0         1         2         3         4         5         6
123456789012345678901234567890123456789012345678901234567890123
* <2014-06-01 Sun 11:41> R9.5 W1.0 初夏の黄砂の中のランニング
  早朝ならなんとか暑さもしのげるだろうと８時に開始。
  風は追い風なし、折り返しで心地よくなる。
  
* <2014-06-03 Tue 19:39> 世の中理不尽横行す

ホークスの交流戦みてたらまだ暴力団に金渡した監督が
でけーつらしてやってんじゃねーか。
どうなってやがんだこの世の中はよ。
いつのまにか復活した国民背番号制といい。
あんまりひどいことが横行し過ぎでないですかい。
家のちかくにに福岡教育大ってのがあるんです、
国立で例の龍馬馬鹿の武田てつやさんが入ったか出たか
ですが。この人のドラマで人という字は棒と棒が互いに
支え合っているなんて事をいいましたが、
どう考えても一方の棒が一方の棒に寄りかかっているとしか
思えませんよ。人という字はね。
貧乏弱者が金持ちやずるい人を必死にささえているんじゃないですかい。
そんなずるい人がスポーツの世界にでけーつらしているのに
それが人気一番のチームなんですかい。
どうやったらそんなに寛大に生きていけるんですかいそのなんとかという
東京の新聞のチームさんよ。
まあ。
そういう私も金持ちになって甘い汁をすうこと夢見てましたから。
同じもんですけんど。
挫折しなきゃ人を犠牲にして甘い汁を吸っていたんでしょう。
夢は破れて、惨めな人間になりましたが、まだ死なせてくれないから
生きていこうと思っています。
みじめな馬鹿でもそれなりにプライドは残っています。
ホークス見たいけどこういう輩を見たくないんですよ。
なんとかなりませんかね。
だから今pcでTV画面かくして音声だけ聞いているんです。
* <2014-06-03 Tue 20:07> アウトラインプロセッサ
  はずかしながらアウトラインプロセッサというのを知りませんでした。
  すこしいうとoutline modeは使った事あります。
  しらなかったから知らないでいいです。
  これなにかというと概要を編集するエディターです。
  私のブログは、emacs でテキストを書いてそれをコピペして投稿しています。
　誤字脱字は表現だからしようがない。文章もめちゃくちゃだが表現だからしようがない。
　それが少しましにできるかもしれないのがアウトラインプロセッサーです。

| 01 | 02 | 03 | 04 | 05 | 05 | 07 | 08 | 09 | 10 | 11 |
|    |    |    |    |    |    |    |    |    |    |    |
* my history.

* <2014-06-05 Thu 16:02> R9.2.W1.0 久しぶりの中３日のラン
仕事を干されたので中三日での平日ランにでました。
このところ油もんバッカたべてしまって、平素より２kgも増えていて
リセットしたかったので、梅雨入り間もない時期ですが、
涼しい晴れ間が広がったのでチャンスでした。
湿度は高いが真夏のまとわりつくような湿度ではないので快適でした。
build up の方は折り返しでかけられず、ラスト1.5kmで4分代に上げて
フィニッシュ。2kgは減ったと思ったのですが、1.2kg減、どうも最近
水分の減りが少ない気がしています。
それと気がつかないふりをしていましたが、皮下脂肪ってますね。
だれかに気をつかう境涯にないのでどうでもいいです。

今年になった栃木だの百道だので地元に目をむけることができなかったのですが、
久々に鐘崎や波津漁港に釣り状況を見に行きました。
波津の漁港もすこし見ない間にトイレがあたらしくなったり漁港施設もも整備されたり
しています。
鐘崎漁港にいたっては、口上（こうじょう）波止場の沖に波止場作ってます。
なんということでしょうか。
こういう光景を見るたびに胸が痛くなります。
地方交付税の使い道はこういうところにでているんだと思います。
使い道が無いんです。
かつて私の両親は、退職金などが入ったが何も買うものがなく最後に
仏壇買いました。
そのノリでしょう。都会の企業の税金がこんなところでコンクリートになってます。
地元の民もうれしくありませんし都会の企業もうれしくないでしょう。
防波堤のお陰でいままでの波止場が砂に埋まっていってます。
海流のちょっとした変化で自然は大きく様変わりします。
ほんとに胸が痛む。
愚かすぎるぞ。
こういったことはずいぶんと見てきてます。
この１０年でこの当たりの漁港は大変な様変わりをしています。
不要なコンクリート物がいくつも立っています。
きんちゃく網やら、大きな２堰の船で数百メートル幅の引き網をして根こそぎ魚を
とるもんだから魚いません。
そういう船は小さな魚は売り物にならないから沖合で捨ててきます。
そういうくずの魚が支える生命の循環は途絶える事になります。
そんな未来への希望のない愚業が行われています。
遅効交付税で漁港は整備されましたが魚がいません。
なんでこんなに愚かなことが起きているんでしょう。
どうすればいいんでしょうか。
あきらめるしかありませんね。
いや滅びるほか再生はないんでしょう。
人間どもは、はやく滅びてください。
* <2014-06-06 Fri 17:38> mac の emacs のフォントが糞に
  emacs 22から24にしたら、
  漢字がかすれた感じのフォントになってしまって、
  老眼と近眼としょぼしょぼ目にはつらくてつらくてしょうがない。
  フォントサイズを拡大して入力しているけど拡大しても汚すぎの
  フォントはストレスを感じて、いらいらいらいらしてくる。
  それはそうだが、msとかmacとか文句ばっかり書いています。
  windows が糞ならmacは糞と同じようなもんだな。
  思ってます。
  確信に変わっています。
  だから、ubuntuにしようかと思ったけど、unityになって、
  こいれももうやるきなくなった。
  もういいや、なんでも。
  おいれは、emacs でやれればそれでいいんだ。
  emacs で、mh-eして、shellしてられればいんだ。
  そいれに気づきましたんです。
  emacs こんなに長く使ったソフトあったかいな。
  ８７年ころから使って２５年かいな。最初はよくカスタマイズ
  してたけど、もうMSが開発環境になって、やめちゃった。
  仕事の環境が変わるたびに環境を整えるのがうざくなった。
  もちこみPCもできないし。
  あるもの使って、手っ取り早くできる環境で、必要最小限のキーバインドと
  コマンドだけでやっていた。
  ほんとうにごめんなさいemacsさん。
  あなたと一緒に棺桶に入ります。
  だからそいれの方向で生きていこうと思うんです。
　で、その矢先にフォントが糞になったんです。
  人生は楽はありません。
  emacs 22 のフォントがどんだけよかったかも忘れちゃいました。
  でも環境というemacsを育てていきます。
  MS/APPLEの糞どもからの脱却方法のただひとつ答が昔からemacs に
  あったのです。
  それを見つけたんです。
  
* <2014-06-07 Sat 08:44> きんりょうへん動かざること造花のごとし
  今年のはじめに、きんりょうへんをアマゾンで買いました。
  花芽確認済みということで５０００円もしましたが、
  花芽は偽物でした。
  茎の切り口のようなものが出ているのでそれらしく見えるだけです。
  プロが間違うわけもないと思うので詐欺でしょう。
  その後、葉っぱは、枯れもせず、伸びもせず、ほんとうに造化のように
  変化しません。
  日に当ててもあてなくても変化しません。
  花はさかず、みつばちを集める事もなく。
  今シーズンは終わりを迎えるようです。

* <2014-06-09 Mon 08:51> R9.2 W2.0 引き続き中三日のラン
  早朝ランを開始したものの１００ｍも走らないうちに右足首に違和感が出る。
  ストレッチしていろいろ速度変えたり試してみても取れないので500mでストップ。
  今日走らないのはもったいないので１５時から開始。
  ここ数週間で68kg後半まで体重が増えているため、内臓脂肪が増えているのが
  あきらかにわかる。体幹のフォームを確認しても腹が重い。
  ３ｋｍも折り返しまできつい。
  折り返しでストレッチ入れて、走りだすと無風焚き火の励ましを得る。
  しかし、体がbuild upに反応する。
  無風の焚き火に頬と耳の後ろが熱る。体は行けるらしい。
  体に任せてラスト１ｋｍで失速。
  ラスト５００ｍまで失速。そこから少し上げて心拍上げてフィニッシュ。
*2 <2014-06-09 Mon 09:19> mid ship two seater をkey less entry
  愛車のミッドシップ２シーターをキーレスエントリーにしたい。
* <2014-06-16 Mon 20:49>　R15.0 W1.0 海の中道マラソン依頼の１０ｋｍオーバーかな
  梅雨に入って雨はふらず湿度は高いが、朝は冷える。
  だから、飯も食わず朝を狙って走った。
  中４日になったが立ち上がりは重い。
  もうランニングして６年目なのに、何回も繰り返しているのに、
  立ち上がりは重い、重いのがわかってるから、1kmを7分半というのを守る。
  ５００ｍだけそのスピードを守る。これは絶対だ。
  その後も体調を見るというか自分の何かを聞く、いや感じる。
  同じコースだが景色や体調は無限の組み合わせのただ一つだけのシチュエーションという
  ものを味あわせてくれる。
  自分の足音は、軽いのか。
  風は、自分に向かっている、自分が向かっているのか。
  空気は澄んでいるのか、異臭かなにかするのか。
  空は青く澄み切っているのか、
  よどんでいて、その力をもらえないのか、
  電柱の続く電線にカラスはまたも鳴いているのか。
  俺に糞を落とす準備をしているかどうか。
  工場に務める従業員のその姿がその働く喜びを羨望をもって景色
  の過去に忘れされるか。
  この農道の横の農作物は従事者の生真面目な素性の良さを反映して
  実っていて、満たされている。季節のそれぞれの実りを米とか麦とか
  の朝のまあ遅い時だがそれでも、また夕日の輝きに栄光の黄金色を見せているのか。
  そういうことを景色と俺の体と相反するかどうかわからないが、
  そんなものとランニングというものをやりながら、
  楽しんでいる。
  ここまでは楽しんでいるのかいないのかわからないが。
  ランニングを終わったら、楽しんでいると思うから続くんだ。
  楽しんでいるから、続いているんじゃない。
  苦しいから続いているんだ。
  それは、俺一人苦しんでいるから続くんだよ。
  逆にね。組織や人やあえていうよ。夫婦でも親と子でも、
  それは二人称になったときは、たぶんまったく刃も立たない。
  あえて言いたいけど、国境とか第二行政界とかそこまで続く。
  ランニングはひとりだけただひとりだけの問題を見つめて、
  いるんだから、とっても幸せなんだ。
  俺にとってランニングはただひとつの自分の中で見つけた自由だ。
  うん。
  それで、今日はとっても快調だった。
  いつもの9.2kmと思ったけど、その後、骨盤の回旋もスムーズ。
  体幹メソッドは素晴らしいね。

  
  
 
* <2014-06-17 Tue 10:32>　ラジオ体操やらされる馬鹿ども
  いまどき朝っぱらからラジオ体操をやっているバカ会社あるんです。
  どいつもこいつもやる気のない素振りでやっているところが。
  あるんです。
  半世紀以上前のしょうもない運動やっていることろが。
  あるんです。
  こんなのまじめにやれば少しは体にいいかもしれませんが。
  ほとんど意味が無いと思われる。
  栃木出張の時の工場でもやってなかったなあ。
  ううん。
  わかる気がしてきたラジオ体操の採用とさまざまな仕事ぶりの
  因果関係が。
  MS採用とラジオ体操採用の因果関係が。
  アベどもが、成果によって報酬が決まる新たな「労働時間制度」の創設
  などと馬鹿なことを言ってますが。
  どこまで庶民を苦しめる政策とろうとしているんでしょかね。
  こいつらの考える成果とは、MS流の成果のこと。インスタンスに対する
  操作とその結果の数のこと、どこまで人間を人間扱いさせないように
  しようとしているんだよ。
  それを気づかないでラジオ体操やるバカどもも愚かだが、哀れに思えて
  来た。
  もういい。俺も哀れだ。
  残念ながらこの方向性は、２２５先物が２２５００円になるまで続くよ。
  かといってその後がいい方向には向くわけではない。
  バブル崩壊後荒んできた今日がまだ底辺ではなくまだ先があるということだ。
  人間なんて滅びればいいのだが、滅び方が問題だ。
  蛇の生殺し的に滅びるんだな。
  ここのところやるせない怒りの灯火が心の闇の中に灯ったのである。
  が、それは、住民税と県民税が所得の１０％ 来やがったことだった。
  都会の企業は、４０％税金取られて今まで文句も言わずにかしらんけど。
  税金さがるのは良かったね。でもそこで働く庶民は、あいかわらず、
  田舎でコンクリート買うために違うとこから税金取られるんだけどね。
  よかったかな。しかも知的生産とは縁遠い、MS生産やらされてさ。
  どこに黒幕がいるのか、しりませんけど。
  今日のワールドカップのガーナとアメリカ戦。
  心底ガーナを応援したもんさ。
  負けちゃったな、あんなにシュート
* <2014-f06-18 Wed 07:46>　メガネメガネ
  老眼と近視は逆のものだから老眼になれば近視が解消されて
  メガネが不要なハッピーな生活がくるのかと思っていましたが、
  そんな夢は来ないんだ。夢は打ち砕かれて、近場が見えず、
  おまけに目がしょぼしょぼして、右目だけがドライにもなって、
  目薬さしたり、涙がでたりで、レンズが汚れて、なんども拭いていると
  レンズのコーティングが剥がれて、傷もついて、どんどん
  悪循環してきて、とどの詰まり、MS流の労働生産活動に支障が出て、
  辛い。
  それでメガネを買い換えることにしました。
  ポイントは、２つ、
  ○老眼を入れるかどうか。
  ○鼻盛り（老眼はちょっとだけメガネを浮かすと見やすいころがある）
  　を調整できるか。
  だ。
  老眼と近視の共存メガネにすると、もともと分厚い渦巻きレンズが
  もっと分厚い渦巻きレンズになるらしい。
  せっかく、プラスティックレンズにしているのだから、重くはしたくない。
  よって前者を却下。
  鼻盛り調整は、金属のものは調整してベストなポジションをさぐれる。
  だが、荒っぽい私にはすぐに曲がってしまう。
  プラステックも調整できるが、ジェルで貼り付けるものは１月も持たない。
  鼻くそのようなものがつくのでみっともない。
  接着剤で鼻盛りするのも同じくみっともない。
  ここまでがメガネ屋２件回って得たものです。
  でまたメガネ市場に来てしまった。
  ここだけ、私の過去のデータが取れるらしい。
  名前とショップ名のキー探したら今のメガネが検索できた。
  驚くことにこれ２００８年に作ったものだった。
  といってもフレームとレンズは２回ダメになったから変えているので
  物理的なものは違うがレンズのスペックは同じだ。
  再度検査して、試作用のメガネをかけると、同じスペックでも
  近場も遠くも見える。
  今のメガネはプラスチックの鼻盛りだが低すぎなんだ。
  試作のメガネは鼻盛りが金属で高いんだ。
  きっと老眼は６年で悪化してきたからこのメガネの鼻盛りの低さは
  今が限界付近なんだろう。
  それと近場用にもうひとつレンズを試してくれた。
  このレンズは、眼球の黒目とレンズの距離でもっとも見やすい位置
  を無断階で探れるというやつらしい。
  通常の老眼鏡は上下２段になっているけど、これは無断階になるもの
  です。で結局このままのスペックでは老眼の悪化に対応できないだろうと。
  このレンズを設定することにしました。
  それから去年の今頃近場だけのメガネを買っていてそれが金属の鼻盛り
  だったので、それに今回のレンズを取り付けることにしました。
  ですので金属の鼻盛りになりました。
  金属鼻盛りと老眼鏡のセットで快適なものになるか来週レンズができるので
  楽しみだな。
  でも今調べたら疲れて合わない場合もあるるらいいが、
  私はどうも一般スタンダードなものが合わないのでやってみるしかないのです。
* <2014-06-22 Sun 15:46>　R7.0 W2.0 絶不調、右股関節痛
  雨の合間をみて朝１０時ランニング開始、気温は低し、風もあるので、
  気候条件じゃなく、不摂生の影響で、絶不調、右股関節痛もでた。
  なんども歩いてストレッチして、ラストWSで決めるかと思ったんですが、
  続かず、フィニッシュ。
* <2014-06-28 Sat 18:03> R4.0 W1.0 不調
  夕方飲み会前のランニング。
  あんまり走りたくない気がして、５ｋｍの予定たてましたが。
  途中なんども歩いてしまった。
  なんかやる気が起こらない。
  体調が悪いわけでもない。
  イジケ魂が出ているわけではない。
  はしりながら考えると日頃の仕事や生活の中にある自信のなさ
  や老いへの恐怖心などが鬱積しているような気がする。
  
* <2014-07-05 Sat 16:35> apple MSほどではないがくそになりつつあるね
  ちょっとweb を覗いて、mac book air をしまって放置していたら、
  なぜかファンがぶんぶん回っていて、開けると画面が黒いまま回復しない。
  やばい雰囲気がしたが電源ボタン長押しで落として、
  電源いれるとまたファンがぶんぶまわって回復しない。
  ついに来たかと焦りだしてなんどかトライするもダメだ。
  apple 天神に電話するとapple のテクニカルに電話しろという。
  電話すると、リセットキー(control+shift+option それに電源キーを
  押してすぐに放す)試すし変化しないのを確認して電源オンするが
  変わらない状態この時点で機械故障と判断される。
  データはバックアップ取っていないというと回復業者を紹介すると
  いって、２つ紹介された。
  その一番目に電話すると浮かぬ対応だ。
  SSDだと60万円かかるとふざけたことを言う。
  ちなみにHDだと7万円だそうだ。
  もう一台macがあるとそちらからSSDにアクセスしてデータを
  取り出せる可能性があるらしい。
  apple の修理はSSD初期化が基本でそれを承認しないといけない。
  再度、テクニカルに電話すると今度は修理業者を紹介される。
  そこに電話すると営業していないので、。
  再再度、テクニカルに電話するとapple 天神に相談しろという。
  おい、役所仕事か、たらい回しでもどってきたよ。
  apple テクニカルはもう一台のapple から取り出しを試みる
  サービスなどはやらないと言い切っていたんだが、
  apple 天神では、9800 円で試せるようなことを言ってる。
  iphone でapple 天神ストアを予約して、不運な自分
  時間を悲観しながら時間を過ごしていると諦めきれないから
  また、電源オンを試してみる。
  なんと、じゃーんという音と共に復活なんということだ。
  いつまた起こるかもしれないので、この状態でバックアップだ。
  64GのUSBを買ってきて、ついでにDVD-Rも買ってきて、
  必要な物だけとったら安心した。
  のどもと過ぎればなんとかだ。
  もうそのままこんなブログを書いている。
  おいれは馬鹿だよ。
  Picture が41Gあって、スプリットしなきゃDVDに入らないので
  面倒くさくなった。
  おいれは馬鹿だよ。
  いいや糞はおいれです。
  もちろんapple store のキャンセルなんかしてません。
  テクニカルは、すこし前はもっとマシだったと思う。
  


  
  
  


  **
* <2014-07-06 Sun 15:51> mac book air は故障のようです
  やはりmac を閉じるとだめのようです。
  ハードディスクを買いました。
  elecom 1TB ８１００円一番安くて、
  snow leopard ver 10.68 に対応しているもの
  今タイムマシンでバックアップ作成中です。
  ポータブルHDは7.5cm X 12cmちっちゃいなあ。
  2010/10位に買ったこのmac book air もまる４年
  になるんだなあ。
  mac のよいところは、emacs キーライクですべての
  テキスト編集ができることだ。
  これが気に入ったからwindows なんかを買う気がない。
  emacs キーでgoogle 検索もできるからなんといいことか。
  他にいいところなんかない。
  iphoto なんかも使いにくいし、finder も糞だし、
  いつも使い方にまようんだよな。
  先月末から新しいプロジェクトにはいっているんだけど。
  92年位に直接チームになったことはないんけど、
  フロアーであったことがある人と一緒になった。
  先方は私に気づいたがどこで知り合っていたか
  思い出せない。
  可能性のあるプロジェクトを上げてもヒットしない。
  最近の記憶に的を絞ったから、まさか２０数年前とは
  思っても見なかった。
  年齢も同じだった。
  その人もcontrol-key の位置は変えていないよ。
  どこにいったおいれのemacs 友達は。
  さて５時間かけてtime machine が終わって
  バックアップが作成された。
  無償と聞いていたけど、無償はテクニカルだけらしい。
  apple に依頼すると一律４万からになるらしい。
  落とした後があるから高いらしい。
  またストアに持ち込むことにした。

* <2014-07-06 Sun 16:39> mac book air 回復か
  一旦システムを終了させて落とした後、
  立ち上げ直し、閉じても、ファンがぶんぶん回って
  真っ黒画面という現象がでない。
  ううん再現せずでは修理もする必要ない。
  しかもサクサク速さを感じる。
  たまには落としてやらんとイカンやんたんでしょうか。
  バックアップもとれたんで安心なのでしばらく様子を
  みることにします。
  今週はランニングは行きそびれました。
  昨日は、このトラブルで時間撮られたし。
  今日は、大雨だし、見送ることにしました。
  
* <2014-07-12 Sat 18:49> R9.0 W2.0 １４日ぶりのラン
  朝出発したかったが歯医者を予約していたので無理だった。
  少し暑い感じだけで風もありそうなので１５時スタート。
  重いのはわかっていたが、我慢して走る、6分巡航が限界だった。
  遅いとやっぱり股関節痛コーチがでてくる。
  股関節痛コーチは、ロードバイクに乗っていることが誘因で
  起こるのはわかっているが、なぜ起こるかはまだわからない。
  対処としては入念な股関節回しのストレッチとフォームでの
  骨盤傾斜を意識してスピードを出すことしかない。
  いろんな文句が多い最近のブログだがまた、TABIO の靴下の
  文句を言いたい。
  いままで何度も大会で走ったソックスもTABIO だったが
  やっぱり、先端側の土踏まずに擦り傷ができる。
  １４日も開けたから皮膚が弱っていたんでたった6kmでこれが
  でた。
  それともう一つ走り終えた後足の指や裏がつるんだ。
  今日はフィニッシュまじかで雨がふりだしたため
  足が濡れてしまったことも大きいが、この靴下は
  疲れさせる靴下だった。
  まったく、しょうもないもの買って、こんなに長い間、
  間違いに気が付かなかった。
  いまのところの靴下選択結論としては、
  柔らかいこと
  五本指（大会以外ならこれでなくていい）
  それなりの暑さであること。
  スベラーズのゴムは付いていたほうがいい。
  という感じだ。
  安いものでも十分だ。
  今日は折り返して、乗らず、歩いて気持ちの整理を
  して再び走ってフィニッシュ１ｋｍを5分で上げて、
  おしまい。ラストは２００ｍずるして終わった。



  
* <2014-07-13 Sun 13:59>　縁
  縁とは、かくも不思議なものだろうか。
  最近２０数年前の知人にプロジェクトで再開したと書いた。
  そこにまた不思議なものが絡んでくる。
  週末に飲み会があって外部の私達は遅れて参加したのです。
  部の飲み会だったため見知らぬひとがいるなか全部で４テーブルあり
  ８名席が２つと５名席が２つ全部で２０数名の宴会である。
  そのうち席が３つあいており別れて座りました。
  初めて見る人どおし会話が弾むわけではないが前の二人の
  話から、彼の一人がある島の出身と分かった。
  私の前の嫁さんの出身地の島である。
  実家はそこですこしだけ有名なので名前を言うとしっているという。
  高校の生徒のうちそこで世話になっているものもいたとのこと。
  不思議だ。
  ４人席の前の二人がその島に出身と親が出身とだった。
  しばらく飲み会がすすんで、違うテーブルの２０数年前の知人に
  そのことをいうと。なんと彼も母親がその島の出身で自分も
  ２年ほど住んでいたらしい。
  しかも先週末と月曜日にかけてその島で主催されている。
  マラソン（クロカンに近い）でていたというではないか。
  彼も興奮してその島の出身者にスマホのマラソンの写真を見せて
  はしゃいでいる。
  ちなみにその知人と私は同じ年らしい。
  縁とはこんなに不思議なことを起こしてくれる。
  ちなみにまだ不思議なことがある。
  そのプロジェクトの会社がある場所は、かつて私と元嫁が
  同棲していたマンションから５分の位置にある。
  通勤のバスもそのマンション前の停留所をとおる。
  しかも同棲時期はその知人と会った時期にそのものであり。
  私が元嫁の実家に結納云々で島に渡っていた時期に符号するのだ。


  


* <2014-07-13 Sun 14:36>　今日はツール・ド・フランス９日目だよ。
  ツール・ド・フランスは、１９０３年から開催され、今年で１０１回目だ。
  観客動員数１５００万、国別中継数１９０を誇る、
  他の大会とは別格の世界最高の自転車の競技大会さ。
  でもオリンピックみたいに色々な種目があるわけではないんだ。
  スポンサーを要した全２２チーム、１チーム９人で
  ３週間（休息日は１日）毎日２００ｋｍ前後を走って、
  総合タイム：マイヨ・ジョーヌ（黄色）
  山岳賞：マイヨ・ア・ポワ・ルージュ（赤の水玉）
  ポイント賞：マイヨ・ヴェール（緑）
  新人賞：マイヨ・ブラン（白）
  を競うんだ。
  それぞれに右の名前のジャージ（マイヨ）が与えられるんだ。
  一日一日はステージと呼ばれ、その度にポイントやタイムで
  各ジャージの勝者が決まるんだ。
  でもこれはいわば暫定順位で、最期の日に、
  それぞれの最終順位が決まる。
  暫定順位でもすごい名誉だけどね。
  総合勝者のマイヨ・ジョーヌの最高の栄誉になるんだ。
  この大会は１００年以上、観戦スポーツとしての
  洗練された成長をしていきているからあらゆる観戦スポーツ
  の面白さが凝縮されているんだ。
  小さな人も大きな人もひとつの大会で活躍できるように作られ、
  チーム戦でありながら個人競技でもあるし、
  スポンサーチームの戦いでありながら時にチームを超えて
  国のために協力しあうこともあるんだ。
  コースは、フランスの世界遺産や準ずるお城や景色の素晴らしい
  場所が設定されていたり、ひまわり畑を走ったり、
  きれいな海岸線や、渓流を縫うような道路を走ったりするんだ。
* <2014-07-13 Sun 16:24> きょわ９日目のツール・ド・フランスだよ
  おいらの夏の楽しみは、ツール・ド・フランスだ。
  知らない人のためにちょっと書いとくね。
  ツール・ド・フランスは、１９０３年から開催され、
  今年で１０１回目だ。
  観客動員数１５００万、国別中継数１９０を誇る、
  他の大会とは別格の世界最高の自転車の競技大会さ。
  でもオリンピックみたいに色々な種目があるわけではないんだ。
  スポンサーを要した全２２チーム、１チーム９人で
  ３週間（休息日は１日）毎日２００ｋｍ前後を走って、
  総合タイム：マイヨ・ジョーヌ（黄色）
  山岳賞：マイヨ・ア・ポワ・ルージュ（赤の水玉）
  ポイント賞：マイヨ・ヴェール（緑）
  新人賞：マイヨ・ブラン（白）
  を競うんだ。
  それぞれに右の名前のジャージ（マイヨ）が与えられるんだ。
  一日一日はステージと呼ばれ、その度にポイントやタイムで
  各ジャージの勝者が決まるんだ。
  でもこれはいわば暫定順位で、最期の日に、
  それぞれの最終順位が決まる。
  各ステージ優勝もすごい名誉だけど。
  総合勝者のマイヨ・ジョーヌの最高の栄誉になるんだ。

  
  


  



* <2014-07-19 Sat 14:34> 手作りケチャップ
  家庭菜園でミニトマトが収穫できたので、
  ケチャップを作ってみた。
  トマトを適当に斬って、玉ねぎとにんにくを
  みじん切りにして、砂糖と塩と胡椒をいれて
  ミキサーにかけて、それをフライパンで
  適当に水分が飛ぶまで煮て、
  酢をいれて味を整えておしまい。
  味は悪いな。ぱっとしないな。
  酸味も甘さもインパクトがない。
  さっそくチキンライスを作って、オムライスの出来上がり。
  とは言え、自分で作ったトマトとケチャップだからうまい。


* <2014-07-20 Sun 19:26> R3.0 W2.0 今年最悪
  本当は昨日の夕方走るつもりが大谷と藤浪が始まったので、
  やめて、今日の４時から走ってきました。
  風は海からのものがあって、涼しさも感じられたが、
  湿度がすごい。
  折り返しから焚き火の熱風状態になるのがわかったから、
  3kmでやめた。
  なんともつまらない。
  走りで終わった。



* <2014-07-26 Sat 08:53> 未来
  未来がわかったら金儲けできる。
  あくなき欲望が湧いてきて消える。
* <2014-08-01 Fri 18:01> TOTAL_R(12.0) R5.0 W3.5 最悪から２番め
  小雨まじりだが走りに問題ないので夕方５時過ぎに開始しました。
  ３ｋｍまではなんとか行けたが４ｋｍで折り返してしまった。
  発作感がでて辛いからしばらく行くがフィニッシュポイントまで走れず。
  ５００ｍほど歩いてまた走りたくなった。
  ５分代で走るも右後ろ太ももがつってあえなく終了です。
  走る精神がなっていないな。
  決して暑さや湿気のせいではない。
  先月は、12kmしか走っていない。
  もうすこし頑張らないと。
* <2014-08-09 Sat 18:25> R9.2 W1.5 無理して伸ばす
  今日もきついのはわかっていましたが、ここらへんで踏ん張っていないと
  回復不能に陥るので、3kmで我慢して、4kmで我慢して、5km 内蔵がすっと
  これが内蔵の汗だろう。
  すこし軽くなって骨盤の回旋も良くなってきた。
  だがきついのが出てきて、build up できない。
  最後の1km で上げて終わりだろうと、頑張るが
  このところの練習不足によるものは上げさせてくれない。
  最後までダメでフィニッシュしました。
  10/19 の直方マラソンにエントリーする予定なので、
  あと２月近いので練習方法にインターバルを入れようと思う。
  盆休みで少し体をいじめよう。
  
* <2014-08-17 Sun 12:39>　R3.0 w3.0 まだだめだす。
  走り始めてすぐに内臓の調子がいいがわかって今日は楽しい走りができると
  おもったのもつかの間、１０時過ぎで晴れて太陽が出てきて照り返しを感じる
  暑さになってきた。
  我慢できるず３ｋｍで終わり。
  

* <2014-08-23 Sat 12:54> R9.2 W1.5 今夏初めて朝練 
 朝７時過ぎからスタート、いつものように３ｋｍで４ｋｍ壁が
 なんかいも襲ってくるけど、
 それは何回もの経験の中で、培ってきただろう。
 そのはずの体を信じて走ろうとする。
 でもいつものように３ｋｍと４ｋｍで苦しい、歩けば楽になる
 という体と心が訴えかけてくる。
 その声はなんどもなんども聞いている。
 だから、その声を無視して、ただ６分以上の走りでも、
 走ることを続ける。
 風は、味方にならない。
 でも方向は折り返しで味方になるはず。
 自分で風を起こせば、涼しくなるよ。
 でも湿度はねとっとした汗を体にまとわつかせるよ。
 でも我慢して走ればきっと清々しい走りに変われるはずだから
 やめるんじゃない。
 そういう葛藤の中で、走り終わった。
 最後の１ｋｍは５分後半まででフィニッシュ。
 次に繋げたいと思う。



  
* <2014-08-31 Sun 22:00> R9.2 W.15 今日も頑張った
  今週もきついのはわかっている。
  走ることが辛くなったわけではなく。
  気象や生活の条件が合わないだけで、
  私のランニング人生というか生きがいというものに何ら
  変化はない。
  苦しさがなんどもなんども襲ってくるが、
  それでもラストは５分前はまで上げて、フィニッシュ。
  それで満足した。
  リセットできた。
  そうだ。
  秋のランニング大会、エントリーミスでハーフ走れなくなった。
  だから、篠栗の山の大会に１１月エントリーした。

  
* <2014-09-06 Sat 16:12>　R9.2 W1.5 今日も頑張った

  昨日酒を控えて、朝６時くらいから開始、
  相変わらず、きついけど、最後まで走った。
  ラスト1.5km でbuild up するにも上がらず、
  もがいていると後ろから足音が、
  すぐに抜かれて２０ｍ差をつけられる、
  後500m で踏ん張って、差を縮めていく、
  ラスト１００ｍでスパートゴール前に
  抜き返して、ごめんね。
  たまたまそこがゴールだったんだ。

  

* <2014-09-14 Sun 20:09>　R4.0 w1.5 今日は負けた
  秋の午後４時湿度はいままでのように
  高くないのをすぐに感じるほどだった。
  しかしどうもまたいじけ虫が出てきてやめさせようとする。
  あえなく、３ｋｍでやめた。
  そのまま折り返して歩くうち、やっぱり後WSしたくなった。
  １ｋｍフォームを確かめるも５００ｍ前でまたやめた。
  なんか面白く無い。
  
  
* <2014-09-20 Sat 16:43> iphone5 割れる
  寝る間際に財布とiphone もって部屋に戻るとき
  iphone がすり抜けて落下、打ち所が悪くクシャっ
  という変な音を立てた、前面のガラスが見事に、
  スパイダーマンになってました。
  １７日の夜に起こって今まで使えています。
  この十字架は一生もんでしょうか。
  iphone6 の発売が昨日だからこの割れたやつ
  でdocomo に下取りさせようとしたが、
  無理っぽいね。
  甘い。
  このiphone5 は3/26に保険で直している。
  実払いは４０００円だった。
  直しているというか、バッテリーの減りが半端
  ないから交換したんですが、新しいのも
  減りは同じだった。
  どうもLine Play が犯人のようだった。
  それから半年まで後一週間。
  実は次の保険が効くまでに半年あるらしい。
  あと一週間で保険が効きそうだからそこで
  直して下取りさせて、ついでに前の4s
  も下取りさせて、めでたくソフトバンクの
  糞から復帰できるか。
  さっき調べたら、SBの更新が来年７月なの
  で違約金が10200円かかるそうだ。
  docomo で聞いたらiphone6 の在庫が
  シルバーと他の色のならあるらしい。
  どうしようかな。
  apple 天神に持ち込みで店頭３時間待ち、
  修理に３時間だそうだ。
  修理は16000円だそうで保険がきけば２４００円
  で直る。
  とすると９台目にする必要もないな。
  保険がどうなっているかSBに連絡してみよう。
  番号押させて長々待たせた挙句教えてもらいました。
  2014/3/28 手続き完了から１８０日だそうで、
  正確にはと聞くと9/29 以降ってこきやがった。
  日付　計算というサイトで調べると9/25 あたり
  に180日経過してるじゃん。
  そうすると来週には直せるじゃん。
  この糞野郎。
  平日はapple 天神が夜７時前までだから
  それから２、３時間待つの辛いじゃねーの。
  apple 天神の予約が一週間詰まっているらし。
  ２日かけて直せばいいかな。
  そうしよう。
  今日は、iphone のバックアップもmacの
  バックアップもとったんで安心パックでねれます。
  てか、この安心パック月500円なのね。
  この暇つぶし道具には、よくもこんだけ金使わされた
  もんだな。
  iphone にする前は、docomo のガラケーで月
  ２０００円以下なかったのに今８０００円超えてるし。
  ３年で携帯８台はないだろう。
  糞やろう。
  やられたらやり返す。
  倍どりだ。
  むなし。

  
  
  
  
  
  



  
  

  

  

* <2014-09-22 Mon 23:03>　R9.0 W1.5 彼岸のラン
  前回４ｋｍで挫折していたから今回は覚悟で向かう。
  なんども走っていたから走れないわけがない。
  気温も苦にならないはず湿度も乾いて、風もある。
  苦しいのは３ｋｍと４ｋｍと５ｋｍにやってくる。
  目先のことは昼飯になにを食っているかわからない、
  明日の開発言語もわからない。
  一寸先は闇だけど。
  少しは自分の体のこともわかってきた。
  思った通りにきつい。
  ただ５ｋｍの折り返しから体が反応してbuild up
  するはず、反応している。
  でも足にもきている。
  これはここ２ヶ月車通勤に変えたことによるものだ。
  だめそうになるけど。
  頑張る残り８００ｍでスパートをかける。
  最後３００ｍやめるのかやめないのか。
  なにやっているのかわからないままフィニッシュ。
  ランニングコースの横に彼岸花の帯が見えた。
  彼岸花には蜜をすうためにカラスアゲハが何匹も
  群がっている。
  赤と黒の妖艶でありながら神聖さもある光景だ。
  彼岸は死者と近い期間、その道に赤と黒の花達。
  彼岸のランです。
  直方マラソンはエントリーミスで間に合わなかった。
  そのかわり篠栗の山を１２ｋｍ走るやつにエントリ
  して金も払った。
  これからは、インターバルなんかを取り入れないと
  いけないと思う。
  アップダウンは本来おいれの本能のうちから
  蓄積された神経とリズムと判断で可能な一番
  才能を感じるセッションだ。
  これに目覚めれば、またあたらしい、遊び
  が始まるかもしれません。
  

  

  
* <2014-09-23 Tue> インプラント治療
  ６月の末に１８年つけていた前の上の歯の差し歯がとれた
  そのご病院に行ってなおしてもらっていたのですが。
  どうも根の葉の部分が割れているらしいとのこと、
  実家の近くの歯医者では抜く、抜くといって、ぐらぐら
  している奥歯の親知らずも抜いて２本抜かれてしまっていた。
  前歯はブリッジにするしかないらしい。
  健康な歯を２本削るのは良くないし、ここらへんの田舎
  の歯医者はもう信用できそうにない。
  でインプラントを考えた。
  
  
* <2014-09-24 Wed 23:43>　しらんがな
  + イスラム国
    わすれた、こんな名前聞いたことないな。
    体外やめろ、アメリカよしね。
    アメリカの国民よ。
    ちゃんとやれ。
    どうでもいいことじゃないぞ。
    ちゃんと、オバマみたいなの
    選んだ責任を国民がとれよ。
    以上です。
    
* <2014-09-28 Sun 17:51> R2.0 W2.0 最近の最悪
  こんなに走れなかったのは久しぶり、
  胸がいたくなったから無理しませんでした。

* <2014-10-05 Sun 17:53> R9.2 W1.5 秋ランニング開始
  今日は手足に寒さを感じるほどだったので
  11時から開始しました。
  先週のつけはわかっていたので、
  我慢我慢の走りでした。
  腰が硬い、腰が落ちてる、入念なストレッチしたつもり
  なのに骨盤の傾斜がうまくいかない。
  折り返しまで我慢すると大丈夫かと思ったが、
  それからも上げられない、最後の1km にかけ、
  なんどか上がらない。
  結局不発に終わってフィニッシュする。

  11月19には山を走るので、
  いつものハーフの練習ではだめだから、
  インターバルを入れないとだめでしょう。
  12km なのでハーフを大会前にいれる必要はないので、
  構える必要もないと思う。
  周りに山はいっぱいあるけど走りに適した山道はないので
  山の練習はインターバルだけだ。
  筋トレはやりたくないけど、やった方が痛い目に
  合わなくて住むかもしれません。

  今日は手足に寒さを感じるほどだったので
  11時から開始しました。
  先週のつけはわかっていたので、
  我慢我慢の走りでした。
  腰が硬い、腰が落ちてる、入念なストレッチしたつもり
  なのに骨盤の傾斜がうまくいかない。
  折り返しまで我慢すると大丈夫かと思ったが、
  それからも上げられない、最後の1km にかけ、
  なんどか上がらない。
  結局不発に終わってフィニッシュする。

  11月19には山を走るので、
  いつものハーフの練習ではだめだから、
  インターバルを入れないとだめでしょう。
  12km なのでハーフを大会前にいれる必要はないので、
  構える必要もないと思う。
  周りに山はいっぱいあるけど走りに適した山道はないので
  山の練習はインターバルだけだ。
  筋トレはやりたくないけど、やった方が痛い目に
  合わなくて住むかもしれません。  
* [2014-10-11 Sat 13:00] R9.2 W1.5 もうすっかりスポーツの秋
  土曜日朝１０時開始。日はでているものの走りやすかったが、
  車通勤の影響で体が重い、皮下脂肪も増えて、内臓脂肪も
  ついてきたようです。
  肩入れストレッチで太もものを触ると筋肉が落ちているのが
  わかる。
  意識して、肩甲骨を引いて、内蔵を大きく動かしならが走って行くと
  折り返しから、効果がではじめました。
  build up は、体調が良い時のようには行かないものの最後、
  1.5km で５分前半まで上げてフィニッシュ。
  徐々に上げていけば、来月の山もいけるでしょう。
* <2014-10-25 Sat 21:06>　R9.0 W1.5 夕方からのラン
  秋が深まっていますがそれでも昼中のランはしんどいので
  夕方から開始。
  というのも土曜日ランを妨げるものは食事です。
  ヘビーになると３時間は開けないと走れないので、
  良いチャンスにならないし、野球が昼からあるとそれみて
  お菓子なんかをつまむとそれだけで走れなくなる。
  いや走るけど気持ちが悪いし良い結果がでない。
  それで４時半回ってスタート福岡といえど、ラン中に日が暮れた。
  肌寒い感じは、調子の悪さを補ってくれます。
  折り返しからビルドアップもかけることが出来ましたが、
  ここの該当がないので走りづらい。
  それでもまあまあのランニングができました。
  山の大会もひとつき切ったので、インターバルを入れないと
  いけないが、なかなかできない。
  酒を抜くだけの対策で挑むことになりそうです。

* <2014-11-02 Sun 20:44> R9.2 W1.5 昼間まえのランニング
  生活はつまらないことばかりが起こりますが。
  いきがいとしてのランニングは続けています。
  昨日は雨が降って初日に達せられず、３連休の中日のつまり。
  朝、朝を征しようと朝飯を食わず。
  ついだ飯茶碗を流し台に投げつけ、作ったおかずもろとも
  粉砕し。
  そして１１時に走りだした。
  走るために飯を食う時間が合わない。
  飯はどうすればよいのか。
  食わなければいいんだ。
  飯よりは、走ることを優先するんだ。
  飯を食って、あぐらを書いてmac をのぞき込むと
  その無駄なものが腹にあたって不愉快の、ほんのささいな、
  些細すぎる、ブヨがよぎるように、いやくだらないTVから
  流れてくるポピューラーのakbとかなんかクズの音楽が
  クズが作っているCMなどの音楽を聞かされなければならない。
  苦痛と苦痛の間に起こる疼きのような痛痒いような。
  そんなものに飯を食うということがなんとも符合してくる
  嫌な思いをしながら飯を食うことが嫌だから。
  今日は飯を食わずに走った。
  飯を食わずとも同じように３ｋｍの壁が来る。
  走らることをやめさせようとする。いつもの内蔵か。
  一週間の不摂生からくるものか酒か。
  おそらく後者の天使が襲ってくる。
  どうでもいいやめるか。
  やめるのか。
  いな、気候か、遥か彼方に敵は去っていった。
  だから、信じて走れる。
  だから、体は折り返してbuild up しようとする。
  それが嬉しい。
  まだまだ、俺は死んでない。
  いつしか体はいつか前の気持ちのランをやっている。
  ストライドをのばそう、肩甲骨を発端として引こう。
  うん、きつくなれば休んで次のサイクルにかけよう。
  そう。これが俺の走り、数１００ｍでおそらく１分の
  タイム差があるはず。そういう風に循環させながら。
  目標の距離に達するのだ。
  だから自分だけの自由なランニングが好きだ。
  足の裏をアスファルトにベッタっと貼り付くような、
  走りをしていなかったのを後悔した。
  骨盤の傾斜はまだまだだ。
  楽しいランニングの季節と気分になってきたようです。

* <2014-11-09 Sun 21:08> R9.2 W1.5 来週は大会
   来週は大会だけど、今週も３ｋｍから６ｋｍ位まで、
   きつかった。
   軽くなること信じて走って８ｋｍからbuild up
   かけられた。
   すると、ゴール前２００ｍでランナーズ・ハイになった。
   これはやばいという恐怖から思わずゆるめてランナーズハイ
   を断ち切った。





 * <2014-11-15 Sat 16:26> R4.5 W1.5 明日のためのウォームアップ
   今日は思っていたとおり５ｋｍで終わらせました。
   しかし、気候と体調はすこぶるよくいつもならこのまま
   ２５ｋｍ走っても良かったと思う。
   ３ｋｍ折り返してbuild up 4km台まであがていたと思う。
   明日は篠栗マラソンです。
   トレイルとはことなり整備された林道を走るコースらしい。
   ４ｋｍまで２００ｍ弱登る。そのまえ２ｋｍに給水ポイントがある。
   ４ｋｍから７．５ｋｍまで２４０ｍ下る。
   そこに２目の給水ポイント。
   その後１００ｍ登って１０ｋｍ地点、それからゴールまで１．２ｋｍ
   ４０ｍ下るというコースです。
   楽勝でしょうか。

   
   
* <2014-11-16 Sun 10:25> R11.2 W0.0 篠栗マラソン

  朝7時過ぎに車で出発。篠栗駅まで４０分強だ。
  順調にgoogle map のナビで到着。
  駅前の立体駐車場につくここは、SUGOCA でしか
  払えないとあったから事前にSUGOCA にチャージしていた。
  そして、オアシス篠栗という市民施設横に人の列を発見。
  それに従って待つことに、50分くらい待った頃。
  前方２０、３０人になって次のマイクロバスに乗れそうだ。
  バスの送迎は嫌な思い出がある。
  大分では送迎バスが遅れて会場についたのがマラソンスタート
  の直前だったのだ。
  今回は、間に合いそうだが、それにしても後方は２００ｍも
  行列ができている。
  彼らはどうなるのかな。
  大会会場まで２０分だから次のバスが戻るには４０分以上
  かかる計算だ。
  １０時半スタートだから大丈夫かな。
  バスは対向車は、すれ違うことができない。
  避難帯で待つ方式だ。
  しかも急な坂ばかりだ。
  到着すると広場にはで店のテントや受付更衣室のテントが
  ひしめき合っている。
  受付にハガキを渡してゼッケンをもらう。
  更衣室は狭いが総７００人としては十分に機能している。
  着替えて、出て早速ストレッチ開始。
  ストレッチも十分できて荷物を預けて、ウォーム開始。
  １ｋｍやりたがったが、時間が迫るので５００ｍでやめて、
  スタートラインへ戻る、それがスタート１０分前。
  やはり余裕なしだ。
  開始から４ｋｍの２００ｍ弱の上りになるのは承知。
  だが１ｋｍで心臓が山のランニングの苦しさを思い知る。
  心拍数が上がって、抜かれてばかりだ。
  なるほどスタート２ｋｍで給水所がある意味は分かった。
  なんとか耐えて、４ｋｍ登り切ると今度は下りになる。
  下りもスピードを落とす。
  どこで稼ぐんだ。
  稼ぎ場所がない。
  ただ、平坦があるとそこは水を得た魚のように飛ばす。
  だが平坦は極めて少ない。
  ７.5ｋｍまで急な坂を下る。
  腕を振らないとスピードを落とせないほどの急坂もある。
  そこで給水、９ｋｍまでらくできる。
  だがこの９ｋｍからの上りがひどい。
  ランナーは上りで歩いて下りで走るでタイムを稼ぐようだ。
  しかし、私はそんなことはできない。
  どんな坂も走り続けると決心して望んでいたからだ。
  死にそうになっても歩きランナーに抜かれそうになっても
  走った。
  かかりに坂の長さを聞いて作戦立てなおそうとするが。
  だめだ。
  １０登るとスタート直後に登った坂が下りのラストに
  なっている。
  そこを下って、ゴール。
  ２２３中１５７位、１；１７分（１１，２ｋｍ）。
  今春の春のマラソンはほぼ中間順位なので、偏差値
  は４０を下回るところ。
  初戦の山はこんな結果になりました。
  すごいいい練習になった。
  そこで川内方式を導入しようと思った。
  つまり、大会を練習にすることだ。
  そこで１２・１４に１０ｋｍの大会にでます。

<2014-11-22 Sat 11:20>　R9.2 W1.5 日暮れラン
  １５時過ぎラン開始。
  先週の篠栗マラソンがいい練習になったと思ったので
  今週はどんな感じかと期待したが、なぜかいつもと同じ
  ３ｋｍでもきつく、折り返してもきつかった。
  しかし、最後の１．５ｋｍは４分前半まで上げてフィニッシュ。
  この原因がわかった。
  風邪引いていた。
  だからせっかくの３連休風邪治に専念することになった。
  鼻うがいとイソジンうがいと葛根湯でどうだろう。
  明日からの仕事では回復しているといいが。

* <は2014-11-30 Sun 19:25>　R10.0 W0.8　コース変えた

  昨日走りたかったが、風邪がぶり返して、悪化を懸念して。
  今週はもうやめようかと思ったんですが、それでも
  やっぱり走らないと意味のない人生生活となっているので、
  ７：３０に起きて、いつもの飯を用意して食べて、２時間
  一週間でためたビデオを見て、１０時に開始。
  たんは絡んできて、のどに問題があるのがわかるが、
  信じて、３ｋｍ、４ｋｍ、５ｋｍのハードルを超える。
  折り返して、build up 開始する。
  体はいい感じで反応する。
  風邪とはどこにあるのか、探っていても、
  わからない。
  いつものフィニッシュ前の５００ｍ前の橋を
  渡って、ラストの１．２ｋｍ。
  風邪の原因がフィニッシュ後の１．５ｋｍのクールに
  あるのがわかっているので、それを短くするため。
  コースを変更した。
  橋を渡ると道路が問題、車の量があるからだ。
  ここは、実は一度とおるのだが車の往来があって、
  待を余儀なくされる。
  だけど逆は道路沿いを走れば、車の空きを確認して
  渡れるから待がない。
  今日渡りと同時に待ちなし。
  あと１．２ｋｍの仕上げに専念できる。
  車の往来のある道路の歩道はやっぱりへどがでる。
  うるさすぎる、４００ｍ我慢して、ラストの
  自分だけのみつめられる問題に入る。
  今日は実は３ｋｍから雨が降っていた。
  かなり降っているので、上下のウインドブレーカには
  水をすって重い。
  それでもこのラストは５００ｍ直線と５００ｍの
  直線を９０度曲がってラストは電柱が応援してくれる。
  電柱を使えば、感覚からペースを上げるタイミングと
  休むタイミングそしてスパートの目印はとても役に立つ。
  けっこうこの１０ｋｍの最新コースはいけるかもしれない。aaaaa


  
  
  

  
  

  
  

  

* <2014-12-07 Sun 21:52> R10.0 W1.0 辛い
  昨日走るべきだったがディスカバリーチャンネル
  ばかりみて、行きそびれた。
  生きがいと称した、私のランニングそんなことで
  終わるはずもない。
  まずしい朝飯を自分で作って、食って、
  お茶を飲んで消化をまつ、
  こたつに寝転んでただ消化を待つディスカバリーチャンネル
  をみながら。
  もし私にランニングの週課がなければ、どんなに
  つまらない人生だろう。
  どんなに自暴自棄なみすぼらしい。
  ものになるだろう。
  ただ、七日のなかの一日の３時間だけが生きがいというか
  希望になる。
  それが私のランニングだ。
  だがやっぱり苦しい、３ｋｍ、４ｋｍ、５ｋｍの折り返しでも
  苦しい。
  折り返し近くになると地元の野球部の活動に遭遇する。
  ちわー。攻撃に、ちわーと答える。
  迷惑だよ。
  そして折り返し、ストレッチが不足しているから
  ちょっと入れる。
  そしてさつき橋の信号の反対を見ると顧問の先生が
  殿を務めているらしい。
  それを気づいて折り返しをbuild up するために
  意気込んでスタート。
  フォームを試してもなかなかいい感じだと思うが、
  なぜかだめだ。
  乗らない。
  そして顧問の先生にちわーといって抜かれる。
  それほど速いフォームとわいえないがが、
  あっという間に話される。
  キロ１分差があるだろう。
  そのうち最終の女子マネージャーの自転車に
  抜かれる。
  だめだ、なんか調子悪い。
  build up もできない。
  それでスパートもできず、先週の新コース
  の１０ｋｍにも行く気も出ず。
  ９．２ｋｍからジョギング程度に１０ｋｍ
  まで伸ばしておしまいだ。
  来週は１０ｋｍの大会だ。
  なんか俺はだんだんだめだな。
  歳だと思うがそうなのかな、酒だよ。




* <2014-12-14 Sun 15:50> R10.0 海の中道リレーマラソン
  R10.0 海の中道リレーマラソンの１０ｋｍランにでました。
  １０ｋｍのタイムトライアルのつもりが芝生、ダートあり
  の７ｍの障害登坂ありだった。
  １．５ｋｍの周回コースだ。
  フルやハーフのリレーと一緒に走るので、ペースが違う。
  自分のペースも作れず、小学生にも抜かれ、
  さんざんになってフィニッシュ。
  １：０１という数字です。
  芝生走るならでなかった。
  
* <2014-12-21 Sun 16:14> R10.0 W1.5 寒かった
  今日も海風（北風）が強く、日が射すかと思ったが、
  まだらな雲に遮られて、自分の影が見える程度、
  海に向かうと向かい風が強く、かなり体感温度が低い。
  しかし、４ｋｍ過ぎると体調が良いことがわかる。
  久しぶりに釣川河口まで行ってみた。
  というのも先週東京にいって帰るとき飛行機の窓から
  ここが見えたから思わず、写真をとった。
  その写真と対比すると面白いかなと思ったのだ。
  数枚写真とってジョグを楽しむことにした。
  走ることができるとはまさに財だ。
  と思ってしばらく走るとやはりbuild up しだした。
  習性となっているからしかたない、このところ
  フィニッシュ位置を変えようとしているが、
  どこにするか迷った挙句いつもの位置でフィニッシュ。
  かえりの1.5km のクールダウンは寒すぎる。
  しばらく歩いて走ろうとするがもう冷えて走れない。
  寒いのでストレッチも不十分に終えて帰る。

  
  
* <2014-12-28 Sun 12:38> R9.2 W1.5 本年ラストラン
  今日もきつかった。
  折り返しすぎても苦しさが、続いてやめようかと思ったが、
  我慢していたら、すこし良くなって、
  ２ｋｍ前からbuild up できてきた。
  最後まで攻めてフィニッシュできた。
  これが今年最後のランニングでした。
  


* <2015-01-01 Thu 18:38> R2.0 W1.5 ファーストラン

  あけおめさん。
  今日は風が強かった500m走って丘を超えたら、向かい風で
  20m 以上ありそうだった。
  日も出ていないので危険を感じ終了した。
  今年の計は、挫折で終わるのか。
  去年も一昨年も挫折で終わっているから負もこのあたりで
  終わろうと思うと書きたいところだが、
  株の世界では下がる株はもっと下がるという格言があって、
  それは正しいと思っているし、それは人生においても相通じる
  ところがあるとも思っている。
  だから、まだ挫折で終わると予想したほうがいいだろう。
  そういうことを踏まえた上で、今年はまた東京にでようと思っている。
  いったい、なんど帰っては上京を繰り返しているんだ。
  
  
* <2015-01-04 Sun 18:49>　R9.2 W1.5 これがファーストラン

  結局伸ばしに伸ばして連休最後に走った。
  前半は苦しかった、数度歩いた。
  後半持ち直して2km 残してやっと内蔵がスッキリしてきた。
  build up　60%　くらいの出来でフィニッシュ。
  走りに希望がない。
  経年とランニングのスキルは、経年に押されて、スキルがいや
  体力もむしろ下がっている。
  だが、ランニングしなければ生きる意味さえ消滅すると思う。
  今まで何回も書いてきたが、私のランニングを継続するということは
  意志によりあるいは元来の勤勉さなどから継続しているものではない。
  ランニング後の達成感の脳内モルヒネを味わうためにやっているのだ。
  この中毒への欲がランニングを継続させているのに他ならない。
  そして人生の中で唯一味わうことのできる自由を満喫することなんだ。
  この閉塞した馬鹿くさい世の中の産業の中で自由などなく不自由と
  そこでうごめく人間と組織は互いに法や規則で束縛し合い。人間本来
  の創造性を失わせてまるで機械が尊いかのように非人非人の烏合の集
  となっている。
  こういう中で生きなければならない私の唯一の精神の自由を開放する
  手段がランニングなのである。
  

  
  
  
* <2015-01-12 Mon 19:13> R10.5 W1.0 やるきがでない３連休
  はじめて、さぼうろうと思ったけど、公開するから３連休最後
  の昼からスタート。
  今日は雨はないものの雲は時々日の光を通しながら素早く流れていき
  風は元旦ほどきつくはないが、それなりにランニングの障壁となっている。
  ただ、我慢はできる。薄いウインドブレーカでも役に立っている。
  内蔵はやはり前半は汗をかくことができずにいつもの障壁になっている。
  それでも信じるだけの経験はあるからランニングを継続する。
  折り返して押し風に変わって、楽にさせた。
  build upはやっぱり体が反応してくる。
  それも9.2km のフィニッシュポイントに対してだ。
  フィニッシュポイントを２つもっていると体の反応だけに委ねるわけには
  いかないのであえて反応を拒絶して、10.5km フィニッシュポイント
  に向かうことにした。
  なんでか、クールに1.5 km はキツイからだこれで風邪を引くことになる。
  だから伸ばしたんだ。でもどうするか気温や風により判断するので、
  ランニングを組み立てにくい。
  でも今日は伸ばした分でスパートできた。
  かなりハードだったみたいで、玄関で靴を脱いで上がろうとしたら、
  ふくらはぎが急激につってきた。こんな激しいつりはいままでなかった
  くらいだ。


  
  

* <2015-01-18 Sun 18:47>　R10.0 W1.0 足音


  TV番組でQちゃんが土佐礼子の練習レポートしていて、
  土佐礼子はまだ本調子じゃないというのを足音で判断していました。
  足音を聞いただけで調子がわかるということをいつも自分にも
  当てはめて試しているんですが、今日は明らかに足音はバタンバタン
  と重い感じがします。
  調子がいい時は、シュッシュッシュッとアスファルトと靴底が擦れる
  ような音なので違います。
  特に走りの利き足である左がひどい感じでした。
  やっぱり当たっていて折り返し過ぎても調子がでません。
  ２ｋｍ前でストレッチして３００ｍ程歩いてみました。
  途中の歩きが改善に有効となることを知っているのでまた走りだすと
  変わってました。
  いい感じの足音になってます。
  このままフィニッシュできるかと思いましたが、左足がおかしいので
  右でリズムを取っていたためか、右足太もも内側につるまえの違和感が
  発生つるまでいくと痛みがのこるのでやめました。
  しかし、残り距離があるのでクールはキツイ風も冷たく少し歩いて
  再度ジョギングで体暖めながら変えることに。
  
* <2015-01-24 Sat 15:03>　R9.2 W1.5 ラスト
  今日も足音は重くてだめだと思いましたが、
  我慢していると折り返しから体が反応し
  スピードアップしました。
  ３００ｍ先にランナーがいるので彼を目標に
  再びあげていいきましたが、なかなか追いつきません。
  ５０ｍに近づいて、ラストで抜くためスパート
  しましたが、危ないめまい感がして、
  ジョグに落として、危険行動回避で終了しました。
  これがラストになるのかな。
* <2015-02-01 Sun 14:27>　R9.0　W1.0 隅田川テラス
  昨日の昼に引っ越ししてきて、荷解きすませて、
  さっそく隅田川テラスをテストランした。
  ヘドロの匂いもなく都会のビジネスビルや高層マンションを
  眺めながらの快適なランだった。
  と言いたいところだが、石畳あり、段差あり、モニュメント
  あり、極めつけが途中なんども橋による遮断だ、階段を登って
  一般道にでてもどってくるのが何回あったろうか、
  数えられない６回か７回か。
  越中島の相生橋を折り返しとして、両国橋まで戻って、
  フィニッシュ距離測でみると９ｋｍだった。
  足は１２だといっていたからショックだった。
* <2015-02-07 Sat 16:35> R6.4 W1.0 隅田川テラス上流
  今日は隅田川テラスを上流向かって走ってみた。
  上流は吾妻橋から墨田区役所横を通る。
  隅田川区役所横は信号待がある。
  テラスはオフロードもあるので雨上がりはきついが
  テラスの防波堤横は舗装状態もよくここを走るのが
  いいようだ。
  だが白鬚橋で遮断されたそのまま橋を渡って
  対岸のテラスを走る、対岸も防波堤横の道路が
  あってこちらを走るのが正解だろう。
  テラスを走って吾妻橋で遮断上に上がって
  ２度目の信号待ち、渡ってまたテラスにでる。
  石畳や段差が多い、それでも調子が出てきたので
  スピードを上げる。
  浅草橋でフィニッシュ。
  ８ｋｍくらいかと思ったが６.４ｋｍだった。
  ランナーはやたらと張り合ってくる馬鹿がいっぱいだ。

* <2015-02-17 Tue 20:23> とっつぁんぼーや
  小さなメーカの地方のはずれで働くとっちゃんぼーや
  が自分のことを「小職」となのってメールしてくるよ。
  たかだか主任だぜ。
  わらえるどころか鼻筋にしわよせてくさい汚物を見下ろすような
  気分になるぜ。
  たかだか主任だぜ。
  どれほど厚かましいやからなんだよ。こいつは。
  大企業っていうのはつくづくくだらないことばっかりやっているよ。
  メールで業務のやりとりできないんだと、誤発信恐怖があるからだ。
  社外秘、社外秘とメールくっつけて、たかだか知れている技術が
  極秘なんだらしい。
  個人情報、個人情報ともうすでに個人情報なんか漏れて漏れて
  闇の世界にひろがっているっていうもんだ。
  もうみうごきできないくなって自分でけつも拭けない大企業の
  端っこの端っこの主任が「小職」と名乗って俺らにメールしてくる。
  大企業病という非効率な組織体質をこの「小職」に付け加えたが
  厚かましくではなく「おろか」というのが当てはまっている。
  「おろか」なのだよ「小職」よ。
  おまえが属する組織もその端の端のお前も。
  「おれ」はお前らみたいなものと「決別」を宣言する。
  おまえらはいずれ世の中から消えていくだろう。
  お前らの大事な子供から引導を渡されてな。
  子供よ「小職」を超えて大きくなれ。
  子供よ「小職」を殴れ。
  こぶしが痛いなら木刀を使え。
  「小職」よ、おまえは子供に殴られてめざめよ。

** <2015-02-21 Sat 16:39> R7.0 W2.5
   今日も寒いので日向を走る。
   先週と同じコースで出発。
   体調が悪いと思っていたが、ストレッチに内蔵もみ
   を入れたのがよかったのか早い距離で速度を上げた。
   だが５ｋｍで100m前の女子が捕まらない。
   6km ジャストの白鬚橋追いつこうとするがめまい感
   がする。
   大事をとって歩きを入れた。
   白鬚橋は明治通りを渡していて、150mは迂回しないと
   明治通りを渡れない。
   交通量が少ないので、フェンスまたぎで渡った。
   めまい感は続くがジョグならと未知の都市高下をいく。
   ここにくると何故か上の車の音がうるさい。
   400mくらいから工事もしていてだめだと判断し、
   白鬚橋に戻る。
   白鬚橋を渡ると遠くに橋が見えるそこまできれいな
   ランニングの為のよく靴底をかんでくれる舗装の
   歩道が続く、ここを周回しているランナーもいる。
   あとで橋を調べたら、水神大橋だ。
   1.2km は稼げる。
   やっとこれで、両国からのランニングコースの完成だ。
   信号による遮断は2箇所、吾妻橋のうんこの前の交差点
   白鬚橋の西側の明治通りの交差点だ。
   まず、自宅から上流の厩橋へ向かって250m対岸の
   テラスに降りきって、480m ここらへんでウォーム終わり
   神田川河口で1.7km、吾妻橋まで登って、4.0km
   吾妻橋を渡りうんこの交差点を渡り、防波堤横を
   白鬚橋までで6.0km 、白鬚橋渡って交差点を渡って、
   水神大橋で7.3km で折り返し。
   白鬚橋で8.5km、ここからは２択だ。
   寒ければ、そのままテラス横の防波堤を進んで、
   X橋の桜橋まで9.7km、
   暑ければ白鬚橋を渡って、都市高の下を、桜橋まで
   9.8km、ラストスパートは、そのまま防波堤横を
   日本で一番デカそうな墨田区役所手前まで10.8kmで
   フィニッシュとなる。
   水神大橋は地図でみるとまともに行けるかまだわからないけど
   これが両国ランニングコースのベストだろう。
   なんといっても階段登りが一切発生しません。
   buildup もかけれて最後は心拍最大でフィニッシュできそうだ。

   

* <2015-02-21 Sat 16:35> R8.3 W1.0 隅田川テラス上流  
  今日は２度目の下流に向かおうと思っていたが、１１時
  開始では、テラスは都市高速の影になる。
  風もあって寒いので対岸のテラス向かうことにする。
  300m上流に厩橋（うまやばし）という小さな橋がある。
  そこまで登って対岸に渡る、対岸のテラスは日差しに
  あふれて堤防が風よけの役目もしているのでグッド。
  おそらく橋で遮断されなずに走れる距離ではここが一番
  長い1.6kmくらいありそうだ。
  東側の都市高下のテラスも同じくらいの距離なので
  夏に影がうまく出来るなら、周回コースとしてもよさそうだ。
  今日も周回を考えて下流に向かう、800mほどで神田川から
  の流れこみが走りを邪魔される。
  両国橋の下流に向かうには神田川と両国橋の交差点を渡る
  必要がある。
  諦めて上流に向かうが観光客でにぎあう吾妻橋で遮断される。
  雷門通りを支えている吾妻橋は水上バスが停泊しているので
  観光客の流れに押されて歩くしかなくなる。
  雷門通りの交差点を渡って、テラスには降りずに防波堤
  横を走ってみることに、ああ、オフロードだ。
  段差があるし、嫌なのでまたテラスに降りる。
  ここからは人化が急になくなり、テラスの住民が多くなる。
  石畳も増え段差も多くここは避けるべきだと気づくが、
  前回は下流に向かったが、上流の景色をみたいので、
  白鬚橋まで登ってみたが、もうここは走らんほうがいいと思う。
  白鬚橋から防波堤横を走る。
  狭いがランナーしかいないので楽に走れる。
  内蔵もすっきりしてきて5分台に上げる。
  浅草の雷門通りはさけたいと思っていたところに、
  H型の橋を発見。
  この橋を渡って東側の防波堤横を走る。順調に走るが
  物足りなさを感じて吾妻橋でフィニッシュ。
  なかなか組み立てられないが天候や季節でいろいろ対応が
  楽しめそうだ。
* <2015-02-22 Sun 18:42>
  昨日からwimax2 にしました。
  wimax1 は両国のマンションで入りが悪くて、困っていたところ
  dti から２週間前に電話があってwimax2のほうが安いらしい。
  というのでwimax2に切り替えたんですけど、
  やっぱりwimax 2も入りが悪い。
  高いマンションが立ち並ぶ街の３Fなんでと思っていろいろ
  場所探して、カーテンレールにハンガー針金で100の箱吊り下げて
  中にいれたら、いつも7Mほどだったのが15Mまで下ってます。
  やったー快適快適どっかのメーカのLANよりはえーぜー。
  wimax1のaterm 捨てていいそうだ。
  もったいないね。
* <2015-03-01 Sun 22:42>
 隅田川に注ぐドブ川の鉄筋を拾った話をしたがそれは嘘だ。
 そんな面倒なことなんかしなくてよい。
 「小職」は
  
* <2015-03-05 Thu 21:53> R0.0 走れなかったことのつけ
  先週の土曜日はランニング日和だったが、ひどい二日酔いになって
  いて、朝早くにめざめるも、二度寝で１１時を超えていた。
  病院に行く日だったので紹介状を片手に動愛病院にいった。
  紹介状を渡して内科に行くと、薬をもらうだけなら、
  近くの開業医に行ったほうがよいと言われるが、もう薬が
  ないからと診療を受けることにした。
  呼ばれると、女医が待っており、同じく開業医を探せという
  薬も２週刊しかだせない。
  紹介状も返せないからここで書いて渡すという。
  両国内科が見つからない。
  相撲の街だから形成外科のリハビリ施設が多い。
  それはいまのところどうにか間に合っている。
  しかし思った。
  毎月毎月血圧のミカルディスと尿酸の薬と中性脂肪の薬と
  睡眠薬はゾルビデム５mmとグットミン、最近は眠剤は酒に変わって
  中性脂肪を増大しているのでたっぷり余っている。
  がしかし思った。
  ミカルディスのまなきゃだめなのか。
  診療費と薬代はゆうにに５０００円は超えるんだ。
  この生活はそういえばランニング生活より長いぞ。
  恥ずかしいから書かなかったかもしれないが、中性脂肪が
  １０００から下がらないんだ。
  ２回連続でだめだからのめといわれてのんでいる。
  一錠でたりないので２錠のんでいる
  しかし、トイレに行くたび石鹸で手を洗っているんだが、
  一向に指の油が少なくならない感じがする。
  パソコンに後がつくのが心苦しい。
  会社のだから。マックにはつかない。いいつくりだ。
  2010年にかっていまだに大きなデザインの変更もないし。
  雪豹は今のよせみてより完成されていると思うよ。
  だってジョブスの最後のOSだろう。ちがったっけかな。
  それはよしとして。今日酒を断酒して日、月、火（ビールコップいっぱい）
  水、今日の５日間飲んでないんだよ。
  調子はいいのではないかとおもうのだが今日飯食って帰ったら
  くらくら感が少しあって不安を煽ってくる。
  今は１０：３０、９：００にはゾルヒデム５ｍとグットミン２錠のんだ。
  だからもう回って酒を飲んだ走りくらいにはなっている。
  目の上のダウさギョロギョロ感は心地よさへと変わっている。
  だからこの調子で行けば改善して行けばランニングも平均の向こう側へと
  いけるのではないか。
  ついに自己記録に挑戦できるんじゃないかと意気込んでいる。
  しかし今日なんかいやな立ちくらみを感じて薬は薬と思ってしまう。
  かもしれない。
  以前マイスリーと酒の組み合わせでラリりが半端ないというのを先生に
  つたえたからこの薬になっているだが、昼間に眠気とボートする疲労感がでる。
  薬はよくないだろう。
  なんとかいい方法を探ればいいが、もしだめなら、薬やめて、眠剤が
  ほんとに必要な方法を探してみようとも思う。
  それとは別だが、昨年６月に老眼のレンズを採用した。
  それが調子が悪い、スマホが見えにくり、遠くが見えない。
  視野がせまし。疲れる。やめたい。
  超近眼から始まって良くなるかと思っていた遠視への以降は交わり相互に
  いい感じで治ると思っていたが近視と遠視は同時に住み分けられ。
  苦しみは２つになるっとしった時は絶望だった。
  酒をやめたので新しい内科はいきなり血液を採取してから始めよう。

* <2015-03-07 Sat 21:01> R11.0 W1.0 隅田川初の11キロ
   前々回に作ったコースの初試走のつもりでスタートしたが
   小雨がひどくなる気がした。
   だから厩橋までで浅草側に渡るところそのまま
   テラスを引き返して両国橋で折り返すというコースに変更した。
   都市高が傘の役目をしてくれると思ったからだ。
   ここのテラスは住民がテントはっているから雨に当たる可能性が
   低いことがわかる。
   みんな賢く良いポジションを確保している。
   私は昨日浅草で飲み会だった。おでん屋から
   ２軒目でハイボールを3杯のんだのがボディブローになっいた。
   ウィスキーの香りが残っている。
   両国側のテラスと浅草側のテラスの距離だが浅草側は大きくカーブ

   しているので距離は長くとれていると思う。
   こちらは神田川に邪魔されないので８００ほど長いようにも思う。
   これで吾妻橋までテラスを走る、最後はジグザクにスロープを上がる、
   でその前に背の高い毛唐にかなりのさで勢いで抜かされた。
   この毛唐は覚えている一番最初の自転車での調査の時に
   抜いていったやつだが、かないいいアグレッシブな走りを
   していると思う。私は吾妻橋を渡らずそのまま交差点の
   信号をまって白髭橋に向かうコースを選んだ。
   毛唐は吾妻橋を渡ってどこかに消えた。
   私は隅田川区役所横から隅田川テラス横の防波堤を
   走る。ここにくると人が極端に減ってくる。
   不安をなんどもよぎらせてくれる嫌なコースの一部だ。
   今回はこの不安に少し戦ってみようと思う。
   不安はくらくら感なんかとして上がってくる、要は不安
   の神経は最大限の予防措置である、心筋梗塞や脳梗塞といった
   不安を象徴する病気を自分では制御不可能な精神の力のみで
   再生するのだ。
   そいう不安の中にいるとまたあの毛唐に抜かれることになった。
   こいつにぬかれるのは今日２回目だ。別になんとも思わない。
   私の目標は最後まで計画にどおりに勝つことがランニングの
   醍醐味である心拍数最大に持って行き達成感爽快感の
   脳内モルヒネを得らることだからだ。
   なんども不安がよぎりながらもbuild up していく。
   白鬚橋に達し対岸の信号を待つこれからが大水神橋まで
   が未体験コースだ他のコースとは違いテラスはあるが
   散策用で土手の上を走るという荒川と同じタイプだ。
   ここが好きなランナーは結構いる、やはり防波堤に
   囲まれたところを走るのは私も不安を助長するので、
   すきな人は少ないのだろう。
   大水神川まではひとつ橋を渡って見事に遮断された
   欄干で終わるのでここで折り返して大丈夫だ。
   ここのルートは開放感と風を感じる。
   もう少し行く方法もありそうだけど、またいずれ紹介しよう。
   折り返すと追い風で快調に信号まで戻る。
   浅草がわの塀に囲まれたところを走る。
   なかなか嫌なコースだが我慢できる。
   桜橋までいって疲れきっていたが、
   渡って最後の力を絞る。
   失速はしたが墨田区役所前の少し幅に余裕があるとこで
   フィニッシュ。今日は雨だから散策の人はすくなかった。
   最初の１１ｋｍはまあまあ成功だったと思う。
   ただここからークールをうまくやるにはテラスに降りて
   器具（フェンスや椅子を使って）ストレッチして帰るのが

  
* <2015-03-11 Wed 21:15>　東京は飯がまずい
  東京の食い物屋の味覚がおかしい。
  

* <2015-03-14 Sat 23:02>　R13.5 W1.0
  今日は朝飯にグリーンカレーの赤いの食って胸焼けしてしまった。
  だから昼飯とらないでそのままランニングにでました。
  先週と同じコースと思ったけど、薄曇りで若干日差しがあるので
  西側のテラスを走ることにした。
  一旦厩橋を渡って神田川まで河口。そこから吾妻橋まで一直線上がって、
  うんこの信号を渡って白鬚橋まで６ｋｍ白鬚を渡って信号水神大橋で折り返し
  と思っていたら、あれ、下通れるじゃん。
  そこを通ると左に隅田川が折れてテラスの最後を思わせてフェンス
  それ以上とおられないようになってました。
  2.5キロ11キロなので１３．５キロになりましたね。
  おそらく隅田川の西側ここが最後でしょう。看板は南千住がでてます。
  もう荒川区でしょう。
  隅田川はもう桜が開くようで自治体がテント立てて夜店なんかだすのかな。
  かんじんのランニングはちょっとさいごは疲れちゃって燃焼しないまま
  終わりました。









* <2015-03-22 Sun 11:24> R7.0 W2.0　半袖

  今日はもう半袖で走っても大丈夫だ。
  隅田川テラスの両国川は６月まで工事が入ってはれません。
  このコースのよいところは両サイドに照らすがあるため
  ホットスタンバイとなってランニングには支障がでません。
  全コースがホットスタンバイではないのですがなんとか
  なりそうです。
  引っ越して最初だけ両国から下流に行きましたがもういってません。
  もう不要です。
  といっても気分転換ではしるかもしれませんが。
  ただ、今日は一挙に気温が上がったせいか、いつにまして内蔵から
  の苦しい痛みがとれず、６ｋｍの白鬚橋からリターンして
  苦しみのままフィニッシュにもっていっておしまいとしました。

  
* <2015-03-28 Sat 12:00> R10.0 W2.0 花見
  先週は土曜日に走れず、しかたなく日曜日に走って、失敗。
  なぜ土曜日のいい時間に走れないかというと、
  朝飯の取り方がヘビーなものでないけど残って走る機会を
  失うことが原因となっています。
  だから今日は食べないまま9時開始。
  11kmか13.5km迷ったが11kmの折り返し地点水上大橋で
  返したあと辛い状態だったですが、build upして、
  桜橋手前でフィニッシュ。本来は後１ｋｍ走るけど、花見
  の散策が多くて走れません。
  とても心拍数最大でフィニッシュなどできませんから、
  手前で諦めました。
  実は今月に入って休肝日をかなり総１５日も入ってます。
  昨日も休肝しました。
  だから走りはそれなりに良かったのですが、期待には
  はるか遠い感じです。
  もしかすると経年は思った以上につまりは練習量を追い越して
  老いぼれが勝ってきたのではないかと思うのです。
  会社が近いので、中日の夜ランをしてもいいかと思っています。
  これもひとつの理由ですが、ランチのヘビー度がかなりきつい
  福岡にいる時の3割はカロリーアップしているでしょう。
  それでも体重68kgで維持できているので基礎代謝と通勤60分で
  なんとかできていそうですが、このままだと、均衡が崩れそうです。
  先週木曜日の朝の体重が70kgに達していたからです。
  下腹の皮下脂肪は相変わらずしがみつかれているので、
  これも何とかしたいんですね。
  ところで、先々週小型船舶の更新手続きしてきたのですが、
  書留郵便が代払いなので本所郵便局まで行きました。
  錦糸町の向こうまで遠い。
  福岡では総武線の平井という駅の近くのマンションを探したので
  ついでに行ってみることに。
  荒川の支流の川がランニング可能と調べたのでどんなか見てきました。
  ところどころクレーになっていてゆるく湾曲しているが隅田川よりは
  綺麗です。ボラの４，５０ｃｍがいるので下流は東京湾に水門なしで
  通じているのかもしれません。ただ、到底１０ｋｍは稼げそうにないし
  周回もむづかしいかもしれない。東京湾の方にはいかなかったので
  わからない。それで１年半ぶりに荒川に出てきた。
  この荒川コースはやっぱり夏は暑さで厳しいだろう。
  隅田川の都市高下を利用して夏を乗り切るしかないだろう。
  
* <2015-04-04 Sat 22:28> R16.5 W2.0 フルマラソンチャレンジするか
  Line Play をはじめてもう一年半になります。
  北海道のフレが第一回オホーツクマラソンがあるから私もはしらないかと
  軽い誘いがありました。
  パンフをみると海岸や湖岸がメインの折り返しのないコースです。
  東京マラソンや福岡マラソンにはまったく興味がなかったけれど、
  このコースは気になりました。
  断面図は、５キロから８０ｍ上りその後４０ｍを数度アップダウンし、
  １５キロにかけて８０ｍ下り海抜にもどる。
  それから２０ｍまでのアップダウンを繰り返しを描いています。
  非常に厳しいコースでしょう山風か海風どちらでも影響の大きさを想像できそうです。
  しかも私は２３ｋｍまでしか走ってません。
  かなり厳しいものになります。
  オホーツクマラソンを気にかけながら９時過ぎからランニング開始、
  雨が降ってます。
  しかたないので都市高速下を走ることに厩橋は工事中だから両国インターしたまでの
  １ｋｍを周回することにしました。
  ２回往復し終わると雨は上がってきました。
  そこで今の自分はどのくらいか調べてみることに今４ｋｍだから１３．５キロ
  コースを走れば、隅田川の花見ポイントを外しても１６.5キロです。
  このくらい走ると今の実力はわかるでしょう。
  金曜日は酒禁止にしているせいかいつもよりは調子がいいから大腿部
  やふくらはぎは疲労感はきついが６分でいけました。
  ラスト１ｋｍはもう少し上げれるはずでしたが、だめでした。
  今の状態でフルは完走は無理でしょう。
  完走とは走り続けるということですから６時間以内に歩いて完走というのは
  ないです。
  全コース走って、５時間以内で完走です。
  この目標を達成するには、週一ランを２０ｋｍにする。
  大会前３週間前までに３０ｋｍを１８０ー２００分で走る。
  それを２回。
  これができたら完走できるでしょう。
  ９・２７で北海道としては２０度行かないので気候は最高ですが、
  通年なら東京では、残暑が厳しく、いつもなら３ｋｍしか走れない日もあるので
  かなり月間距離数は減るから早朝ランニングになるでしょう。前日からの準備が必要。
  ３０ｋｍは給水も考えないといけないからうまいコース設定が必要でしょう。
  まだどうするか決めていないけど、ここのところの目標感のなさと
  経年に押される逆境をだっするにはいい転機かもしれません。

* <2015-04-12 Sun 15:05> R10.0 W2.0 葉桜
  昨日は、ランニングも洗濯もする気がなくてなんもせず、
  ディスカバリーチャンネルと溜っていた映画見て、ぐれていた。
  酒を日月火水と控えて、木曜日と土曜日は飲んでもいい日とした。
  それは書いていなかったけど、昨日は飲んだので、今日のランニングは
  調子がでなかった。
  それでも酒がすくないので入り（３ｋｍまで）は調子がいい。
  が、４ｋｍ過ぎから左横腹が痛くなった。
  この横腹の痛みは胃の痛みだとわかっていたので途中の水飲み場で胃に
  水を入れてみた。
  すぐには効果はでなかったがしばらくして痛みを忘れた。
  しかし上げられない。体は5kmで反応するが乗って行かない。
  市役所からすこし上流の隅田川土手の桜は葉桜になって、
  自治会のテントも片付けが入っていた。
  それだからここがゴールにはできないので手前の桜橋がゴールになった。
  今日も半袖で十分の晴天で気温も最高だったのにおかしい。
  まだ、フルマラソンは迷っている。
  ３月は51.5km走っているから距離は伸びているけど今後は暑さに
  削られるから難しい。
  かといって何も目標もなしにやるのもつまらない。
  
* <2015-04-19 Sun 09:58>　R10.0 W2.0 ハンガーノック
  今日は病院で血抜きだから朝飯食わず病院いって帰っても
  飯食わず、うとうとしていたら昼過ぎて、ここで飯くうと
  今日は走れなくなるのでそのまま走りに行ったら、
  やけに苦しい。
  それでも我慢して６ｋｍの白鬚橋まで来て、
  ついでにいつもの水神大橋までいった。
  対岸にテラスがあるので、渡ってみたその橋、
  すいじんおうはしということがわかった。
  みなかみとおもいこんでいてもうしわけなかった。
  でも渡ってもテラスは途中工事中らいい。
  それでもなんか左足の股関節がおかしい。
  ずーっと右足の股関節の痛みと同じもんがある。
  ストレッチしても取れない。
  どうやっても取れないが、走っていて痛みがあるわけじゃない。
  だから戻ることにしたが海風がくるしい。
  すいじんおおはしとしらひげばしの間はかなり整備された。
  市民へのコース真ん中に黒い1.5mほどの帯がある。
  ここってクッションがいい。
  それを本能でわかるランナーは好んでこの帯を走る。
  わたしもそうである。
  しかし、なぜ気になるのか。
  わたしのシューズはアシックスのゲルニンバス。
  それ買ったの2012/10だったのアシックスのカード
  をなにげに見ていて気づいたんのが昨日かな。
  月間40kmとしても２年半で1200km。
  靴底をみた。
  やばそうなくらいかかとの外が減っている。
  わたしの足は百姓の足だから慣れているが、
  それでもこれほどか。
  ゲルニンバスはクッションがいいからと選んだもんだ。
  ここのところというか東京に来て、キロ数は少し上げたんで、
  翌日の筋肉痛もなっとくしていたけど、
  それだけじゃないような気がする。
  筋肉痛がひどい。
  経年と複合して因が定かでないが、シューズの影響も
  ありそうだ。
  ゲルニンバスは15000円くらいしたけど、
  2年半使えばもういいでしょう。
  買い換えよう。
  あとかかとの内側はもったいないぐらい無傷だ。
  足の平は全面に削れている。
  蹴っている。
  体幹なら浮かすだけなのでこんなに削れるのも変だ。
  フォームがおかしくなっているのかも。
  骨盤の傾斜がだめかも。
  ああ。初心にもどろう。
  クール中にそう思っていながら両国の問屋街のいや下町の
  職人の街のいや商業の街のウインドウーに映る自分の姿は
  ほとんどアスリートだ。
  だが腰が沈んでいる。
  ランで出会うランナーのフォームを心で批判していたが、
  自分もそうなっているかもしれない。
  とナルシストになっているとなんか変。
  腹減ったー。
  これハンガーノックだ。
  やったー。

* <2015-04-25 Sat 10:08>　奥多摩の御嶽山ハイキング
今日は久しぶりトレッキングネタ書けました。
目的地は奥多摩の御嶽山です。
両国マンションを7:30に後にし、
いつもの通勤コースの国技館前を通って
いつものように総武線各停に乗る。
土曜日なので乗客は半分以下の少なさ、
もっと少ないと思ったけど、
いつも御茶ノ水で降りるが、
今日は降りたホームの向側に来る快速の三鷹行きに乗り換える。
新宿まで四ツ谷停車して9時に着いた。
ホリデー快速おくたま5号は7番線。
トイレ探して7番線に上がってしばらくすると電車が来た。
前から4両があきがわ5号となる。
電車がホームに入って来たから数えたら丁度後ろ6両内
だからラッキーと思って余裕がある席を選り好みして
落ち着いたらホームに入ってきた方にでるので逆だー（≧∇≦）
乗ってはいけないあきがわ5号に乗ってました。(ﾟoﾟ;;
9:19分に出発だからもう間に合わないよ♪(´ε｀ )
9:36御嶽駅着いた(*^◯^*)
人が多いよ♪(´ε｀ )
バスも人が並んでいて前から4人目できられた(*^◯^*)
バスもケーブルカーもスイカ使えるけどチャージはしといたがいいね*\(^o^)/*
で6分で着いた。
トイレして、おやきかって出発(10:40)
御嶽神社までの参道の周りにはお土産店や
蕎麦屋が数件あって宿も沢山あるみたい。
興味はないのでスルーすると
御嶽神社に参拝させるように案内があり、
道がわからんから神社までのかなり急な階段の横にルート発見。
しばらく行くと登山コースの分岐点がある。
七代の滝0.6の指す道を行く事にした。
ところがこの道急な下りばかり続くかなりの難所です。
それでも我慢して降りると滝の音が聞こえ出した。
小さな滝のが落ちていてまあまあ憩えるかな。
ここでおやきを食べて昼食休憩だ。
その後は滝の横から手摺の付いた鉄階段登りだ。
一挙に登って天狗岩に着く。
鎖場があって天狗岩は登れるらしい。
危険なことわしないで沢沿いのコースを行く。
道は整備されて沢を渡る岩が組んである流れは
30cm位で綺麗な多摩川の源流の水が流れている。
大雨なら渡ることはできないだろう。
森の中の沢沿いの道は気持ちがいい。
倒木に生えた苔は原生林を彷彿とする。
しばらくいくとまた滝がある。
脇のみちを登って行くと休憩所がある、
その横が大岳と御嶽神社への別れ道予定通り下山する。
御嶽神社までは2キロはあるけど楽な林道だから問題無く到着。
たた、途中の看板には去年の11月にツキノワグマが二頭目撃されたとかいてました。
近場てこれだけ自然を満喫できれば大満足でしたが、帰りの電車は人がいっぱい。
フライフィッシングに来るのはいいかも。
結局山歩きは３時間３０分で事前の調べとおんなじだった。

* <2015-05-01 Fri 14:04> R6.0 W3.0 新しいシューズ
 アシックスのゲルカヤノ21。
 銀座のアシックスで３D測定して
 ランニングマシンで着地の写真もとってもらって、
 買ったのがこれです。
 先週前のアシックスゲルニンバスのかかと外がすり減ってしまっていたの
 を気付かず使い続け、アシックスカードを調べれば２年半前の購入だった。
 それで慌てて買いに行ったのですが、クッション性が
 よいので即決。
 今日が卸でした。
 だが、右足だけフィッティングがよくない。
 靴紐をなんどもゆるめたりしたが、足の甲にあたり感が
 あって疲れる。
 左足は問題ない。
 それでやる気が無くなって、６ｋｍで終わり。
 先週はトレッキングして筋肉痛になったので
 ランニングはしていないから足の異常も疑いが残る。

* <2015-05-05 Tue 14:04> R3.0 W3.0 新しいシューズ 
  シューズの紐をかなりゆるゆるにした。
  目で見て差がわかるほどだが、甲のあたり感が弱くなったものの残る。
  実はこの日は、タビオの糞靴下を履いてしまっていた。
  実家に戻る際、荷物に放り込んだのがこれだった。
  この靴下は、締め付けがひどいので足の裏の血流が
  滞って、ランニングをじゃまするためのものなんだが、
  １５００円する生地は丈夫で、デザインもカラフルで、
  捨てようとしてももったいないからおいていたんだけど。
  もうこういう輩のものは捨てた方がいいが捨ててしますと
  無になるのでおいておくことにする。
  マジックでバツ印かいてね。

* <2015-05-16 Sat 22:49> R10.0 R2.0 イエス様は私の力です。
  4/26はトレッキング明けで筋肉痛だったからランニングしないで
  銀座のアシックスで３D計測してランニングしてかかとの傾きを
  チェックして、ゲルカヤノ２１のニューカラーを買った。
  それからおろして今日が３走目の日。
  右足のフィッティングが相変わらずおかしい。
  隅田川テラスは4/19 以来だった。
  右足の甲にあたり感があっておかしいのは確かだ。
  走りながら思い出した。
  以前この経験があった。
  痛風だ。
  東京に出てきて昼飯がかなりハードでプリン体も
  多くなっているからそのつけがでているんだ。
  割り切ることにした。
  もう気にしないでいこう。
  そう決めてアップが終わって３ｋｍ過ぎからあげようと
  してもだめだ。
  ６分半で苦しい。６分までも行けない。
  だが、ここでやめると負のサイクルを断ち切れない
  のでいつものコースのコンピリートを目指す。
  水神大橋の折り返しから時折build up を試みるほど
  回復するが続かない。
  ボロボロになってフィニッシュ。
  １０ｋｍ走って、膝からしたの疲労感が前の靴の時と
  違って全然でない。
  もう少し走れば靴紐の位置も馴染んでいくだろう。
  
* [2015-05-23 Sat 20:59] R10.0 W2.0 

  夕方スタート。
  やっぱり右足の甲にあたり感があっておかしい。
  はしりながら思い出した。
  これ震災前に浦安にいた時と同じ症状だ。
  あの時は形成外科にいって痛風じゃないかと言われた。
  電気治療もやってそういう結果だった。
  それだ。
  ということで気にしないで走ることにした。
  ところがきつい。
  なんどかやめようと思ったが、走りきった。
  最後だけ少し上げて終わり。

 * <2015-05-24 Sun 21:05> R10.0 W2.0 新シューズの効果

   昨日走ったにもかかわらず、筋肉痛にならない。
   あたらしいシューズのおかげだ。
   前のシューズは使いすぎだった。
   こんなにシューズの違いが出るとはと思って、
   ２日連続で走りだした。
   ２日目は快調。
   途中失速はしたものの最後までbuild up できた。
   アシックスに感謝だ。
   疑って申し訳なかった。

 * <2015-05-28 Thu 22:13>　気に食わない奴らのひとつ目、民放のアナウンサー。
   朝からこいつらの面をみるのが嫌なんですよ。
   だから地上は見ないようにしている。
   ただ、目を覚まさせるにはTVをつけているのがいいので
   なんかつけている。
   何かの間違いで朝のワイドがついて、こいつらの面が眼に入るのは
   気分がわるい。
   だからといって、NHKをみるきもしない。
   朝から人が殺されたとかを面白がって、素材にして、
   きもちの悪いアナウサーとコメンテーターなんかのしたり顔を写して
   視聴者は見続けるのかな。
   気に食わない奴らと書いたが、もっと辛辣な言葉でも良い。
   面を見ただけでどうしてこんなに嫌な気分になるのか。
   自分でもよくわからない。
   だから少し考えてみよう。
   ひとつ、俺は優等生が嫌いだ。
   ひとつ、調子のいいやつが嫌いだ。
   ひとつ、正義を気取るやつには反吐が出る。
   ひとつ、俺は巨人が嫌いだ。
   ひとつ、俺は読売と名のつくやからが嫌いだ。
   ひとつ、俺は徳光とかそのあたりから若いやつらへの継承にはうんざりしている。
   ひとつ、CIAが嫌いだ。
   ひとつ、警察官が嫌いだ。
   ひとつ、政府が嫌いだ。
   ひとつ、杓子定規な奴が嫌いだ。
   ひとつ、野球中継で姓名をサウンドの気持ちよさで呼ぶアナウサーが嫌いだ。
   ひとつ、西武戦で中村は二人いるが気にせず中村とよぶアナウサーが嫌いだ。
   ひとつ、えこひいきする奴が嫌いだ。
   ひとつ、陳腐な奴が嫌いだ。
   ひとつ、軽い奴が嫌いだ。
   ひとつ、長島が嫌いだ。
   ひとつ、とその息子も嫌いだ、K1のビデオにその名前はピーっという音で隠してもらいたい。
   
   まだまだ自分の底にある嫌気で沈没した船は引き上げられないが
   いずれまたトライしてみよう。

* <2015-05-30 Sun 08:50> W9.0 男体山 7:30
  このところトレッキングネタがひと月に一度入っているが、
  これがそのまま続くことはないだろう。
  栃木県の男体山。
  去年の出張の時遠くに眺めていた雪を纏ったきれいな山だった。
  日帰りではかなり苦しい日程だと計画から思っていましたが、
  案の定の結果になりました。
  浅草から東武東上線が出ており、奥日光まで直通で行けます。
  当初は特急でのんびりと腰をかけて行くことにしていないのですが、
  それではどうも下山しきれず、宿をとるか、キャンプすることに
  なりそうだったので、6:00の始発で出発することに、
  幸い両国からは１ｋｍ位だからあるていけます。
  ６：２０始発、席は余裕だったが北千住で埋まってしまう。
  ８：２５東武日光駅到着（少し遅れていた）
  駅厩舎をでると真前がバスの場すでに人の列ができているが
  臨時がでているので待っていると２台目に乗車座れてよし。
  いろは坂をくねくね登って
  ９：３０二荒神社前到着
  所要をすませて、神社で５００円の入山料を払う。
  お守りをもらうがすぐにどこかに捨ててしまう。
  １０：００登山開始
  １１：００４合目
  １１：５０６合目このあたりでもたつく
  １３：１２７合目
  １３：２４８合目
  １４：００９合目
  １４；３０登頂
  １５：１０下山
  １７：００５合目
  １７：４４４合目
  １８：３０神社

  ７時間半かかった。神社につくと水が出しっぱなしの洗い場で
  靴のドロを落として終わった。
  神社にはいると雨が落ちてきて、階段の石の上を湿らせてきた。
  この時間はバスはないと諦めていたが、なんと１８：４７分が
  あった。
  １０分前だった。
  それにのって東武日光につくと、なんと特急も連絡待ち５分だった。
  水を買うだけにしてのりこむ。
  特急きぬは快適１９：３０過ぎの日曜日車両中の乗客は連れを含んで
  ３人だ。
  しかになにか妙な揺れを感じたと思ったのもつかの間地震が発生。
  しばらく様子をみるとか行っている。
  東武動物園まで様子見の徐行運転だとか行っている。
  あきらめてここで一泊できるように水を調達する。
  しかしそれらは稀有となり３５分遅れだけですむ。
  今回は３６ｌのザックにテント、寝袋、パッド、水２ｌ、１．５日分の食料、
  を装備していたのでかなり重装備となっていて、１３ｋｇ以上となっていた。
  だから地震で車内泊で対応できたし、現地でキャンプも可能だったんだが。
  とにかく重すぎる。
  トレニングを兼ねてこうしたが、もういいという感じだ。
  ６０ｌのザックで登るなんてのは土台無理そうだ。
  しかし、７時間半、急坂を登り降りして山の難しさがわかってきた。

* <2015-06-06 Sat 14:17> R10.0 W2.0 隅田川の戦い
  いつもの隅田川テラスいつものように水上大橋までで折り返して
  おしまい。もうすでに初夏の苦しいたたかいとなっています。
  シューズを気にしないでいいので楽ですが、なかなか
  スピードに乗れない。
  水上橋の折り返しまで行って白鬚からのラストにかけて
  少しスピードを上げて終了。

* <2015-06-13 Sat 21:32> R7.0 W2.0 よるラン
  隅田川の高架下にでて厩橋にキロ7.5分で向かう。
  厩橋は人は少ないが歩道は狭い。
  乳母車は特に気おつけて抜いていく。
  風や空の調子を伺って、駒形川のアーチを降りるそれが
  いつもの隅田川テラス。
  都会の真中でもここはランナーは数えるしかいないから
  顔も覚えている人もいるくらいだ。
  まだスピードを挙げないようにして、様子を見る。
  海風があるので気持ちがいい。
  突き当りは、神田川の始まりになって、折り返しとなる。
  無風だ。東京に来てはじめての無風だ。
  この無風はおそらく水上橋９キロ弱まで続く。
  実は今は夕刻もうすぐ日が暮れる。
  ここまで遅くなったのは気温が下がらなかったから、
  とりあえず吾妻橋までいってみよう。
  吾妻橋を横切ってそのまま行けば木々があるから涼しいかも
  しれない。
  そうして桜橋を横にみて前方をみると工事中の看板が、
  近づくと９/30までらしい。
  これで一挙にやる気が落ちた。
  もうすでに歩きになった。
  これで終わりだ、X橋の桜橋を渡って不完全燃焼の気分
  がいやだと気持ちが上向く再び、白鬚橋を目指す。
  だが今日の暑さはここで限界、ここで折り返していつもの
  終点であまり燃焼できないフィニッシュとなった。
  すっかり日の落ちた隅田川には屋形船が何船もでていた。
  だがサイレンに築く、なんと水上にも緊急車両ならぬ
  緊急船があるんだな。

* <2015-06-14 Sun 21:32> ５H　新浦安へのサイクリング

  最近食生活の悪化というか完全にカロリーのとりすぎにより
  体重が３ｋｇ増加した。
  有酸素運動を長くやって消費したいと目論見。
  １１：３０にサイクリング開始。
  駒形通りを荒川に出たくて平井方面に向かう。
  ロードの連中に抜かれながら荒川に出てきた。
  不思議なもんだ、新浦安に住んでいた時は帰る道が今では
  逆になっている。
  とりあえず、急ぐ、風は海風だ。
  逆らわずにゆっくりと進む。ロードの連中に抜かれるのは
  腹が立つがしかたないので記憶がどうなっているか橋の形状を
  思い出していたが、案の定間違えた。
  そうだ。海側から２本目で荒川を渡らないと行けなかったんだ。
  先端で休憩者がいるので景色を見和わしてもこころに引っかかるもの
  はなく直ぐに引き返した。
  そうだ、ここを渡って、葛西臨海公園へと向かうんだ。
  臨海公園も通りすぎて、舞浜橋を渡るとそこは夢の国だ。
  なつかしい舞浜駅の裏の駐輪場で水を飲んで、
  以前のマンションのあった東野に向かう。
  あったあった、なにも変わらん。
  いや、あんなとこファミマなかった。
  まあいいOKストアを横見て、新浦安駅にむかおうとした。
  モナの５階の中華の麻婆豆腐セットがたべたかった。
  開いている駐輪に停めてモナに登ったが人いっぱい、
  入れないので、アトレのおむすび屋でおむすび買って
  総合公園で食べることにした。
  総合公園は震災で壊れてわたしがいるとき半分が治った。
  このブログにもなんども登場したランニングコース。
  懐かしさと心細さと不安が胸に去来したが押し殺して帰路につく。
  江戸川からとも思ったが、普通の道は遅くてだめだから。
  同じ道をもどることにした。
  上りは風が押してくれたので、少し踏んで帰ってきたのが
  １６：００だった。
  
* <2015-06-20 Sat 17:32> R14.0 W2.0  フルマラソンへの挑戦
  昨日も暑くて、体調も悪かったので、今日は朝８時開始。
  気持ちよくスタート。
  実はフルマラソンにエントリーしました。
  だから今日は少しのばそうと思っています。
  南千住までのコースにアップしました。
  気温は苦しくないけど、最近の食生活のせいで、
  体重が３ｋｇほど増えています。
  ６６ｋｇまで落とさないといけません。
  水上橋をくぐる前からランナーズハイになっていました。
  距離を稼ぎたいのであえて壊さないで走っていたら、
  水上の堤防の上りで自然に解消しました。
  まあそこからは普段通り上げて最後桜橋でフィニッシュ。
  めんどうなので１４ｋｍとしました。
  今後は土日の２回走って行こうと思っています。
  大会前に３０ｋｍ二本。
  大会用シューズにも手をだそうかと考えてます。

* <2015-06-28 Sun 17:32> R７.0 W2.0  フルマラソンへの挑戦  
  フルマラソン挑戦ということでエントリしたのが
  第一回オホーツク網走マラソンです。
  エントリーに８０００円。
  羽田ー女満別、宿泊がいくらになるのか、できれば
  安いがあればいいのだが。
  エントリーだけだからいろい調べてないといけない。
  まあ、直接関係ないのだが大会とその練習では時計が
  必要になってくる。
  いままでかったランニング専門（確かセイコーインスツルメンツ）
  のもので寒い季節では裏蓋の冷たさがきつくて、なんの
  人間工学なんて考えていないやつで、夕方走ってもライトも
  付いていないような、まぬけが作ったようなものを買っていたが。
  何よりも大会でラップを取りながらやっていて、ミスるんだよ。
  ２、３大会挑戦してどれもミスっててがっかりだ。
  だからこれは憎しみからハンマーでうっ叩いて捨てた。
  それでも大会の時には必要だ。
  いろいろ必要なものを絞ってくると、ダイバータイプとなった。
  ベゼルをあわせるだけで２時間のハーフのコースはスタートで
  合わせるだけできる。
  フルでも同じできるから面倒なラップ操作をする必要がないから
  楽だ。
  ということでGMT針、ベゼルがあれば良いということになる。
  GMT針は大きく中心にあったほうがいいがベゼルはハーフにも使うので。
  ２４時間でない方がよい。
  むしろダイバーの６０分のほうが良さそうだ。
  フルでは普通の時針と分針とベゼルでわかる。自分の走りは細かに
  アップダウンを繰り返すのでデジタル的に眺める必要はないから、
  これで十分です。
  ということでSEIKO SUPERIA のSSA057Jにして購入しました。
  ところがキャンセルとなってしまいました。
  数分前に住所が間違っていたのでキャンセルしたのが輻輳したようです。
  キャンセル確認して新しい住所にして再注文したのですがそれがキャンセルされています。
  もう一度購入しようとしても在庫がありません。
  状況を再度確認してもう一度やります。
  ということで時計まだ先になりましたが、
  今日は日曜日の夜スタートです。
  実は先週の月曜日から風邪を引いたらしく、医者にも行きました。
  ５日分の薬を飲んでも咳がとれません。
  ですので日曜夕方まで我慢してましたが
  結果は、さくら側の６キロで歩きました、きついので調整して再び
  ７キロで折り返し、帰路５分まで上げて、フィニッシュです。
  どうも肺に違和感があります。

 * <2015-06-30 Tue 20:44> R10.0 W2.0 すごい久々の朝４時

   昨日はノンアルコールディであったから、マイスリーを１０ｇ、
   レンドルミンを１錠を処方して寝た。
   ただ、やはりマイスリーはラリりの極みを見せる。
   またも、焼き飯を作って食ったらしい。
   なぜ、この第三か第四かの人格は、俺らしく、極めて俺らしい。
   明日への嫌味を残してくれるのか。
   嫌味は眠りを２時半で終わらせた。
   酒がないのでその起き方はただ薬的なというより健康的なものと
   勘違いする程、生命の寝起きを伴っていたから、しばらく休んで
   ランニングに出ようと思ったのだ。
   ただ、命の目覚めと心よい爽快な目覚めだと思ったからだ。
   ただ、こういう思い込みは常に平常にも行われていることなので
   これが特別ではない。
   だから、命から溢れて浴びる自身のよろこびとその景色と同調できる
   ランニングを開始するのだ。
   朝２時半からうとうとし、ランニングの結論を出すに１時間。
   それで目を覚まし、きわめて入念なストレッチをまだ開けぬ、
   カーテンに仕切られたその暗闇と蛍光灯に照らされた部屋で行う。
   体重を測る、焼き飯の重さを現実に分かった。
   なぜ、飯を食わせるのか。
   お前へのメッセージがランニングだ。
   ４時前開始だ。
   まだ暗い、だがライトを持っている。
   いつもの厩橋に行く、そして対岸の隅田川テラスを下る。
   神田川までそして折り返して吾妻橋までこれで４ｋｍ。
   そこで吾妻橋を渡って、朝日のうんこビルの横の勝海舟の
   きわめて惨めな、その像が見えてそのまま道なりに進む。
   隅田川公園が右手に広がるが土手の道は桜橋まで嫌な坂
   で、古びて黒くなった堤防に挟まれた道を自分の影をみて
   駆ける。
   そして白鬚橋に向かう。浮浪者のテントの並びに挟まれた
   黒びた堤防がくねる道を進む、上には都市高の高速があるから、
   時折トラックのけたたましい打撃音が炸裂する。
   その音は思いの外、下をいくものには苦にならない。
   ここまできて、半分の５ｋｍを終わっている。
   ずっとない軽い感覚だ。
   走れている。  
   そうして水上大橋の元を折り返して、この浮浪者の道
   に戻る。
   そして、最後３分ｋｍまで上げれた。
   清々しい。
   これが今朝の話。
   ランニングはこうなるべきだ。
   俺らしい嫌味な第何格の者と共生しているのだろう。
   極めてオモローだ。

* <2015-07-02 Thu 20:57>　本屋の憂鬱
         1         2         3         4         5         6
123456789012345678901234567890123456789012345678901234567890123
  
  御茶ノ水の三省堂書店は実にいい書店であ
  る。クラシックを流していること。本の並
  べ方に筋が通っていること。静かなこと。
  ただ、本自体がダメなことが残念。ここに
  並べられた本を見ていると読んでは損をす
  るようなものだらけだ。めくると字の空間
  がありすぎる中身の無い、興味だけで読者
  を呼んで、最初の３ページでその本題が尽
  きてしまう。そんな本だらけだ。読者にへ
  つらう本は価値がない。へつらいの証が文
  章の隙間だ。空間がその意味を持つ詩集な
  らよいが、普通の本にその必要はない。紙
  が白いことを忘れるくらい文字で埋めてこ
  いやー。この愚鈍の書籍群の中から真の本
  を選ぶにはどうしたものだろう。中学より
  慣れ浸しんだ方法を取るよりほかあるまい
  。それは古い本を探すことだ。新品の古い
  本の中にこそ風雪に耐えた言わばサバイバ
  ーがいるのだ。タイトルに凝縮され完結さ
  れた文字を読み取るのだ。かと言って純文
  学なら三島由紀夫しか読まないおいれには
  もうどうでもいいのですが。何かアイデア
  やヒントがほしいときは実用書をさがすだ
  ろうそのあたりにあるのは実にひどいもの
  がならんでいる。そこではこの方法が役に
  立つだろう。

* <2015-07-03 Fri 19:19> イングレス脳
  イングレス最近聞いたゲームの名前である
  。グーグルが提供しているオンラインゲー
  ムで実際の地物とバーチャルな世界と融合
  された世界で爆弾を仕掛けたり人と陣地を
  撮り合ったりその場所のモニュメントを投
  稿したりするものらしい。リアルな地物に
  は実際に歩いて行く必要がある。それにハ
  マったおじさんにがいた。

* <2015-07-04 Sat 09:21> 腕時計
  腕時計はしない主義というか腕にはめてい
  るだけで気になってしょうがない。いらい
  らして外してしまう。結婚指輪もすぐに外
  してしまう。だから別れたのかもしれない
  。そんなだからランニング用の時計もしな
  くなった。というか苛立ってぶっ壊した。
  トレッキングはじめて時計の必要に迫られ
  て３０００円で買った時計もぶっ壊した。
  そんな俺だが過去にロレックスを買ったこ
  とがある。さすがにロレックスは壊すこと
  はなかったがしなくなって机においていた
  ら忽然と消えた。そんな馬鹿なと思うが、
  事実だ。実家には箱だけがある。証拠は帰
  ればすぐに見せることができるから信じて
  ほしい。その消えたロレックスはGMTマス
  ター１だ。新宿のさくらやで２６万で買っ
  た。エクスプローラー１を買うつもりだっ
  たが回った店の店員がこれをしていて気が
  変わった。そこで一番安かったさくらやで
  速攻買いした。エクスプローラ１は高倉健
  が戦友と裏盤に釘で書いて出演者に贈る奴
  だ。シンプルでいいと惚れ込んでいたが、
  電車で前に座った袈裟着た坊主がしていた
  のもやめた理由だった、もうエクスプロー
  ラーには興味はない。俺のランニングに時
  計は不要だと随分前に書いたが大会となる
  と時計が必要になる。前回の男体山トレッ
  キングははじめての長丁場自分のペースと
  安全を考えながら帰りのバスの時刻に合わ
  せたりするのに必要だ。スマホを見ればと
  思うがポケットから取り出したり操作が体
  力ぎりの世界ではうざすぎる。というわけ
  で時計が必要になった。ランニングとトレ
  ッキングで使える時計がほしい。かつてラ
  ンニング用の時計はセイコーインスツルメ
  ンツのデジタルだった、過去のラップも数
  十本保存できるすぐれものだった。という
  か機能が豊富だった。だがこいつ冬にする
  と腕が冷たくて耐えられん体は熱くなるが
  手の付け根のくるぶしの付近は熱くならな
  いのだ。だからずうっと気になってしょう
  がない。結果この時計をぶち壊す理由がイ
  ンクリメントされ続け最後に爆発した。大
  会にでてラップを記録しても誤操作してい
  る、俺にはというか人間工学もなんにも考
  えていないこの時計への怒りもインクリメ
  ントされ続けていたのだった。
  俺のランニングには秒単位の正確性など必
  要がない。ラップを気にして走ってだれに
  もじゃまされない唯一無二の自由を失うこ
  となんかできない。
  以上のような状況と経験から考察した結果
  ロレックスのGMTマスター２が俺の時計だ
  と結論を出した。正確にはGMTマスター２
  のブラックベゼルだ、以前持っていたGMT
  マスタ１は赤青ベゼルをブラックベゼルに
  無料交換可能という謳い文句だったのだ。
  その時計を失う前に日本ロレックスに交換
  を連絡したところその受諾のハガキが来て
  いたのだ。この切なる悔しい思いがこめら
  れているのだ。だがGMTマスタ２は現在価
  格８０万くらいか。山で岩にあててぶっ壊
  れたら泣けない。そんなこんなでいろいろ
  探したらこいれに行き着いた。
  セイコースーペリアSSA057J
  http://item.rakuten.co.jp/auc-gallant/ssa057j1/?scid=af_pc_etc&sc2id=202756144
  正確にはSSA057J のステンレスベルトを
  変えてSSA053Jの布ベルトにすることだ。
  この極みの選択肢は俺を酔わせはててしま
  った。それで先週アマゾンで注文した。そ
  の後、数日思いを馳せて、配送状況を確認
  した。すると注文がありませんになります
  。あれれ。あれれ。かわいそうなおいれは
  。きづく、キャンセルされてしまったのね
  。とそこでショップに問い合わせると他で
  売れたらしく在庫がなくなったのでキャン
  セルしました。だそうだもんで、あれれ。
  ここから８日程たった。
  インターネットで探したが見つからない。
  検索のヒット率の下の方で見つけたサイト
  。なぜか在庫がたくさんある。問い合わせ
  ると在庫があるから購入に進んでください
  という。だが待てよ。すこし調べてみると
  このサイト代金振り込んでなしのつぶてを
  やってるらしい。あぶないあぶない。そこ
  で諦めた。日曜日ランニングもしてやるこ
  となくなったら思いついた、秋葉の免税店
  はどうだろう。さっそく行ってみた。ヨド
  バシだめだ。セイコー５はあるSSA055J1
  があるがヨドバシは高い。もうここで物川
  根。ソフマップだめ。他にも数件回ってな
  し。akky あったよ。しかも文字盤の白も
  黒もベゼル黒もあるよ。ベゼル黒は触手が
  伸びたがSSA057j1に決めた。37500円日
  本人だから消費税かかった。
  で翌日から仕事でどの位の性能のあるか試
  した。だが装着して歩くとすげー重い。ず
  しりと垂らした腕を重力が引っ張る。ラン
  ニングでもの試したが、ステンレスベルト
  はやっぱり駄目だ。予め調べておいた、SS
  A53J1のナイロンベルトを注文する。メー
  ル便で翌日に来たよ。封筒に入っているが
  重さを感じないほど軽い。これは期待でき
  る。だがよく見ると接着剤のし見た後がベ
  ルトの穴の横に付いている。なるほど、検
  品で落ちたやつだな。だがそれは気にしな
  い。ベルト換え用の工具をamazon で注文
  する。ベルトが５５００円、工具６００円
  工具はきちんとしたクッションに包まれた
  封筒に入ってきた。なんの苦もなくステン
  レスベルトを外して、ナイロンベルトに棒
  を差し込んで、ベルト交換完了。
  そしてこれがその勇姿だ。黒の文字盤とご
  っついシルバーのベゼルとナイロンが53と
  違う大人びた感じがいいとと思う。ただ、
  ナイロンベルト仕様を仕事につけていった
  ら午後には外してポケットにしまいこんだ
  。暑くてつけてられない。ということでト
  レッキングとランニング大会用の時計は苦
  闘の末手に入れた。

* <2015-07-04 Sat 20:23>　R7.0 W2.0 ギターの住人
  今日は年上の弟が泊まっていたので、朝ランニングできず、
  夕方スタート。マンションを出ると雨だ。
  しかたないので、コースを変更。
  両国インター・厩橋間の２ｋｍの折り返しコース走ることにした
  なんどか書いたがこの厩橋は３月から工事が入っていて６月末
  まで通れなかったので隅田川テラス入ってそこを目指す、
  厩橋をくぐると頭上の高架は右に緩やかに曲がるから雨よけには
  ならなかった。しかもオフだ。オフでもそうわるくないから
  靴の汚れは概して心配ない。で吾妻橋を見て折り返し、
  厩橋をくぐればずっと両国インター下まで雨を避けれる。
  このことを知っているランナーは多いと思うが数人しかいない。
  否ギターを抱えた住人がいた。程よく酔ったこの住人は、
  雨に悩まされず、その住居の前で私にギターを褒めて
  ほしいような笑みをもって訴えてくる。
  私は笑みを返して通り過ぎる。
  それを３回ほど繰り返して、きつくなった。風はない。
  自分で起こす風だけで走っていたが湿度が高い。
  ２往復もできず、最後１ｋｍを４分台にあげて川を渡る
  総武線を無理にゴールの帯にして終了。
  風がないから歩けば顔に焚き火があたる。
  １ｋｍのクールで足りず、またも厩橋まで行ってクールを
  終えた。

* <2015-07-12 Sun 02:39>
  墨田区トリフォニーホール。
  錦糸町の北口のロータリを出て西にいくとすぐにある。
  聞くところによるとサントリーホールと肩をならべる
  施設らしい、ここでマーラーの２番をやるらしいから
  と誘いをうけた、なんどかクラシックネタを書いたが
  音楽鑑賞はヘッドフォンで少しやっていた。
  しかし交響がうまくなってくれないので、もうしまい
  こんだままになってました。
  そんなところへの誘いだったからなおさら面白いと思ったんでした。
  開演は１９：１５その前にいっぱいやっていたらぎり
  になってしまった。

* <2015-07-12 Sun 12:22> R8.0 W1.0 自力の風
  一昨日から夏が到来した。
  今日も暑いので朝早くと思っていたが、
  ２時にまたも目が覚めてその後どうしたのか
  夢の中でもがいて８時過ぎていた。
  もう暑いから日陰の高架下コースの周回に決め
  何回周回するのか考えながら走って１往復して
  ５ｋｍ、三味線の練習する女子、
  うん下手っぽい。
  後１往復して、もう一度下手な三味線を聞くのが
  苦痛になって８ｋｍでフィニッシュラスト２ｋｍは
  ５分前半まで上げたが、ダメだった。
  まったくの無風だから上りも下りも自力の細い風
  だけだった。

* <2015-07-13 Mon 20:51>　イングレス脳
  イングレスとはグーグル製のオンラインゲームだ。
  それをやり続けることで弊害を受けた脳がイングレス脳だ。
  とこの造語をはじめて作ったと思い込んでいたら。
  イングレス脳でヒットする。
  別にどうでもいいから話題にしないが。
  このゲームの弊害

* <2015-07-14 Tue 20:49> R3.5 W1.0
  昨日は、ツール・ド・フランスも野球もないから早く
  ねたもんで、朝またもはやく起きた。
  それで６時位から走りに出た、５ｋｍの予定だったけんども
  トイレに行きたくなって、厩橋の西側のトイレでうんこ
  したら、昨日のレバニラ炒めのニラがでて回虫みたい
  だったね。
  俺は健康なんかな。
  そのトイレをでたら隅田川テラスへのスロープが広がる。
  で、神田川の始流を目指す、しかしこっち側は暑い。
  とにかく暑い。
  で、思ったね。東京市根。
  で、面倒になったから３．５ｋｍでやめて、
  かえってシャワー浴びてたら洗濯が必要だ。
  洗濯の代償をはらうんだったら、もっとまじめに
  走りなさい。

* <2015-07-19 Sun 20:49> R2.0 W1.0  
  
  夕方６時、もやっとする蒸し暑さの中いつものコースへ
  と出発する。いつものようにマンション入り口の植え込み
  のコンクリートブロックの端っこに両手を添えて、
  大股を開いて、腰の傾斜へのストレッチをしてみる。
  ほんとはもっとやりたいが、ここは通りなので適当に
  終わる、そして走る隅田川へ。
  ウォームアップだから７分半で５００ｍは行かなければならない。
  厩橋を渡ってトイレがあってそこから隅田川テラスへの
  スロープを降りる。
  あれ金網がしてある。張り紙を見ると7/24,7/25 は
  隅田川花火大会なのでテラスには降りれませんとある。
  なるほど、ここが隅田川花火大会のそれか。了解。
  いつものようにテラスを神田川始流をめざす、
  むっとする暑さはあるが海風だから、正面に風がある。
  だが、いやな気分だ。これは焚き火になる。
  折り返しから焚き火だ。
  今日は、というか昨日からやる気がでない。
  だから、２ｋｍでやめた。
  もっと走れたがやめた。いじけた自分にいじけた自分が
  いじめをやってやめたんだ。
  そういうもんだ。だけど、俺はこの自由は自分の中だけ
  なので悔いることはない。２ヶ月後にフルマラソンに
  挑戦しようとしているのにたった、２ｋｍ
で終わりか、
  自由だ。どうやろうが自由だ。
  やめようがそれは自由だ。

* <2015-07-24 Fri 07:39> はげ
   「はげ」だれでも罵るときに使うことば。
   「はげ」いよいよ切羽詰まってしまった。
   昨日シャンプーした後、鏡に写った頭が
   キューピーちゃんのようになっている。
   「はげ」いやだー。
   AGA治療のTV CMは見なくなったが、
   髪の毛も見なくなった。

* <2015-07-26 Sun 20:42> R7.0 W1.0　隅田川花火大会
  昨日は隅田川花火大会、清澄通りを封鎖して
  道端にシートを敷いて、大勢の人たちが座って
  眺めていた。
  私のマンションからはライオンのビルが大きく
  塞いで、丸い花火を半円に切り落としていた。
  ビル群の隙間に見える花火を探して、
  いや既にわかっている住民や観客は何気ないいつもの道路
  に新たな価値をつけていた。
  隅田川花火大会には被害者達がいる。
  それは警察官だ。
  隅田川にそって両国国技館どおりが市役所へ
  と走っている。
  そこは花火をみることが許されていない。
  というか立ち止まることも許されないらしい。
  女性警官の公僕たる謙虚さのない怒鳴り声が
  立ち止まって花火をみようとするものを脅していた。

  この情緒のかけらもないくだらない一夜が過ぎて、
  ランニング開始。
  むっとする暑さが立ち込めた道路は花火大会の痕跡すら
  残っていない。
  隅田川テラスにもなんの痕跡もない。
  風もない。
  なんとか１０ｋｍと思ったが無理だった。

* <2015-07-30 Thu 21:54> 気に食わない奴ら２
  そいつらの俗称はセンコー。
  もう５０も過ぎるが今眼の前に現れたら殴りたい。
  小学校から中学、高校とこの職業の連中を思うと憎さを
  超えた殺意が湧いてくる。
  錆びついた鉄筋で打ちのめしたい。
  なんでこんな大人に会わなければ生きていけないのか。
  なんでこいつらについて学ばなければならないのか。
  明らかに生徒とセンコーでは権力の差がある。
  それを傘に偉ぶる教えるなんでお前らの価値観を
  押し付けられなければならなかったのか。
  いやでいやでしょうがなかった。
  俺の人生で小学校３年位が字が一番うまかった。
  だが、NHKの放送でシャガールが１本の線を描いていた。
  ただの折れ線グラフのように見える。

  そしてシャガールが言った。
  私はいかに下手に線を描くかの練習をしているのだと。
  俺はその時から字をうまく書くことなんか意味のないこと
  だと知った。
  字をうまく書くように言う人間であるお前たちセンコー
  にはへどと糞を食わしてやりたい。
  俺はお前らが言う社会の倫理や道徳などというものが
  大っ嫌いだ。
  だからお前らやお前らの作った教科書なんかのテストで
  まったくやる気がしない。
  特に嫌いな奴の科目は赤点ばっかだ。
  お前らは本当に嫌だった。
  だから本屋の純文学コーナーの本を買って、よみあさった。
  だれも教えてくれない、タイトルとその中身に希望を持って
  その世界に入った。
  そしたら自由が見えてきた。
  希望が見えてきた。
  お前らに絶望をあたえられ続けた俺は本で自由と希望を手に入れた。
  お前らは一体なにものだ。
  独裁のちょびひげか。
  安倍か。オバマか。
  
  

* <2015-08-01 Sat 13:43> R10.0 I1.0 W4.0 50肩
  昨日は酒を断って今朝は５時起きの６時ランニング開始。
  14ｋｍの予定でいつものコースを走るが南千住の行き止まりで
  気力が途絶えて、インターバルを５本入れたら、再度
  気力が途絶えて、walk に切り替えた。
  それでおしまいだ。
  50肩という字が変だ。
  ほんの１分のところに整骨院があり、その窓に５０肩という
  文字が目についていた。もう一年にもなるかYシャツを脱ごう
  とすると左肩に刺すような痛みが走って、これが５０肩か
  と納得してそのままにしていたがこの文字から
  治療できるのかと思っていて先週いってみたら
  花火大会があって、その整骨院の前にテキ屋が陣取っていて、
  １週間またされていたが、今日行ってみた。
  問診書いて待たされて、まだ時間かかるというので内科に
  いった、特定健診結果と毎月の内科通いの日でもあった。
  特定検診の結果心臓が肥大しているらしい。
  書かれた結果をみると軽度の左室肥大らしい。
  これはレントゲンによりわかった。
  心電図でも結果を反映しているらしく心臓の壁の厚みがあるらしい。
  これの結果は左室高電位と書いてある。
  それはランニングによるものかというとそうではないらしい。
  その後の経過観察とすることでいいらしい。
  その後整骨院に戻って５０肩の痛みについていうと
  納得されて、電気治療開始。肩に２極つけて電気を流す。
  勝手に筋肉が収縮する。それが１０分くらい、その後、
  マッサージ。これで５０肩の痛みを出している筋肉の
  まわりをほぐしたらしい。
  その後、ウォーターベッので背筋伸ばし、
  ふくらはぎから肩までバブルジェットでマッサージ。
  それも１０分。
  あんまり深刻じゃないのであと数回で治るらしい。
  保健も聞いて２５００円。
  安いかも。
  家に帰って、肩を揉むと痛い。
  ５０肩の痛みを出している筋肉はどこにあるのかわからなかったが
  今は触ると痛いので場所がわかる。
  痛みの場所が特定されたのはいいがこれで良かったのか。
  確かに左肩の全体に軽くなったのでまたいこう。
  

* <2015-08-10 Mon 20:28> R5.0 W2.0 夜ラン
  一昨日小岩の焼肉屋秋元で飲み会があって。
  そこは、有名で予約も取れないほどらしいけど、
  偶然とれたんで行きました。
  うまかったよ。
  そんで西船に遊びに行って悪酔いして、
  土日はランニングにならず。
  しかたないので仕事帰りに走ってみましたが、
  １９時じゃまだあついので５ｋｍで終わりました。
  ２０時半こえればいけるかもしれない。
* <2015-08-14 Fri 11:35> R14.0 W2.0 早朝ラン
  今日は山歩きもあるし、フルマラソンの練習もできないから
  気合入れて昨日から準備して１４ｋｍ走りました。
  あまりつよくはできなかったけど。
  満足だ。
  もうすぐ谷川岳登山の前泊に出発します。

* <2015-08-16 Sun 15:50> 谷川岳
  上越新幹線東京発１３：３２で越後湯沢へ。
  乗り換えで検索したら土合（どあい）駅まで
  はこのルートがヒットしたのでなんの疑いなく、
  このルートに決定。
  乗り換え時間もぴったしの時間で土合駅に到着した。
  実は越後湯沢は谷川岳を追い越して、新潟よりに
  来てたから上越線の土合駅は上りホームに到着という
  ことになっていた。
  上りホームはなんの変わりもない田舎の単線ホームだ。
  人気のある山でかつ盆なので混むと思ったが、
  新幹線も空いている。
  宿も２つめで空きがあったのですぐに予約した。
  土合山の家。
  ２食で８９００円。プラス弁当５４０円。
  綺麗に掃除されているのが嬉しい宿だった、
  宿泊は３組。
  夕食は、カニまでついてた。
  炊きたてのご飯はうまかった。
  夕食が終わって、部屋で、水筒に入れて持ってきた。
  焼酎をのんでいると、ペルセウス流星がみれるかも
  と思い立って、宿を出て街頭のない暗い道を
  登って行くと雲が晴れて左下から右上に流れ星が
  見えた。瞬間小さな線がいくつも見えて、
  また雲に覆われた。
  土地勘のない道は怖いので早々に引き上げて、
  宿で焼酎を飲む。
  明日の登山に影響ないほどでやめて寝る。
  明朝６時前に起床。
  板場では朝食の準備が始まっていた。
  昨日は朝食は７時と言っていたのに６時には
  食べられるとのこと。
  どうも女将の気分で決まるらしい。
  これで谷川岳ロープウェイの運転開始の７時に間に合う。
  朝食済ませて登山の準備。
  水は洗面所で組むのはやめよう。
  サビ臭いからだ。宿の玄関右に山の湧き水を引いて流しているので
  そこで汲のがよい。前日にそれに気づいたのは良かった。
  いつものように釣り竿とテント一式のフルセット装備。
  なので不要なものは宿に置かせてもらうことにしていた。
  だが、宿をでるとロープウェイまで車で送ってくれるらしい。
  おまけにロープウェイにはロッカーもあるらしい。
  宿に荷物を預けても風呂には入れてくれないらしい。
  金とってもいいのに。
  残念なので余分な荷物も持って行くことにした。
  車で５分もかからず到着。
  ロッカーに預けて２００円。
  ロープウェイの乗車は建物の７階にある。
  エレベーターを待っていると到着したのが６階だった。
  慌ててスロープを使って７階にいくと６，７０人が既に列で
  これはチケット購入待になっている。
  ７時の開始でみるみるはけてチケットを購入。
  宿から割引券をもらっていたので１割引位の２０００円弱だ。
  ロープウェイの乗車もみるみるはけて、一番景色が見れる位置に
  乗車。土合口から天神平までかなりのスピードで登る。
  景色を堪能して天神平到着７：２０。
  登山客は蟻の列にもなりそうだと想像していたが、少ない。
  レストランの下にトイレがあって準備おけー。
  いよいよ魔の山、人喰いの山、谷川岳登山の開始だ。
  標高は１５０２ｍ、土合口７４６ｍだからかなり楽してます。
  谷川岳はオキノ耳（１９７７ｍ）トマノ耳（１９６３ｍ）の
  双耳峰だ。この耳を目指します。
  天神平に着くとリフトが２つ見えるが２つとも休止している。
  実はロープウェイも７月２０日の大雨から休止していたが、
  なんとか盆の１３日に復旧したのだ。
  リフトを見上げて右側から登山道が伸びている。
  ７：４５分登山開始。
  前日も前々日も雨が降っているから土はところどころに
  水も浮いているが苦になる程ではない。良かった。
  広葉樹が生い茂る山肌に登山道が巻いている。
  かなり整備されて崩れるところには板が敷いてあり。
  滑り止めも程よく打ち付けられ、楽に登れる。
  これが天神尾の始まりか、傾斜もきつくない。
  １時間で熊穴沢避難小屋到着。
  少し休んで出発。すぐに傾斜が変わったのを実感する、
  鎖場ありロープありの岩場ありのコースになる。
  しかしところどころ写真を撮りたくなる景色に会うので
  楽しい登山だ。
  天狗のトマリ場という岩につく。
  この時期なら高山植物がたくさん見れると思っていたが、
  探さなければならないほど少ない。
  それでも見つけては写真を取るので結構時間を費やした。
  危険なところも殆ど無い。
  頂上らしい耳も見えるので心の折れるところもない。
  景色はすでに森林限界の様相となり、眼下には雪渓も見える。
  ３時間かけて肩の小屋につく、トイレもあるが
  使わない。登山客は多いが苦になるほどではない。
  小屋は宿泊できるしTシャツも売っている。
  ここから耳が見える。
  トマノ耳まですぐだ。到着して宿の弁当を広げる。
  おにぎり２つにビニールに入った漬物とみそピーナッツ。
  そしてちーかまが２本。
  ちーかまは保存食として、オキノ耳に向かう。
  オキノ耳は、大きくないのでこちらで食事をする登山者が多い。
  やはりラーメンを作る人が多い。
  ラーメンも持ってきていたが、それほど腹が減って
  いなかったから作らなかった。
  オキノ耳も景色はあまり変わらないのですぐに戻る。
  トマノ耳から肩の小屋にもどる途中小道を発見。
  そこにはオーバーハングの絶壁が出現する。
  足がすくむほどの絶壁がつま先からほんの５０センチ
  にある。はるかしたには雪渓がある。
  あとで調べたがこれがマチガ沢だ。
  距離感が全くつかめないが５，６００ｍありそうだと感じた。
  肩の小屋で少し休んで下山。
  結局天神平まで１：３０分で下山。
  早すぎる。だが７：４５から１４：４５分。
  遊びすぎで７時間かかった。
  いつかこの計画の悪さが後悔につながる日がくるかもしれない。
  バスで水上に行って温泉探す予定だが、
  １５：３４分の上越線の上り電車に間に合う時間だ。
  そのままロープウェイ土合口から道路を下る。
  途中思いもかけない滝に出会う。
  土合駅は日本一のモグラ駅７０ｍ地下に下りのホームがある。
  それも見たかったが、断念。
  上り線に乗って水上駅で接続電車に乗り換えて高崎駅に向かう。
  上り線は１８切符の若者がたくさんいて、席どりのため
  ごったがえす。連れがそれに勝ち残って、座れた。
  しかし、鈍行のこの列車はジャスト１時間のエコノミー症候群の
  苦痛を味あわせて、高崎駅につく。
  ここで焼肉食べて、新幹線に乗って例のちーかま摘みにビール
  を飲んで愉快になって、上野で下りて、両国についた。
  帰路の清澄通りには東京都慰霊堂がある。
  震災記念堂だから関東大震災のものだ。
  この前の広場には沢山の灯籠がそえられて、今日が盆だと悟らせてくれた。

<2015-08-23 Sun 13:15> R10.0 W3.0 またも工事
  フルマラソンもあとひと月にせまる。
  なんとか距離を稼ぎたい。
  朝７時開始、いつものコースを走るが湿度９５％がそれを拒む。
  １４ｋｍにするかどうか白鬚橋６ｋｍ地点で決めようと望むが
  税金を使いたい輩の悪意が工事中の看板を打ち立てていて。
  到底走るに適さない横道に誘導し、１０ｋｍも走らせまいとする。
  この看板の設置場所はbuild upの最後の力を奮い立たせなければ
  ならない場所だ。
  めげる、それでも走りながらテラスの周回コースでハーフと３０ｋｍ
  をやるべきか、考える。
  結論はこの横道を受け入れるしかない。
  だが今日はもうやめる。憤りに耐えられない。
  筋トレもなんとか絶やさないでやっている。
  体重を６６ｋｇにするため飯制限もしている。
　網走が当初の予想より寒そうなのが救いだ。  
  
<2015-08-27 Thu 04:35>　R11０0　W2.0

  朝５時起き昨日は小雨降る御茶ノ水界隈だったし、
  すこしつかれもあるのであえてやめた。
  酒もほどほにしてホークスが勝ったのをみてねた。
  すこし遅めだが朝の雰囲気から温度が２０度さがっている
  のを感じて、チャンスやってきた。
  水補給とストレッチを済ませて、開始５：４５分。
  いつものコースで今やばしから対岸に渡って、神田川の
  支流まで、折り返しても風がある。
  ほどなく６分にあげても気温は上がってこない。
  例の間抜けな工事看板を横目に見て諦めた民家の路地を
  縫う。おそらく５００ｍの＋だろう。
  快調に白鬚橋を折り返して、センターの柔らかい帯を
  走る。信号待ちをあえて選んで呼吸を整えてbuildup
  の仕上げに入る。
  もうこの横道は苦にならない。
  ＋５００加算の見る価値のない景色だから記憶に入れる必要
  も名前を知る必要もない。
  そこを抜けて本来のbuild up の仕上げにかかる。
  横道で上げられない分。ここで急に上げていく。
  住人のテントは増えた減ったか知らないが、それを超えて
  いつものフィニッシュに向けて心拍数最大にして駆け抜ける。
  だがその前に白い鳩がコースにいる。
  だから１０ｍ手前でフィニッシュ。しさびさに走れた感で
  気持ちがいい。
  時計をしているので１１ｋｍで６５分だ。
  うん少し遅いな。できれば５５分で上げたかった。

  
* <2015-08-30 Sun 14:00> R24.0 W1.0 フルの恐怖

  月間総距離は51kmになったが、目標の倍の80kmには、程遠い。
  兼ねてより考えていた24km走破を試みた。
  金曜日の夜１０時に寝て４時半開始狙ったがあっけなく寝坊。
  日曜の朝に順延しようとしたが、外にでると小雨が舞って、
  肌寒い。夕方狙いでも行けるんじゃないかと入念にストレッチ。
  ワセリンも足の指に縫って17時ジャストに開始。
  湿度は高いが気温は２０度を下回っていて、風も心地よいから、
  楽に進む。24km は自己最長から1km長い。もう4,5年も前に、
  リュックを背負って浦安を回ったものだ。
  距離は走り切れたのが23kmというだけだった。
  今回はフルの為の長距離の目標を設定しての走りだから、
  種類が違う。だが、ハーフより落として開始とはいえ
  5kmで４０分かかった。骨盤の回旋もいい感じなので、
  そんなに遅いのも変だが、12kmの折り返しで、
  ストレッチ入れて、何分か。。。忘れた。
  骨盤はまだ粘っていて、15km で水分補給とストレッチ。
  16kmの再びの吾妻橋からテラスに戻る。
  神田川の折り返しまで順調。左で踏ん張って、ふくらはぎ
  に痛みが走る。乳酸のた疲労痛というよりは棒で
  叩かれたような疎い嫌な痛み。
  それで分かった。蹴りすぎだ。
  18km過ぎで２時間１０分。
  発汗はパンツとシャツをずぶ濡れにしているので、３ｌは
  超えている。
  このまま水分補給無しで24km走ると危ない予感。
  20km の吾妻橋の交番の横で水分補給半分を捨てて、
  ラストの４ｋｍ の両国川テラスに降りる。
  やばい暗いの痛みがふくらはぎを走っているが、
  ここでやめると連鎖してフルが失敗する。
  テラスは暗いのでペースもつかめず、段差にもつまずく。
  両国インター近くまで行くと工事の看板。
  これでやめられる理由があった。みると一人の男が、酒
  飲んでいる。その横をみると看板の横に道が細く続いていた。
  まだやめられない。
  それから折り返し２００ｍ程の前にやっと工事で打ち切りだ。
  ストレッチを入れなおす。背筋と首にも重い痛みがある。
  これからラスト２ｋｍ。
  走り直す。テラスは街頭が少ないが両国側の水上バスのりば
  は明るい街頭が連続している。
  明るさは不安を消して、ここで５分代にあげてみる。
  上げられる。その外灯切れるところまで上げて、
  終わり。ここからまたゆっくりにして吾妻橋のライトアップ
  された橋桁を目標に闇のテラスを進んで、フィニッシュ。
  大会と同じようになにもなく終わる。
  だが24km 自己最長記録更新だ。
  帰路ですぐに水分補給。
  だがおかしい、飲んでいるのに乾きがおさまらない。
  これが酒による内蔵力の低下だ。
  交差点で太ももに手をやってたたずむと自転車の親子は
  寒いねといっている。その横で後頭部に水を注ぐ。
  24km2時間58分だった。
  フルは甘くない20km過ぎて一挙に落ちる。
  この状態であと18kmは地獄を味あうだろう。
  サブ５も夢と消える。
  
* <2015-09-01 Tue 20:29> R1.0 WS1.0 Wind sprint
  会社帰りwind sprint を思いついた。
  両国川のテラスの外灯がならんで明るいところだけ
  全速力の８０％=wind sprint で走ってみよう。
  １９時過ぎに戻って開始、厩橋下りて、両国インター下に向かう。
  最終点は工事中。住人もいるが暗い。
  やはり両国の水上バス乗り場だけがナイター設備だ。
  ここをwsしてものたなささのまま終わる。
  もうすこしマシなコースを作らないとだめだ。

* <2015-09-05 Sat 20:38> R15.0 W2.0 走るためのダイエット
 先週24km走の走りだし体重は70kgを超えていた。
 今日は、68.5kg昼間の摂食は効果がでているが、
 3kg超はブレの範囲なのでいつ戻るかわからない。
 今日は長距離の準備はしていないので、10か15km
 しかできない。
 走りながら考える、15km にすべきだろう。
 すこしセイブ型の走法も考えてみる。
 着地から足の裏のしなやかな曲がりと送りが鍵だ。
 １８ｋｍまで続く80mと40mの山登りを制覇するには
 それしかない。
 それとリズムだ。先週はなんども起こるUターンに
 リズムを作り直す事ができず無駄にタイムを落として
 足への負担も蓄積されていた。
 1) 体重を開始点で66kg。
 2) しなやかな着地と足の送り。
 3) リズムを作りなるべく長く維持し走ること。
 めざすはこれを36km までやること。
 後の6kmは例のなりふり構わず。走り切るという走法だ。
 今日のラン後の体重は66.2kgほどだ、少し脱水感がある。
 

  
  

  
  
  


* <2015-09-09 Wed 13:49> R3.0 台風
  仕事がノウザンデーなので早く帰ってきて、
  雨の降らないコースを走ろうと思ったけど、
  雨脚はひどいし、テラスの内側に残土なんかをおいて半分以上
  テラスの幅を専有しているところがあり、
  うまく高速の下を走れずにいたけど、厩橋と両国橋の
  あいだならうまくいくと思っていたら、
  両国橋の下くぐると水没していて、靴がびしょ濡れに
  なった。靴がびしょ濡れは戦意で喪失。
  あっけなく３ｋｍで押しまい。
* <2015-09-12 Sat 21:09> R15.0 W2.0 15km初日
  ホントは30km走りたかったが、気温が高いしコースを
  つくれないのでやめた。
  午後４時開始。
  15kmでbuild up もできたんで、よしとしよう。
  白鬚橋の工事中は辛いなるべく直線を選ぶが、
  すれ違う自転車歩道のギャップや信号。
  狭い信号は歩行者も自転車も十分注意しないと危ない。
  そしてディニーズをバーミヤンとファミリマートが
  いったいになった噴水と池がある施設のコーナを左に
  柱のオブジェを縫って白鬚橋へと登る。
  風は橋を渡り切る頃に吹き始めて応援をしてくれる。
  よくもまあこんな急所を工事にしてくれたもんだ。
  この近辺浅草側はどうだと以前回ったがこちらも道路を
  走るように工事現場から誘導している。
  両岸でおなじところを塞いでいるんだ。
  白鬚橋を渡って、水上大橋をくぐって南千住の最後の
  隅田川テラスで折り返し、ここでは決まって軽くストレッチ
  夕闇の帳はもう裾を残して閉めかかっている。
  もう顔も見えない。
  そこからふただび開始。
  いつもここからは快調に進む。風向きもいいからか。
  と思っていたが、体水分量がここで３ｋｇ近く落ちているから
  ではないか。
  だから軽く感じる。バーミヤンコーナーは危ないのでゆっくりに
  してラストの暗い、住人のもはやこれは掘っ立て小屋といれるまで成長
  したブルーシート小屋を左にみてこれが切れると心拍数を最大にして
  フィニッシュだ。
  こうなれば、モルヒネが帰りの２ｋｍを幸福にしてくれるのだ。
* <2015-09-13 Sun 13:21> R15.0 W2.0　15km連日
  オホーツクマラソンのためには練習で３０ｋｍを走るというのが目標だった。
  だがコースがない、全部をやるには給水ポイントも設定しなければならない。
  気温は夜間しか無理だ。早朝というてがあるかもしれないが、早朝は無職
  で開始することになる。食事して２、３時間はかかるから５時開始は難しい。
  それだから１５ｋｍ連続と設定しなおした。
  その次の日が今日。
  ２日連続１５ｋｍは経験がないが、５ｋｍを過ぎてわかる。
  疲れが残っている。太ももやふくらはぎに重いものを感じる。
  これが効果だと直感した。
  インタバルでは瞬間の筋肉しか傷つかないがこれは持久の筋肉が
  こわれていくんだ。きっと。
  それで前日と同様コースを重くなったとはっきり感じてフィニッシュした。
* [2015-09-19 Sat] R8.0 W2.0
  今日は中を開けてしまった、途中に散髪入れたもんだから走れなかった。
  それでも１５ｋｍ走っておいた方がいいと思ったが、扱った。
  それでバーミヤンコーナでやめて水飲んで折り返して８ｋｍとなった。

* [2015-09-21 Mon] R5.0 W2.0
  前回の走りはダメだったが、もうだめというか、りっぱな走りには
  できない。内蔵を動かしてフィニッシュした。
  それでもあつい。
  テラスの浅草側を走っただけだ。
  これでいいのか心配だがあとは綺麗に酒を断ってダイエットの67kg中
  をスタート位置に持ってこれるかどうかだ。
  明日は、姪っ子の全国吹奏楽の決勝が錦糸町のトリホニーで行われる。
  私しかいないのでvideo が失敗しないことを願うのみである。
* <2015-09-23 Wed 20:55> R3.5 W1.0
  今日走らなければ、ブランクが３日となってしまうので、慌ててスタート。
  やばい。
  どこまで本番に弱いのか。腹筋で腰をいためた。
  走る分にはいいが、屈むと軽いがじんと来る痛みがでる。
  ジクロテクトを大量に縫って、明日どうでるか。
* <2015-09-26 Sat 08:38> 網走オホーツクマラソンしゅっぱあーつ
  腰の痛みはどうなのか自分ではわからないけど。
  おそらく治っていない。
  朝の体重は67.5少し重いがこれ以上は難しい。
  網走の気温は１８から１９度になるので、半袖で望むつもりです。
  大会のページをみるとArcGIS のアプリでコースを表示できるように
  なってますが、距離表示がないので糞のやくにもたたねーな。
  ESRI っちゃこんなもんだ。へどがでるぜ。
  やはり、５ｋｍからの８０ｍの上りと１８ｋｍまでのアップダウンが決めだ。
  関門のタイムが延長されている。
  金哲彦先生が走って助言したのかな。
  ますます、びびりまする。
  とにかく、サブファイブ頑張ります。

* <2015-09-27 Sun 23:38> R42.195 第一回オホーツク網走マラソン　結果5時間２７分
  走ってきました。
  参加者は２６００人あまり、クラスは、４８３人中３５１位、５時間２７分でした。
  サブファイブ達成できませんでした。
  ２６ｋｍでwalk しました。
  やはり、フルの練習はしていなかったんでしょう。
  Line Play のフレンドに誘われて、無謀とはわかっていたんですが、
  チャレンジしてきました。
  ５ｋｍでオホーツク海を望んで、左に折れ、まもなく１８ｋｍまでの
  アップダウンが続きました。
  エイドは５ｋｍ毎に農大生１年の継承されたボランティア精神の声に
  励まされ、出された食事はすべてとって、水分補給も、怠らず。
  ７．５ｋｍから５ｋｍ毎に設置されたスポンジで後頭部を冷やすも
  ２６ｋｍでふくらはぎの真中の痛みとももの痛みからwalk を取り入れないと
  ５時間は危ないと判断して、２００ｍwalk８００ｍrunを繰り返すが、
  ３５ｋｍでは半々になり、しまいにはwalk が多くなり、
  39ｋｍで５時間を超えてしまいました。
  37kmでは雨が降り始め、雷鳴響く、豪雨となり、ゴールの位置も
  わからず、ラストもかけられず、フィニッシュしました。
  しかし、このマラソン大会は素晴らしかった。
  エイドの充実、街の意気込み、１ｋｍ事のポスト、そして景色。
  コースは、完全に車両が排除されていました。
  マラソン大会ってこんなに楽しいもんなんだって、はじめて、
  思いました。
  いままで走ったハーフはなんだったんだろう。
  ８０００円の参加費は安すぎる。
  アームオーム、木の完走メダルと大きな大会バスタオルをゴールに
  女子大生にかけてもらい。
  食事券、ビール券もついて、素晴らしい大会だった。
  豪雨のゴールでのバスタオルはあったかった。
  来年も走りたくなった。
  てか網走に住もうかな。
  土曜日、女満別空港に昼過ぎについて、網走駅までバスで移動し、
  ザンギ丼を食べようとセントラルホテルに行くが、１４時で終わり、
  まわりで食べるところ探すと、全部準備中。
  きっぱり昼飯抜きに決定。
  引き返して、刑務所まで３ｋｍジョグ。これで明日の準備終わり。
  網走川を下流に戻ると、大きな水音が、耳に入る。
  よーく水面をみると無数の鮭がいるではないか。
  ああ、北海道だ。
  素晴らしい。網走は、アイヌ語で我々が発見した土地という意味だと、
  看板にある。
  北見の東横インしか空いてなかったので電車で一時間かけて、
  女満別を通り越して戻らないといけない。
  そのままwalkで下るとオホーツク海が見える。
  道の駅でコーヒーのんで満足する。
  １７：１８の特急で北見に５０分でつく。
  駅前のデパートの６Fが食事できるらしい。
  北見塩焼きそばとビールを飲む。
  酒はここ数日絶っていたからリラックスの意味だ。
  そして明日５：３０に起きて、６：３０からバイキング。
  軽く食べて、６：５４分の始発に乗る。
  駅にはランナーの列がすでに出来上がっている。
  早くきて正解。昨日切符も買っていて正解。
  なお、スイカは使えないのを事前に聞いていた。
  ディーゼルの匂いの時折する車内は、ランナーで
  いっぱいだ。みんな同じ、緊張が伝わってくる。
  駅でトイレを済まして、すき家前から５分おきに出ている、
  マイクロバスに乗り、５分で刑務所に到着。
  更衣室で、着替えて、荷物を預けて、自分のブロックEを
  探す、途中、谷川真理を発見みんな無視なので無視する。
  そして、金哲彦先生とワイナイナの声は内容を聞かず、
  スタート砲。５分がネットになる。
  それにかねてよりの時計のベゼルをあわせる。
  そして、５ｋｍのオホーツク海を見、声をかけられる。
  ほんとにラインプレイのフレが応援してくれた。
  ジーンとなって、手を振りなおして、坂に挑む。
  これが大会の朝の話です。
  そして、Line Playは、今では、e-MailとLineに変わった。
  やったね。
* <2015-10-04 Sun 11:28> R10.0 W3.0 大会の後
  まだ暑い日が復活していた。
  数日前まではもう昼間でもはしれるんじゃないかと思っていたが、
  昼間走れる程にはもどっていなかった。
  だから４時頃開始大会後だから１０ｋｍと決めていた。
  酒も大会後に飲みだしていたので、またもどっているかと
  思ったが、そうでもない。
  体は５ｋｍでbuild up しようとする、しかし、それでも白鬚橋
  の工事までだ。
  一般道にと走りづらい、どうしても乗らない。
  これを２回通過するのも面白くない。
  そこでフィニッシュを早めることに変更した。
  このまま水神大橋まで行って折り返して白鬚でフィニッシュだ。
  これで気持ち良いフィニッシュが完了する。
  帰りのクールが３ｋｍに伸びるがいいだろう。
  昼間走れる季節だから探検もできるだろう。
  といういうことで３分代まで上げてフィニッシュ気持ちいい。

* <2015-10-10 Sat 18:28> R10.0 W3.0 もう秋
  もう昼間でも走れる。気候は秋へと変化した。
  白鬚橋の工事は参っているが、それを利用する前回のランは
  もうひとつ進化した。
  白鬚橋の工事中までの6km を一つのbuild up で完結し。
  そのあとの一般道で調整し、水神大橋まで２ｋｍ少しを再度
  5分から3分まであげてフィニッシュする。
  ２段階build up へとするランニング方法を考えだした。
  太ももとふくらはぎの乳酸の倦怠が効果を裏付けている。
  トータル10kmとは思えなほど疲労感がクールの間中覆っている。
  しばらくこのランニング方法でやってみよう。
* <2015-10-18 Sun 19:14>　R20 W5.0 お台場
  昨日は、ホークスのクライマックスステージの優勝がきまったので、
  妙に飲み過ぎて、首が震えているので、ちゅうきにもなったのかと
  思って、一日中寝てた。
  夜も酒をのまないでおこうと思ったが、それは、先のことはわからない。
  睡眠薬のんだあとに飲んでしまった。
  人生はほんとに先のことはわからない。
  朝だけ自炊でハヤシライスを作って食べたが、昼になっても食欲も
  わかない。１３時近くになって、ひらめいた。
  リュック来てLSDをしよう。隅田川を上流はいつも行っているので、
  下流に向かおう。
  そうだ、お台場だ。
  という思いつきで、しゅっぱーつ。
  秋晴れとはいえ日差しはすぐに汗を出させる。
  隅田川テラスを両国橋のもうひとつ下から右岸を下る。（どうも下流に向かってそういうようだ）
  順調だがすぐに川に切られて、お台場方面へと最短の角々折れで、
  向かう。なかつかないが２時間かけて到着。
  仕事先に向かうためりんかい線で天王洲アイルへ向かうとき、
  おどる走査線のあのメロディーの駅に到着。
  お台場公園へ向かうとまだ海水浴という行為をやっている人たちが
  いっぱいだ。
  証拠写真を一枚とって、帰ろとすると、水上バスが到着。
  これにのれば両国につく、時刻を聞くと１時間近くあるので
  やめて、帰路につく。
  道間違える。
  ほんとgoogle map駅も乗ってねーのかよ。くそ。
  まあ、２，３ｋｍのオーバーで相生橋までつく。
  それほど体力は落ちていないが、次の橋でやめよう。
  やめたのはおそらく３ｋｍ以上河口だ。
  ある気がつらい。
  結局、４時間３０分かけてこの思いつきはやり遂げた。
  距離はざっくり１２ｋｍX２くらいだと思います。

* <2015-10-25 Sun 19:14>　R7.0 W3.0 
  今日はテラスの神田川河口から吾妻橋だけの折り返しを狙った。
  だがやめた。
* <2015-11-01 Sun 19:14>　R10.0 W3.5
  
  いつものようにコースをなぞって、白鬚橋の手前で、一般道に入って
  またコースへもどる、コースだ。
  だが、白鬚までの６ｋｍでのビルド、次に水神大橋折り返しのビルド
  でランニングはできた。
* <2015-11-07 Sat 19:14>　R7.0 W0.5
  神田川、吾妻橋でビルドできるかと思ったが、やめたくなったんで、
  やめたんだろう。
* <2015-11-15 Sun 14:26> R10.0 W3.5
  + アラ鍋(はた科のクエを出している）

  　吟ばん
    03-3252-1030
    東京都千代田区神田須田町1-17 第２Ｆ＆Ｆロイヤルビル　Ｂ１Ｆ

    銀座 土佐料理 祢保希（ねぼけ）
    050-5799-5191
    〒104-0061  東京都中央区銀座7-6-8 西五番街通り
    ＪＲ 新橋駅 徒歩4分
    地下鉄 銀座駅 B3出口、またはB5出口 徒歩4分

    赤坂 土佐料理 祢保希（ねぼけ）
    〒107-0052 東京都港区赤坂３丁目１１−１７
    03-3585-9640

  + アラ鍋(スズキ科のクエを出している）
    せんふじ
    東京都台東区根岸2-20-12 青木ビル一階 TEL 03-3873-1129
.
* <2015-11-15 Sun 21:18> R10.0 W3,5
  今日も走れた。
  白鬚まででビルドして水神折り返しの再ビルド、かなりきもちよく終わった。
  
* <2015-11-23 Mon 21:06> R11.0 W1.5
  隅田川テラスを最高のランニングコースと思っていた。
  いや、いまも思っている。
  だが、今日は、新たな通行止めが、されていた。
  吾妻橋ー神田川に２箇所神田川にはくだれず、吾妻橋にも登れず、
  一般道にのぼっていくしかなくなっていた。
  もう、４週間もブログを書いていないが、書きたい気持ちがなかったんではなく、
  書こうとする気持ちが現実のそういうもので阻害されていただけだ。
  私の精神や肉体にそんな異変はない。
  そんな異変があれば面白いからブログを書きたいと思ったはずだ。

* <2015-11-28 Sat 21:06> R4.0 W0.5 両国川テラス
  明日は、小松菜マラソンの１０ｋｍだから今日は少し走ってランニング
  モードに戻すためテラスにでた、昼過ぎの日差しが心地よくなっていて、
  ひさしぶりの両国側テラスを走ることに決めた。
  テラスは工事のための材料置き場と工事による封鎖があったがすべて
  解消されてフルに走れる。
  往復４ｋｍそのことを確かめて終わり、明日の１０ｋｍに望む。

* <2015-11-29 Sun 21:06> R10.0 W2.5 小松菜マラソン
  朝８時半、大江戸線で両国駅から森下駅へ、都営新宿線に乗り換えて、
  東大島（ひがしおおじま）まで２０分、
  下りて荒川河川敷へ、久しぶりの荒川だった。
  天気は快晴、気温も湿度も申し分ない、ランニング日和だ。
  小松菜マラソンは、２０ｋｍ，１０ｋｍ、５ｋｍ、親子のエントリーがある。
  １０ｋｍの記録を出して、フルマラソンの再構成の材料にしたい。
  だから、３４５０円出してエントリーしていた。
  河川敷は、何回もサイクリングしていたので記憶にある形状だ。
  マラソン大会だからそれなりなのめぼしいテントやらがあるはず。
  探したが２，３ののぼりがあるのでまさかと近づくと、のぼりに小松菜の文字があった。
  これだ。ううん陳腐。
  ９時半からの受付ということだったが、９時でもできるらしい。
  名前を言ってゼッケンをもらい、公園のベンチに荷物をおいてストレッチの
  準備をする、しばらくするとスタッフが参加賞を持ってきた。
  ビニール袋に入った小松菜うどんの乾麺だ。
  ううん陳腐。
  この大会は高校のマラソン大会レベル。
  ストレッチしてコースの下見を兼ねて１ｋｍ地点にむかう、
  赤いコーンに１ｋｍ表示。
  ２ｋｍのウォーム完了。
  そういえば、チップもない。
  手動計測らしい。３４５０円だして手動かよ。
  １０：２５分が１０ｋｍのスタート、その前に５ｋｍが走る。
  この大会で唯一のマラソン大会ぽいのがデジタルの時計。
  それが５ｋｍにあわせるから、５分遅れで自分のタイムになる。
  スタッフがコースを説明、おおい、２．５ｋｍの折り返しかよ。
  往復５ｋｍとあったが河川敷利用した大会で４回も折り返しがあるのかよ。
  ３４５０円だして、チップなし。２．５ｋｍの折り返しかよ。
  詐欺の大会だ。
  ２０ｋｍにでなくてよかった。８回の折り返しは、テラスのコースでもないぜ。
  コースは正確に言うとスタートラインから２．４ｋｍ上流に登って、
  折り返して、スタートラインを通り越して１００ｍで折り返して、
  スタートラインにもどるというもの。
  案の定大会参加定員４００名はいない。
  スタート位置に並ぶと給水があった。
  のんでみる、水だ。
  いや、みずじゃない。うす～い。まずーい。
  のめずにゴミ箱へ。
  １０：２５分になってスタート。
  計画は、１ｋｍの入りで６分弱、その後、５分前後で６ｋｍまで、
  ７ｋｍで３０秒落として、ラスト２ｋｍで４分、５００ｍで３分
  でフィニッシュだった。
  だが、スタート直後にまわりに合わせて、４分台。
  ３ｋｍで１４分、速すぎる。
  自然に落ちるが呼吸が調整できない。
  ４ｋｍでやめようと思ったが、いつもの４ｋｍの壁。
  ５ｋｍ過ぎて、うしろから来る２０ｋｍのランナーが抜いていく。
  なんか走りが違うランナーにも抜かれる。
  最後から２回目の折り返しでそのランナーがコースから外れる。
  リタイアか、じゃない、一般参加のランナーだ。
  てか、ただでこの大会参加できるんだね。
  きつかった、スタートラインに戻るが、１００ｍ先の折り返し、
  まで行かなくては、その折り返しは、ほんとがくっとくる。
  そいで、ゴールラインにもどる。
  二人のスタッフが計測に必死だ。
  頼むから間違えないでくれ。
  計測時の混乱を防ぐため１００ｍ折り返しを入れてるんだからね。
  デジタル時計は１時間をわずかに切っていた。
  これは５ｋｍのタイムだから５５分ということだ。
  やっぱりね。
  呼吸整えて、ブルーシートを４枚敷かれた荷物預かり所で、
  シャツを着替えて、帰る。
  JR平井駅に向かう。
  平井は今年の引っ越しで住もうかまよったところ、見てみたい。
  みた。腹減った。
  ううん、もう見に来ることはない。
  韓国料理の看板みて、プルコギ食べたくなった。
  ボリュームたっぷり、ひたすら食った。
  火曜日、結果がインターネットに載った。
  ５４：３０だった。
  平均で５分２７秒だ。
  一週間してハガキがきた。完走証だ。
  裏に完走証。表にタイム。
  おいれのマラソン記録は個人情報じゃないらし。
  
* <2015-12-06> R7.0 W2.0
  両国側のテラスが全開なのでこちらを開始位置にして
  コースを組み立てようとする。
  テラスに入って、厩橋まで登って折り返して、両国インター
  まで下って、折り返して、吾妻橋まで上る、吾妻橋は
  スロープがあるから階段登りはない。
  交差点にでてほとんど青はないので観光客なんかと一緒に
  シグナルを待って、言問橋、さくら橋を横に通過して、
  白鬚橋に向かう、だが白鬚橋の前は工事中。
  この工事は１２・２８まで、この対岸も工事で封鎖されて、
  テラスはランナーに受難を与えている。
  てか、ほんとこの白鬚橋の工事はかかりすぎだ。
  これを土方肥やしという。
  いままでのようにここまで第一弾のbuildupして
  一般の道にでて、白鬚橋を渡って、水神大橋で折り返して、
  ラストのbuildupするのだが、今日は寒い。
  ３ｋｍのクールは耐えられない。
  なので白鬚の工事を折り返して、さくら橋でフィニッシュ。
  受難の冬のテラスのコースこうなった。
* <2015-12-13 Sun>R4.0 W.0
  今日は雨がふっていたから高架下のコースを選ぶ、
  工事用の機材が取りさられていたので、満足するが、
  なんか面白く無いので４ｋｍでフィニッシュ。

* <2015-12-20 Sun>R15.0 W2.0
  ひさしぶりに快調。
  15km荒川区まで到達して、最長コースでフィニッシュ。
  最後までbuild up３分台まで上げた。

* <2015-12-26 Sat> R6.5 W2.0
  なんで集団作ってランニングやるやからがいるのかな。
  ランニングという自由なものを集団の規制をつくって
  走って、くだらない会話して、走って、不自由をつくって、
  マヌケな人生歩んでいやがる、じゃまだよ。
  今日は、最初は調子はわるくなかったが、
  体が６ｋｍでやめた。
  これで走り納めか。
* <2016-01-31 Sun> R12.0 W2.0
  なぜこんなに長くはしらなかったか。
  それは仕事をやっていたから、仕事はキツイ。
  平日も土日も容赦なくそれを終わらせるため、
  山を登るように、折り返しをもとめ、ただ、
  今を頑張るしかない。
  それが仕事というものらしい。
  そのくだらない世界の合間を狙って、今日走った。
  12/28で完遂しているはずの白鬚橋の前の工事は2/28まで
  だれか他に責任があるような看板で塞がれて延長されていた。
  この工事8/1から始まっていたんだな。
  多くの工事を受注して、人が回らず、タイムシェア的な
  仕事で税金を奪っている光景がはっきり見える。
  つばをひとふきして、通常の道路に迂回する。
  ひと月走らなかったが、体は問題ないらしい。
  心は、つらかったから体も疲れただろうといたわったが、
  その必要はなかった。
  それでも南千住の隅田川の折り返しまでで、ふくらはぎが
  やめたいと言った。
  だからやめて折り返してビルドを終わらせた。
  空は、紫の色を足して青く高かった。
  ひだまりを抱える東側のテラスをクールする。
  幸せという言葉なら今自分に降り注いでいる。
  走るために生きてきたと言える。
*<2016-02-11 Thu> R11.0 W3.0
 仕事はまだ続いている、走るために生きていた。
 その証明のために朝１０時に開始。
 震災3/11を知る私は、昨日から恐怖に駆り立てられている。
 いや恐怖ではない。
 こころ踊る楽しみを体現できないか、うきうきしているのだ。
 私の住んでいる両国には国技館があってその横に江戸美術館がある。
 スターウォーズのパクリのような像の足の下はゆうに１００ｍを
 こえている広々とした空間が広がっている。
 これはなんだろうと考える。
 最初に思いつくのが死体置き場だ、無数の死体を並べるには雨をしのげる
 し都合がいいはずだ。
 隅田川のテラスは焼け出された住民が水をもとめて並ぶ姿が見える。
 私の楽しみとはこの光景に直面することだ。
 両国駅を少し南に向かうと回向院という寺がある。
 これは、江戸の大火や関東大震災でなん万人も葬った、寺らしい。
 それは最近気づいた。
 まさにこの土地にはそいういうわけと来るべき準備が行われている。
 その準備がどこかで行われていると体が察している。
 それが今日の私の楽しみだ。
 いな今週末の楽しみだ。
 ランニングはひだまりのあるテラスをえらんで走るが西側はすぐに工事
 になり、吾妻橋まではテラスの横のビルがならぶ小道を走る。
 吾妻橋から白鬚は工事がないので階段などが途中にあるが今一番いい
 区間かもしれない。
 それを登って、白鬚橋を超え、南千住のテラスの終わりまで走って、
 ストレッチをいれて折り返しのビルドアップをする。
 そして３ｋｍのクール。
 前回と同じ空は紫を増している。
 あの震災の時と同じ紫の空だ。
 カモーン。あの黒い波よ。この東京の薄汚れた。砂の楼閣の一切を
 流しされ。
 川渕の木々の枝には布切れではなく、ひしがれた死体をつるせ。
 東京という人間の巣。砂粒をまぶしたような気持ちの悪い巣を
 その黒い波でうちながせ。
* <2016-02-14 Sun> R5.0 W1.0 
 欲望の始まりか、途中か、果か、その各々の欲求を表した、
 きしめくように立ち並ぶビル。
 外灯の光は光々と、真天井に輝く真円の月の光さへ無意味となる。
 この時ビルは砂から生まれて砂にもどる。
 そして何度も何度も微塵にすり潰されて、もっと小さな粒になる。
 いつしか粒は、やみに閉ざされ時間もない静寂の世界になる。
 ランニングは内蔵のうずきがすごいし、やる気の根源がそこにあるので、
 それを具現した走りで隅田川テラスの両国側をうろちょろしている。
 ときどき吐くものもないはずだが嗚咽が回る。
 吐いて楽になりたいが、胃にへばりついたこの汚物はでてこない。
* <2016-02-21 Sun> R12 W2.0
 今日は、白髭川のコースが１度遅れた工事の２度目完成日を過ぎているから
 復活しているかもしれない。
 朝遅いにもかかわらず寒い。浅草側のテラスが日があたっているからそこを走る。
 しかし、蔵前橋を渡るとまた工事のフェンスで塞がれている４末まで走れない。
 折り返して厩橋のスロープを登る厩橋をくぐっても駒形橋に行けずに
 また工事で封鎖されているから。
 ここで一般道に上がって、浅草の吾妻橋まで寒そうなビルが作る細い道を
 ひだまりを探して走る。
 浅草の交差点を観光客と一緒に待っていると、元気な中国語や人力車の
 若者の声聞いてそれはそこに置いて吾妻橋から白髭橋までの浅草側テラス。
 ここは石畳あり段差ありで集中できないがノンストップで２ｋｍ近く
 走ることができるから良い。
 だが今日はここじゃない。反対側のコースを行く。
 観光客と地元の住人をひよこの雌雄を判定する技師のように一瞥して
 識別しながら吾妻橋を渡る。
 工事完了を裏切られていたから心配していたが、白鬚橋への道路は開通
 していた。
 南千住の駅までいって折り返して、白鬚橋に戻って桜橋手前まで
 ラストスパートこれでやっとbuild up できた。
 
* <2016-02-28 Sun> R10 W3.0
 今日は、水神大橋折り返しで、先週に続き桜橋手前まで
 ラストスパートこれでやっとbuild up できた。
* <2016-03-05 Sat> R9.0 W1.0
 すべてやる気がなくなって、ランニングは、両国の右岸を
 往復して、フィニッシュ。

* <2016-03-13 Sun> R5.0 W1.0
 どのコースを走るか迷ったままスタート。
 お台場へのランニング依頼、隅田川を下る。
 両国橋を渡って対岸へ、ここの距離も忘れて、ただ走る。
 簡単に途切れて、往復４ｋｍ弱、両国までで５ｋｍか。
* <2016-03-20 Sun> R14.0 W2.0
 土曜日走れないというのは金曜日に酒をあおっているから、
 その単純な理由で今週も日曜日になった。
 10時過ぎスタート。対岸のテラスに日があたっているので
 厩橋を渡る。ただし、駒形橋過ぎは工事なので折り返す。
 それで温まって、もう一度両国側に戻ってインター折り返し、
 吾妻橋で戻って、いつものbuild upコース。
 南千住までいって、最後もまともにbuild upかけれた。

* <2016-03-26 Sat> R10.0 W2.0
 土曜日の悪循環をなんとか断ちたい。
 そういう思いで３時過ぎに無理に開始。
 やっぱり調子が悪い。もう１ｋｍでおかしい。
 ここでやめると後悔の念の方が嫌なので無理をする。
 吾妻橋でやたらと人が多いので気づく、花見シーズン到来だ。
 役所前のコースは人が多いので浅草側を走るが、吾妻橋は
 人が多いので走れない。歩いているて渡る。
 しばらく登って人がいなくなった。
 そして我慢と無理の区別がつかないまま、水神大橋で折り返して、
 白鬚橋からラストをかけるがかけられずフィニッシュ。
* <2016-04-02 土> R8.0 W2.0
 前回と同じだが桜が満開となって人が多くて走れないだろう。
 案の定、吾妻橋は日本全国、いやアジア、いやヨーロッパ、いや南米もか
 そのような人々が集まって、日本観光という、すでに私にはそれがどういうものか
 わからなくなっている集いの中に紛れ込んでしまった。
 調子は悪からここでwalkで休もう。
 人混みをぬけて台東区側を白鬚橋まで登る。
 今日は辛いので白髭橋渡っていつものフィニッシュへ８kmでおしまいだ。
* <2016-04-16 Sat> R14.0 W2.0
 先週は、やる気とタイミングが邪魔をされて、走らなかった。
 走らないことのつけが大きいことはわかっているが。
 それにもましてやる気がでなかった。
 4/14 は熊本地震があった、１０過ぎに姪っ子からなんで電話したかわかる？
 と電話してきた。いつもの気まぐれと思っていたが、
 そうじゃなかった、熊本しかも姪っ子の住んでる町が地震を襲っていた。
 やばい、家族の安否をすぐに確認したが家の中は冷蔵庫が飛び出したり、
 家具から皿が零れ落ちたりと悲惨だが、全員無事だった。
 隣のおばちゃんも無事だ。
 この日避難すべきか親は迷った。でも子供が避難すると言って聞かなかった。
 結果、本震から逃れることになった。
 それでめちゃくちゃになった姪っ子の故郷は全国区の被災地と一夜にして有名になった。
 本震から逃れて３日福岡に避難したものの自分たちだけ助かるなんてという思いと
 最後まで諦めまいと思う複雑な気持ちからまた益城町に戻って行った。
 今もそこで避難している。
 私にできるのは復興を思ってランニングするだけ。
 今日もきつかったが、今ここでの最長コースを走った。
* <2016-04-23 Sat> R4 W2.0
 体調崩してどうにもこうもならん。
 熊本のように体が揺れている。
 隅田川テラスの台東区側は全て工事が終わったようだ。
 だから厩橋を渡って、神田川の下流口までそれから戻、蔵前橋、厩橋、
 駒形橋、そして吾妻橋。もう吾妻橋も潜ることができる。
 歓びいさんだがどうだろう。相変わらずの人で、歩きになる。
 隅田区側に渡って、どうしようか迷ったが。
 やめた、帰りのクールも気分が悪い。
* <2016-04-24 Sun> R15.0 W2.0 復興と快復へのランニング
 昨日調子悪くて今週はこれで終わりと思ったけど、気が済まないので。
 １４時、ホークスの試合も見たかったけど、録画して、開始。
 いつもの厩橋を渡って、台東区側を下る、神田川まで、ここにきたのは
 何ヶ月ぶりだろう。折り返して、また厩橋を渡って隅田川を両国インター下まで
 総武線の下はスロープになっているからすんなりテラスにでる。
 行き止まりにある石を回って、吾妻橋を目指す、今日は快調だ。
 吾妻橋にもスロープがある。
 これでうんこのビル前の交差点で観光客の人種を伺う、西洋とアジアと中東と南米、
 興味を引くのは日本人か韓国人か中国人を区別だ。このゲームの答は聞くまでもないが
 だいたいわかる。
 後で距離ソクで見たら吾妻橋で6.6km白鬚橋9kmこの間重い内臓苦悩が走るが我慢。
 白髭を超えると足がたまらんと言ってきた。
 歩きを入れてストレッチ、水神大橋渡って、汐入大橋にきたら、腰が入ってきた。
 骨盤の傾斜がうまくいくようになってスピードが出せる。
 折り返しでストレッチするより、そのまま走る方がいいと判断。
 途中苦しくなるがすぐ快復したので最後は３分にあげて１５km終了。
 ただ、このところ左の踵が痛い。
 なぜだろう。靴はほとんどすり減っていない。
 blogは便利、今のゲルカヤノを買ったのが15/5/1。
 500km-700kmが目安だそうな。一月50km確かに寿命か。
 ところで、熊本の地震は姪っ子が被災者となって今も避難しているから
 なんかを支援してやりたい。
 だけど、義援金などとはどうしても偽善金と読んでしまいそうだし、
 無責任のエイリアスと忘却の淵がみえ隠れする。
 だから、浦安でやっていたようにランニングしながら復興を祈ろうと思う。
 病に倒れた人も必ず立ち直ってと祈ろうと思う。
 今日のホークスの試合見るの諦めていたけど最終回の攻撃に間に合った。
 ５：５同点か、柳田倒れたあと４番内川、見事ホームランでさよならだー。

* <2016-04-26 Tue>
 去年の終わりに、macを買った。
 買い換えたんじゃなくて新しいハイスペックがマシンが必要になっただけ、
 apple のクソGUIを使いたいとかおもったわけじゃない。
 このくそ、
 したが変換しない。
 下と最初のスペースキーでしたを変換しないだ。
 下、この下は変換した。
 下。したとは下で変換した。
 下、もういっぱつで下を下と変換するが。
 したを一回目のスペースキーで変換しないのだ。
 下、下。もう変換する。このくそ。
 これ,おれのemacs だけじゃなくサファリでもおこるぜ。
 したやろうしね。
 さふぁりのさいしょのぐーぐるのてきすとに、した、とうって、
 すぺーす、うってもしたのままじゃ。
 sita yaro,sine.

* <2016-05-01 日 13:04> R7.0 W2.0 
  金曜日飲みすぎて翌日走れない。それが今日は翌々日も走れないということで終わった。
  フィニッシュは吾妻橋。
  両国からここまで５００m程がオフに変わる。固められているから雨でもそう苦にはならないが
  散歩の人も多いのでここでスパートはかけられない。
  リセットかけれずおしましい。
* <2016-05-02 月 18:04> R10.0 W2.0 　
  GWに関東にいるのはおそらく2005年以来だ。
  2004年の夏頃から忙しくその年の正月は元旦のみ休んだだけだった。
  そのままGWも帰っていないはずだ。
  それ以来のごたごただが続いているが、ランニングはリセット効果があるので欠かせない。
  昨日のリベンジでbuild upもかけてフィニッシュ。
* <2016-05-05 木 12:04> R10.0 W2.0 　
  2日に同じコースでフィニッシュ。かなりかけれたと思う。
* <2016-05-05 木 19:10> おいれのmac book pro はくそなんや
  やっとわかった、俺のMac book pro 13がクソな訳。
  親指がかすかにタッチパッドに触れてそこでemacs やeclipse のエディタが反応して、
  薄いブルーの選択やプルwindowなんかがでてしまって入力妨害しているのだ。
  当たっていないと思っているが当たっているっぽい。
  タッチパッドの淵に両面テープのスポンジを何枚も重ねて貼って親指があたらないようにしたら
  現象がでない。
  2010年に買ったエアーではこれほどの現象がでていないので、タッチバッドの余計な進化と
  思ってしまっていたが、測ってみたよ。
  このクソ野郎。
  スペースバーの下からタッチパネルの上部までMac book air が16mm
  pro が12mmじゃねーか。
  この4mmが余計な入力妨害してやがったんだ。
  親指にバンドエイド貼るとか軍手のおや指だけはめるとか考えたけど、両面テープを
  タッチパッドの上部に貼ったら問題なく打てるよ。
  蓋もしまるしね。
  この情けないmac 早く手放したい。
  airより３００gしか重くないのだけんど、重すぎて使いにくいんだよ。
  タッチパッドがセメーヨ。
  この憤りどうしたらいいんだよ。
  proとairこんなちがいがあるのって普通気がつくか。
  airとは、4mmなんか。

* <2016-05-14 土 15:38> R10.0 W2.0
  同じコース。
  まあまあかけれたと思う。

* <2016-05-22 日 13:30> R8.5 W0.5
  同じコース。
  前にも書いたがランニング中に死ぬと身元不明死体となって無縁仏になる。
  それは家族に不幸なので健康保険証を携帯と鍵と一緒に腕つけバックに
  いれて走っていた、気がついたときだけだが。
  今日はたまたまランニング中に連絡が入る可能性があるので
  ５kmとかでチェックのため携帯だしたら落としたらしい。
  それを気づいたのが吾妻橋７km。
  やばいと思って引き返したらやっぱり落としていた。
  だれかが拾って堤防傍に避けていてくれた。
  ありがとう。
  ということで１０km断念。

* <2016-05-28 土 12:30> R10.0 W2.0
  同じコース。
  保険証はまた落とすのでバックを工夫する必要があるが、
  工夫の方法思いつかず持っていない。
  酒はそんなに飲んでいないがやけに苦しい。
  白髭橋の折り返しでボロボロ、ラスト１kmですこしあげて
  おしまい。

* <2016-06-04 土 16:30> R7.0 W2.0
  同じコース。
  海風が強くて登りでも後ろから風が服と思ったけど。
  それほどでも無い。
  暑いじめじめの嫌な季節がはじまった。
  それで吾妻橋で諦めた。

* <2016-06-11 土 14:21> 茶臼岳（那須岳）他２座登山計画
 + 茶臼岳(那須岳)(1日目）（7.5km)
   - 東北新幹線東京駅０６：４０発（やまびこ203号）
   - 上野駅０６：４５発（やまびこ203号）
     ＊次は上野07:50やまびこ２０５しかない
     ＊上野07:18やまびこ１２３で宇都宮から黒磯駅でも間に合うかも
   - 那須塩原駅０７：５０着
   - 那須ロープウェイ行きバス０８：０５発
     土日8:05 8:35 9:10 9:55 10:40 11:40
   - 那須ロープウェイ山麓駅０９：２０着
     通常８：３０～１６：３０（上り最終は１６：００、下り最終は１６：２０）
     ＊帰りはロープウェイ使わず。
   - 那須ロープウェイ山頂駅まで５分（２０分間隔）（１６８４m）
   - 牛ヶ首山頂分岐（５分）
   - 山頂口（３５分）
   - 那須岳（１０分）（１９１５m）
   - 山頂口（１０分）
   - お釜口（）
   - 硫黄鉱山跡（２０分）（１７４２m）
   - 無間地獄（１５分）（１７５０）
   - 牛ヶ首（１０分）
   - 姥ヶ平（１５分）（１５９４m）
     昼食３０分
   - ひょうたん池（往復２０分）
   - 沼原・三斗小屋温泉分岐（２５分）
   - 沼原分岐（５０分）
     樹林帯（虫多い）
   - 三斗小屋温泉（２０分）（１４６５m）
     １５：３０までチェックイン（煙草屋旅館：０９０－８５８９－２０４８）
     １６：３０夕食、消灯２１：００（自家発電）
     日の入１９：００/日の出４：２０
     洗面道具必須、ヘッドランプ必須、昼弁当注文済み５００円
 + 朝日岳、三本槍岳(２日目）(10.0km)
   - 三斗小屋温泉(煙草屋旅館)７：００出発（１４６５m）
   - 隠居倉（８０分）（１７５９m）
     休憩
   - 熊見曽根（６０分）（１８８２m）
     休憩
   - １９００峰（５分）
   - 清水平（２５分）
   - 北温泉分岐（１０分）（１８５６m）
   - 三本槍岳（３５分）（１９１６m）     休憩
   - 北温泉分岐（２０分）
   - 清水平（１０分） 
   - １９００峰（２０分）    
   - 熊見曽根（５分）
   - 朝日の肩（１５分）
   - 朝日岳（１０分）（１８９６m）     昼食（弁当）
   - 朝日の肩（１０分）
   - 恵比寿大黒（１５分）（１７４２m）
   - 峰の茶屋跡避難小屋（１５分）
   - 中の茶屋跡（２５分）（１６１０m）
   - 登山指導書・登山ポスト（１５分）（１４８９m）
   - 峠の茶屋駐車場（１０分）
   - 那須ロープウェイ山麓駅（１０分）（１３９０m）
   - 那須塩原駅行きバス
     土日12:10 13:10 14:10 15:30発
   - 那須湯本温泉バス停（２５分）
     鹿の湯５００円
   - 那須湯本温泉バス停
     那須塩原駅行きバス
     土日13:50 14:50 15:55 16:50 17:15 17:55 18:50 19:50
   - 那須塩原駅（５０分）
     東北新幹線下
     毎日16:02 16:49 17:02 18:02 19:02 19:29

* <2016-06-12 日 18:09> R4.0 W1.0
  土曜日走りそびれ、日曜日もそびれかかった１６：３０分。
  ホークスが巨人の豚どもに三連勝して気分がよかったが、
  走りは冴えない。海からの湿った風がうっとしい。
  神田川河口を目指す時、隅田川の水上バスの格好いいのが追い抜いていく。
  それとともに隅田川の泥の匂いが漂う、風が増して遠くから匂いを運んでくる。
  いままで慣れたつもりでいても吐き気がするわ。
  おそらく隅田川の水上バスや屋形船の移動スピードは１３kmぐらいだから、
  調子が良ければ競えるだろう。
  だけどそんな気は湧いた泥の匂いに隠れて湧いてこない。
  精神的になにかおかしいわけじゃ無いがもうやめる。
  両国橋へ向かうスロープ前でやめた。
* <2016-06-19 日> R12 W2.0
  今日は、20161103、ずいぶんとブログを書いていなかった。
  mac book pro に移行してemacs が書きづらく、
  pc開くのが億劫になったというのが最たる理由だろう。
* <2016-06-25 土> 茶臼岳（那須岳）他２座登山
  予定通りしっぱーつ。
  相棒は新幹線に乗り遅れて、宇都宮で降りて、黒磯駅だそうだ。
  黒磯から那須塩原まで７分という記事があったが実際１時間。
  踏んだり蹴ったりの男はほっといて初の単独登頂を狙う。
  だが、ガスでなんにも見えなっす。
  見所もないというか今思い返してもあまり記憶がない。
  それで人に会うこともなく那須岳登頂して、宿への獣道
  のような林道を這うように歩いて到着。
  タバコ屋旅館。
  これが今日の宿の名前、なんと電気がきていません。
  事前情報では、昭和５８年に宿の主人が息子に殺されている。
  やったー。
  このブログ初めての探偵物語の幕開けとなる。
  案内されたのは２階の６畳ほどの廊下とは障子、隣部屋とは襖でしきられている部屋だ。
  部屋は同一の構造で６部屋か、一部屋は４人は泊まれる。
  よく水戸黄門にでてくる旅籠のつくりだ。
  今の主人の優れたDIYの技術でお縁に衣類干しが設置してある。
  私はすでに探偵になっていたから早速現場がどこか探したくなっていた。
  タバコ屋旅館は主人の母屋と客間の二家構造でそれを山道の上を廊下でつないでいる。
  山道の横は小さな川になっているが生活排水を流している。
  客間の２階は中２階があってここにトイレと洗面所がある。
  おそらく以前1階は土産物などを売っていたと思われる古い商店の様子
  があるが現在は物置のようだ。
  私は当時のわずかな記事を思い出した。
  それによると主人は客間で寝ているところを後に責任を問えず不起訴になる息子に
  頭を殴られ布団に寝た状態で泊まり客に発見されている。
  客は救助ヘリを要請して病院に運ぶがすでに絶命していたらしい。
  私は、２階の部屋に案内されているとき階段を登った横にある４畳半の部屋が気になっていた。
  おそらく寝ていたとされるのはこの部屋だ。
  この部屋は他の部屋と違ってドアも窓も開いたままだったからだ。
  年月はたっても電気のない静かな掃除は嫌なものに違いない。
  通気もあるがこの部屋は中がみえるようにして置かなければならない心理が働く。
  さっそく入ってみた。１畳の押入れと一つある小窓からは裏の庭が見える。
  虫が窓枠は張っていた。羽アリだ。
  よしわかった。主人はこの部屋で血だらけのふとんに横たわっていたのだ。
  中２階は、トイレがあるその横を通って母屋への廊下を渡るのだが、トイレは
  通り抜けて１階への階段への間口から１階の物置が見える。
  1階への階段は１０段もない。
  ふと横の壁を見ると土壁が剥げ落ちている。
  私はその剥がれた壁に奇妙な黒いシミを見つける。
  血痕だ。やしわかった。主人はここで殴られて血吹雪あげて一階に転げ落ちて
  絶命したんだ。
  だが謎は深まる。
  客はどうやって救助ヘリを呼んだんだろう。
  現在この旅館は衛星電話のみの連絡しかできない。
  なぜ血痕は漆喰で隠されたのだろう。
  なぜ記録では就寝中ふとんの中で殺されたとなっているんだろう。
  
  探偵としての成果もあがって、山行きの疲れを癒しに、秘湯中の秘湯三斗温泉の自慢の露天風呂にいく。 
  渡り廊下を渡り宿の主人が迎え入れてくれた玄関脇をとって、
  そとの廊下をとおり、山の斜面を登るとすぐに手作りと湯船があった。
  ここは時間帯により女湯と男湯、混浴もあるらしい。
  粗末な脱衣所は女には無理だろうと思うが内湯があるので女はそっちを使うのだろう。
  私は温泉に入って気持ちがいいとは思ったことがない人間である。
  だがこの温泉は違う。前方には開けた景色現れそれを辿っていくと遠くにある山々の雄大な山頂と
  稜線が見えるのだ。
  山を登らなければたどり着けず、たどり着いたものだけが癒しの温泉に入ることができる。
  露天風呂からの景色は再びの山行きの計画の源力をもらうことができるのだ。

  どのくらいこの湯に使っていたかしれないが、部屋にもどるとき廊下の下に遅れてやってきた
  相棒が到着した。この山行きは途中迷うことが予想されるため緻密に計画を書いたのだが、
  最初の一歩でつまずいたこの男は後に災難にあうことになる。
* <2016-07-03 日> R6.0 W0.0
  いつものコース、厩橋から対岸に渡って、スロープを降りて神田川の始まりにでて
  また戻って、総武線の下のスロープを降りてテラスにでて両国インターの
  したで折り返して、スタート位置あたりでキツくなってやめた。
* <2016-07-10 日> R5.0 W1.0
  いつものコース、厩橋から対岸に渡って、スロープを降りて神田川の始まりにでて
  また戻って、総武線の下のスロープを降りてテラスにでて両国インターの
  したで折り返して、キツくなってやめた。
* <2016-07-16 土> R21.0 W3.0
  第二回網走マラソンのエントリー締め切りをてっきり7月中と思い込んでいた。
  昨日それが6月中と気づいてエントリーできない。
  無性に悔しくてたまらなかった。
  それだから思いつきでハーフ走ることにした。
  隅田川テラスの21kmコース。
  途中白鬚橋と吾妻橋の信号２箇所で３回のストップだけ走れるコース。
  厩橋から対岸の浅草橋側に渡って神田川折り返して、そのまま、吾妻橋の
  トンネルくぐって、白鬚橋手前まででまた折り返して、厩橋をくぐって
  急転スロープを登って厩橋渡って、高架下を南下、両国インター折り返して、
  両国側テラスを吾妻橋手前でスロープで吾妻橋信号待ち。
  ストレッチチャンス。
  ハイドロチャンス。
  そして、高架下を道沿いに言問橋くぐって、X橋の桜橋を通りすぎて、
  白鬚橋に突き当たって渡り、２回目の信号待ち、ここはストレッチやりにくい。
  渡って土手ここはこのコースというか隅田川沿いでは一番気持ちのいいところ。
  そんで水神大橋をくぐるためテラスに降りてそのまま上流へ、なんとか橋くぐって
  また土手に上がって南千住で折り返して、桜橋の手前、浮浪者宅すぎでゴール。
* <2016-07-31 日> R9.0 W4.0  
  前に住んでいた花見川のコース走りたくなったんで行ってきた。
  総武線で新倹見川まで行って、前に住んでいた、２度とお世話にならない
  と決めた、レオパレスのかつてのくそアパートをみてそこからコースを再現する。
  私のランニングの始まりつまりこのブログの始まりもここから。
  私のランニングコースは、花見川、浦安、宗像、隅田川とホームコースは
  ４つになったんですね。
  ４つのコースで快適さでは一番の花見川。
  なぜならランナーはわがまま。
  冬は日向を夏は日陰を朝でも夕方でも自由な時間に走りたい。
  と思う。
  時間は食事から経過時間も重要だからなおさら自由に選択したい。
  それが許されるコース。
  なぜなら花見川は両岸を走れるのと周りは緑が多いため日差し朝夕で逆転され
  こっちでは日向対岸では日陰というのが作られるからなのだ。
  山の間を流れる川の両岸が走れるところがあればこの偶然の恩恵にあうのだが、
  ここしか私はまだ会えていない。
  
  コースはなんにも変わりはない。
  ただ、私の走破能力は上がったのだろう。
  かつてのアパートから出発して上流に向かういつものコースは短いと感じたから。
  もうここは走らないでいいだろう。

* <2016-08-20 土> R7.0 W1.0 
  前半は福岡に帰っていた。
  福岡で走る気だったが、暑さで走る気がなくなった。
  それに益城町にいってきた、復興は程遠く。
  災難は他人事とかし、諦めが漂っていた。
  こころの憤りは計り知れない。
* <2016-08-28 日> R7.0 W1.0   
  8月は１４kmしかはしれていない。
  あと気持ちが変わった。
  隅田川テラスを走り続けてヘドロの匂いが吐き気を催していたのですが、
  それだから近くにできたスポーツジムの広告が気になっていて、
  一月８千くらいならジムの方がいいなって思い出していたんですが、
  ヘドロの匂いかいで思った。
  これがランニングなんだと。
  今この自然のいや不自然なものいや自然なことと向き合い挑むのが
  ランニングなんだ。
  暑さも寒さも匂いも廃棄ガスもやかましい総武線の音もすべて受け入れて
  ランニングしよう。
  それがランニングだ。
* <2016-09-05 月> R4.5 W2.0   
  先週ランニングできなかったので平日夜走ろうとした。
  でも中途半端に終わった。
* <2016-09-10 土> R10.0 W10.0   
  三鷹の上連雀に２０代の時数年住んでいた。
  小説家でだれのを一番読んだかと言われれば太宰だ。
  中学高校での話だ。
  太宰の墓は三鷹にある、２０代の時にはすでに太宰なんて稚拙なものより、
  三島に傾倒していたから別に取り立てて行きたい気持ちはなかったが、
  太宰の墓を見に行った、コケた小さな石の墓は入水自殺した女も横にあった。
  その横には森林太郎の大きな墓がある。
  それはもう３０年以上も前の話、今回、小金井公園を走るために
  中央線に乗ったが三鷹で降りて昔を懐古してみたくなった。
  養ったランニングの機動力は20代で長く感じた駅からの道をとても近くに
  していた。
  太宰の墓の寺は今では大きな斎場となって金を稼いでいるようだ。
  その斎場奥から入ると裏に墓地が広がる、ボランティアの墓掃除が何人も
  死の恐怖に向き合っていた。
  太宰の墓はどこかと尋ねるとあの桜の木のあたりだという。
  驚いた、３０年前とまったく位置が逆。
  記憶が違う可能性もあるがおそらく墓を変えている。
  ３０年前は少し小高い山の上という印象がある。
  もうひとつ驚いたのは墓が増えているということ。
  そりゃそうさ、年月が経てば人が死ぬ。
  さてこんなどうでもよい寄り道をして、前住んでいたとこ、友達の家
  なんかの所在を確かめながら走って、武蔵境、小金井ときて、
  目的の小金井公園についた。
  だがここを走る余力はなくなっていた。
  ストレッチを十分して帰ることにベンチを利用してやっていると、
  前方にカップルがストレッチやっているかなりの強者ぽいが
  互いに向き合い完璧に呼吸を合わせてストレッチしている。
  なんという気持ち悪さ。速さが気持ち悪い。
* <2016-09-17 土> R7.0 W2.0
  3連休の初日急にやるきがなくなって吾妻橋で終わる。
* <2016-09-19 月> R10.0 W2.0
  戸田市彩湖マラソンハーフにエントリーしたのは9/7。
  戸田には１時間かからずつくのが気に入った。
  だから頑張ろう。
  build upできたと思います。
* <2016-09-25 日> R10.0 W2.0
  隅田川を走り出して、ランナーズハイにはなったことがない。
  テラスは石畳ありクレーあり段差ありだからならないと思ったが
  8km付近できた。
  前方にカップルが走っていてそれをじわじわと追っていると
  抜く直前にきた。
  すーっとして、もしかしたら息もしなくていいような楽な感じ、
  だけど、すぐに折り返してラストスパートだから、折り返した、
  瞬間にスピードあげてランナーズハイを打ち消して、
  浮浪者宅すぎてゴール。
* <2016-10-02 日> R10.0 W2.0  
  build upできたと思います。
* <2016-10-08 土> R10.0 W2.0
  途中から大雨に変わった引き返そうとしたが、体が気持ちいいので
  そのまま走り通した。
  build upできたと思います。
  いつものようにクールで厩橋にくるとスクータのおっさんが話しかけてきた。
  ずぶぬれの私をみて共感の念がそうさせたらしい。
  俺も雨の中走ってんだよ。
  ちょうど冷えていいよな。
  このおっさんはどうも南千住の土手あたりを走っているらしい。
  たぶんすれ違っているだろう。
  あったら声かけるよ。
  たぶん私あってもわからない。
* <2016-10-15 土> R10.0 W2.0
  build upできたと思います。
  帰りに喉が痛いのをしった、風邪と気づかずケアしなくて、
  次の日休んで医者に行って、薬飲んで、完治に１０日かかる。
  医者の薬は、長く飲むとだめだとわかってきた。
* <2016-10-30 日> R10.0 W2.0
  天気は曇りいつものコース。
  5kmすぎからあげて最後は少しバテた。
  平日はアルコール中毒、週末は脳内モルヒネ中毒、果たして
  この行為は健康にいいのか。
  この行為はもしかしたら体にはいいのかも知れないが、脳には
  わるいかもしれない。
  脳の記憶が悪くなって久しいがこれのせいかもしれない。

  ところで走り終わってシャワーして、目白にスキーを買いに行った。
  というか目当ての新モデルの板と靴を注文して内金をいれてきた。
  このブログに新しいカテゴリを追加しなくてはならない。
  それは、テレマークスキーだ。

* <2016-11-06 日> R14.0 w4.0
  昨日走るつもりでいたが酒による体調不良で今日に順延していた。
  大会まで２Wだからもうハーフでも入れないといけない。
  足の指にワセリンを塗って、いつハーフを走りたくなっても
  対応できるように準備して望んだ１０時。
  昨日酒を飲んでないから結構いい感じ、いつものコースで始まり、
  南千住の折り返しからいつもの浮浪者宅過ぎでゴールの15kmに決めた。
  実はワコールのタイツCW-Xを買って３回目の試走だった。
  もちろん大会に合わせて買ったのだが最初からの印象で膝の内側のしめ
  感が違和感だった。当たっている感じが疲れがたまる感がしている。
  今回始めての10kmオーバだが、その違和感が距離とともに増幅してくるのが
  わかる。もうひとつ腰のゴムがキツイ、このしめのせいで腰の横の筋肉に
  疲労感がまた同じように距離を稼ぐたび増大する。
  CW-Xの中でもしめつけが一番軽いものを選んだのだが、残念。
  このタイツもくそになった。18000もしたのにだめだ。
  大会はいままで履いていたサポートのないものにする。
  今日の走りは、南千住の折り返しまでは、まあまあ、ラスト１kmで
  アップできれば15kmでも十分だと思っていたのだが、13.5に小さな川が隅田川
  土手を切って流れ込んでいるので上に橋があるこの橋にかかった時
  揺れを感じるそしてパニックを誘発。
  橋を歩きに変えて乗り切りスタートするが14kmで揺れが起こって、
  無理せず終了。

* <2016-11-13 日> R12.0 w2.0
  大会まで10日を切った昨日相変わらず酒で具合がわるい。
  二日酔いを風邪の症状と混同して、葛根湯を飲んでしまった。
  翌日の今日、風邪じゃなかったんでラッキーと思って１０時前開始。
  10kmか15kmか悩んだが、12kmでスパートしよう。
  おそらくシーズン最高の天気と気温と湿度だっただろう。
  快調にフィニッシュまで持ち込んで終了。
  脳内モルヒネ３０分かけて味わい帰宅。
  これで木曜日の夜に５km、土曜日に３kmとウオークで仕上げます。
  今日で過去ブログに追いついた。
* <2016-11-16 水> R5.0 W1.0
  仕事を１８時で切り上げて今週の大会のための準備
  中２日でのランニング。
  ヘッドラップをして普通のズボンに長袖シャツで走った。
  夜だから速いかと思うが錯覚だろうか。
  かなりあげて、なんなくフィニッシュ。
  
* <2016-11-19 土> R5.0 W1.0
  今日は雨体重は、果物中心で63kg代まで下げっていたが、最後に
  スタミナを付けるため、魚と炭水化物から高タンパクのチーズ
  バナナ中心の果物をプラス、パスタを当日朝７時に食べて臨もうと思う。
  しかし昨日早く寝すぎって起きたのが１時。いかん。
  寝よう。
* <2016-11-20 日> 戸田彩湖マラソン2時間９分３０秒
  今年はじめての大会。こんなに近くでやっていたなら去年も
  でたはずだ。
  両国8時、秋葉原で京浜東北で赤羽、赤羽でから北戸田駅まで
  ５０分だ。駅に着くと送迎バスの並びをスタップが誘導していた。
  運良く真後ろでカット。バスの入り口でコースを確認１５分で
  公園の入り口前のバスセンタに到着。
  ここから土手を超えて、彩湖と彩湖の周辺の広場が見える。
  更衣室はずっと向こうだ。
  今回は１１時スタートだからいつもの大会と比べると遅い時間だ

  今、霧がはって雨になるのかと思うほど冷えているが、これに
  だまさず、半袖で行くところに決定。
  それにしても小さなテントにギュウギュウの更衣室。
  狭いよ。ちゃんとストレッチできない。
  ゼッケンをつけて外にでると荷物を預けるのに５００円とるらしい。
  普通申し込み料金に入っているはずなんだが、だいたい、
  その金を引っ張りだしたりするのが大半なんだよ。
  ストレッチを始めたいが良いところがない、芝は濡れていてできない。
  なんとか小さな舗装の小道を見つけて行う。
  寒い、先ほどコースの看板を見たけど、やっぱり周回だった。
  この大会２km、５km、１０km、ハーフの欲張り大会だ。
  おまけにトイレは出発時間に近いところを狙ってすませとしたが、
  なんと１０kmのリターン組がゴールのトラックに入ってきて、
  スタートラインに並ばせないように続いている。
  なんというお粗末な設計か。
  欲張っていろいろ距離の大会やったもんだからこんなことが起こる。
  これでスタートラインに並べなかったらどうすんだ。
  なんとか１０kmの戻りの列は途切れ始めた。
  １００名以上がその大井川の難所で足止めを食らったようだが、
  私の後ろはどうなったか知らない。
  もうギュウギュウだがベストポジションを探す。
  2:10分、2:00まだまだとこのあたりとならんだが、
  あれスタートの垂れ幕の１０mあとだよ。
  こんなに速いところじゃ。。。
  ３分前。
  しかたなくこの波にのることにした、速い、２kmで気づいた、完全
  ５分切るスピード、早すぎるよう。
  徐々に落として、体力を回復したいが、うまくいかないまま５kmの給水
  水じゃんか、ポカリじゃないのか、
  私は練習は水だが大会はポカリの方が味があるので口で噛むようにのめるので
  よく入るきがするからいいと思っている。
  どうも水の次はポカリらし、だが８kmにみかんがあった、ここは周回だから、
  もう一回くる、最初の一周のラストに入る前にみかん、一口もらう。
  すっぺ、喉をツマラして、はらたつ。
  すでに２kmで記録更新を諦めた感があり、８kmでもリタイアしたくなって、
  スタートまで戻った。
  やめるか、いややめない。
  何故やめない。それはこの先１時間ちょっとの我慢ですむものが一生の後悔
  に変わるからだ。
  それだけのために走る。
  すこし、走りがましになった。
  だが１２kmで左の中指の感覚がなくなった。
  抜かれながら走る。
  ここのコースは初めてなので、目標物がわからない。
  ただ、ずうっと続く林の曲線が傾く向こうが折り返しと思う。
  それを目指す、帰路数はいつも思うが１０kmのものと区別がつきにくい。
  １１時開始という異例の遅いスタートなので気温差がくるのはわかっていた。
  やっぱり、かなり暑い、ポカリは３杯のんだ。
  のこり３kmでくるのはみかんさっきは左で食べたんで、今度は右側で２個たべた。
  うまい。だがのこり３km頑張るのにみかんかよ。
  そして橋を渡る、ゴールとは反対の折り返しまでいき、そこから彩湖沿いのコース
  から外れてトラックに入る、トラックは３・４週もうゴールはできる。
  後悔よさようならこれでお前には苛まれることはないだろう。
　１０km５４：３８だった。これは去年の１０kmタイムトライアルに８秒にせまる
　ものだった、すべてこれが敗因だ。
  この大会の懸賞は、手袋となんかのサプリ１畳、それとコーンスープ一杯。
  せこいな。
  帰りバスから北戸田駅へ、１番乗り場を普通に目指すと、階段１２６段のぼりが
  まつ最後まですばらしい、運動促進の待ちだったな。
  次は１０kmでここの大会さがすよ。
  
* <2016-11-26 土> R10.0 W2.0
  この日もいつものコース。
  ただ、左足の踵からその側への筋に妙な痛みが走っている。
  痛みが擦れている感じもするのでそのまま１km走る。
  すると不思議。綺麗に消え去った。
  むしろ痛みがとれて気持ちがいい。
  気温上がっているがこのところ海風は吹かない。
  山風は気持ちい。
  ヘドロは気にならない。
  ５kmでから６分を切り出して５分前半で７kmまで
  吾妻橋の信号待ちから立ち上がりまではいつもコースが
  くねるのと人が多いのとアップダウンがあるので、
  ペースが落ち着かない、桜橋５００m前になると落ち着く、
  ここから５分を切り出す、白鬚橋で４分後半、折り返して、
  ３分台にあげてフィニッシュ。
  だがこの時期のクールは寒い。
  テラスを利用して帰っていると、隅田川を登るシットインカヌーで両パドル
  のやつがいた。プレジャーボートとジェットスキーのバカも多いがこういう
  バカもいるもんだと思った。
  自分でもやりたかったことだが。

* <2016-12-03 土> R10.0 W2.0
  今日は朝１１時スタート。
  風はほとんどなし。
  いつものコース。
  ３分台まであげてフィニッシュ。
  帰りは一般道。もう日向をあるかないと寒い。
  飯がこまっている。
  肉、牛肉と豚肉だけだがこれを食わないようにしてもう一月か。
  いつもなら筋肉壊れているから横綱ハンバーグでもいいかと
  安易にしてしまうがそれができない。
  水を５００ml補給したが今日のランだけで１．５kg以上落ちた。
  それほど汗はだしていなかったのに。
  
* <2016-12-04 日> 三斗温泉殺人事件
  ここに金子金吾という一風変わった４０代半ばの男がいる。
  住を墨田区本所の５０年もたった古かびアパートの２階にして、
  衣は山着を常としている。
  探偵業を生業としてあげてはいるものの仕事の依頼のないときは隅田川を挟んだ
  荒川区あたりのスーパーなどで荷下しなどのアルバイトをしている。
  妻子なく、寄り添う女もなく、日柄、ディスカバリーチャネルをみるか。
  散策しては、雲を眺める。
  ときおり、ジョギングして老いの確認と人生の虚しさなどを味わっている。
  
  ある朝の散歩をしていると信号待ちの鮮やかな着物を着た娘を見つけた。
  跳ねた帯の結び目がこの娘の粋と内なるものの気丈さを現しているように思えた。
  娘は持て余している旅行用のスーツケースを両手で押して信号を渡り駅の方に
  転がしていった。
  新手のアイドルの撮影でもあるのかとその姿の向こうを探すが、
  初夏の夏への勇み足ともいうべき蒸し暑さがそれ以上の好奇心を奪ってしまった。

  それから何週間たっただろうか。
  私は駅のロータリの横を通った時その娘がなにものかを知った。
  それはテキ屋の娘だった。
  彼女は、スーツケースに手作りのぬいぐるみを詰め込んでいたのである。
  腰掛けてうつむいて針を動かし何かを作っている。
  これが彼女の生きがいと人生の喜びなのだろう。
  
  並べられた相撲の人形のひとつをとって。
  金吾は、ためらいを咳払いで打ち消して言った。
  「これはあんさんの全部手作りですかい。」
  娘は、眉にすこし怪訝なシワをつくり首を持ち上げた。
  怪訝さは大きな目で金吾を直視した時は、失われて、
  その大きな黒目とはっきりした白目が今まで不愉快なものなど見たことが
  ないようなあどけない少女を見せて、
  話をするために作成中のものを止めて、それを覆い隠す白い手の動き、
  着物の襟からのぞく首筋と丸い小さい肩が成熟した女の色気を醸し出した。
  「そうですよ。お子さんにどうですか。」
  「そうさなぁ。おれっちには子供はいねーんだよ。」
  「じゃあ。彼女にどうですか。相撲女子はやってるんですよ。」
  「いや。おれっちが抱いてねよっかな。」
  「おもしろいね。お相撲すきなんですか。」
  「モンゴル人が嫌いなわけじゃないが。相撲の封建的なところがどうでもね。」
  「それより昔からここで商売してんのかい。」
  「おとうちゃんが会長しているからそれでお前も勉強しろって。」
  「親子２代ってわけかい。よし。このお相撲さん、おいらの事務所に飾っとくぜい」
  「ありがとう。なんの事務所やってんの」
  「てやんでぇい。探偵事務所だよ。」
  金吾は、薄汚れた名刺を娘に渡した。
  娘は、すこし物怖じしたがそれを受けっとって代金のお釣りを返した。
  金吾は、次の出店を探す素振りに入っていたが、それはこの娘に対する気持ちを
  隠すためだった。
  先ほど自分を見上げかける娘の映像がまぶたに焼き付いていた。
  すでに金吾の想像は、娘を白い裸体に剥いて、流れる首筋と斜めに刻まれた
  細い鎖骨の流線のくぼみの行方が目的の白い乳房の谷へ入り、そこに娘の鼻息が流れるのを
  感じてていた。
  金吾のやさぐれた手の手中には二つのやわらかいものがあって、そのきめ細やかな肌の
  感触をまぶたの裏に映していた。
  先ほどつり銭を受け取った時に触れた娘の指の腹の感触がその実現に一役かって
  金吾は、まだ想像発端を娘の腹から下半身へと映していった。
  金吾には他の出店は映らず自宅を兼ねている事務所の方向に向いていた。
  娘の尻を最たる目的の地の想像の端点にして、そこで地団駄を踏み、我へと帰ったとき、
  すでにアパートの入り口が正面に見えていた。
  まだ、初夏の１７時過ぎである。
  金吾はこの時より悪夢にうなされ続ける。
  奇怪な夢は娘の白い胸に刃をたてて殺し、返り血を浴びその罪を逃れるため娘の
  肉体を引き裂いでとある社の下に引きづり込み穴を堀埋めようとするが、
  穴が掘れずもがき苦しみ罪を重さから彼女の亡骸にしがみつくがそこに
  頭があり彼女の見開いた流血した目に睨まれながらめが覚めるというものだった。

  金吾は美しい娘に心を奪われたのは事実だったがそれは恋というものではなかった。

  初夏の清々しさがまだ残っていた季節はとうの前に終わり、真夏を迎えようとしていた。
  一人の女が金吾の事務所を尋ねた。
  娘は潔いような白いワンピースをまとって真夏の暑さに決して怯まぬ防備をしていた。
  それがあのテキ屋の娘だった。
  彼女は１通の手紙を携えていた。

  伝七捕物帳には赤っ鼻の親分がいる、銭形平次にみのわの親分がいるように
  金子金吾にもこれに匹敵するものがいる。
  この界隈の組の三下の三下で石原の半次というものがそれだった。
  石原の半次は金に困った時にあらわれてはバイトの情報などを拾ってくるなど
  便利な反面根っからの忘れっぽさからいろいろとトラブルを起こし、金吾を悩ましていた。
  この日金吾は役所事があって出かけているとき半次が事務所の番をしていた。
  アパートの安ドアのノックが３度響いた。
  半次が鼻ほじりながら
  「金吾さんですかい、鍵あいてますぜ。」
  「いいえ、ここ金子さんの事務所ですよね。」
  ドア越しに女の霞むような声がした。
  半畳ほどの玄関があったが半次は靴を吐かずドアをドアを開けた。
  見下ろすように半次は言った。
  「ああ、どなたさまですかい。」
  「私は木戸といいます、金子さんに相談があってきたんですが。」
  「金吾さんは今役所に用事があっていってまして相談なら聞いておきますよ。」
  「あそうですか、それではまた伺います。」
  半次は引きとめようとしたが何かをこの時決心したような彼女の仕草に困惑して、
  そのままドアを閉めてしまった。
  半次は靴を履いてもう一度ドアを開けたが階段を駆けおりる音だけがしていた。

  金吾はそのことを半次から聞いたのは３日たった木曜日の夜だった。
  駅のロータリーで出店を探すが彼女はいなかった。
  他の出店に聞くとここ１週間ほど見ていないということだった。
  
  そしてまた１週間が過ぎたころ栃木県の那須のある神社から若い女のバラバラ死体
  が発見されたと報じられた。
  しかし、金吾にはその事件とテキ屋の娘に関係があるとは思いもしなかった。
  半次は金吾にこっぴどく怒られて頭にはきていたが、組のつてを使って、
  そのテキ屋の娘の住所と名前を突き止めていた。
  いきおい携帯で金吾にそのことを伝えたいた。
  そして直に金吾にメンツを保ったことを自慢しようと金吾のアパートを尋ねた
  が金吾はいなかった。

  そのころ金吾はすでに娘の家を尋ねていた。
  昔の商店のような一軒家であったが一枚の開きドアが開いて、
  母親という女と話していた。
  確かにあなたのところに行くと行っていたのですが、その後すぐに、私の実家で
  ある栃木県黒磯市の親戚の家に行ったとのことだった。
  黒磯は母親の叔父が引き継いでおり現在は従兄弟の家族がいるとのことだった。
  そして、母親から１通の手紙が差し出された。
  この手紙は金吾のところに行くと言って持って行ったが会えなかったため、
  母親の手元にもどっていたのだ。
  というより金吾に渡ることを承知で渡されたのだと金吾はあうんの呼吸のような
  信頼感を娘に感じた。
  この手紙は母親宛ての手紙であった。
  差出人はなく、次のような内容であった。
  『木戸葉子さま
  突然でありますが、このような手紙を差し出すにあたり、
  多分に失礼と思いますが、どうぞお許しください。
  内容はあなた様のご両親の名誉、否、家系の名誉にかかる話です。
  あなたのお父様は三斗温泉の宿を経営されておりましたが
  昭和５８年の事件でお亡くなりになり、あなたとお母様は黒磯を離れての
  暮らしをなされております。
  現在もその経営者は変わりましたが宿は存続しております。
  古い宿のため宿は傷み朽ちるところまで至っております。
  そこで、昭和５８年の事件は、古い記事の通りではなく、新たな事実
  が発覚しました。事件の被害者であるあなたのお父様は、別館の寝室
  で撲殺されたのではないのです、新たに壁に隠された血吹雪とも思われる
  ほどの血痕が発見されたのです。
  私は、この事件に関し独自の調査をしたところある大きな事実が隠されている
  ことに気がつきました。
  事件の際の泊まり客は１６人いましたがそのほとんどの素性がはっきりしておりません。
  私は、旅館のすぐ上の社に、当時の宿帳が隠されているを偶然見つけました。
  そこには、現在の皇族の名と証拠があったのです。
  その宿帳の泊まり客名簿から類推するに皇族の闇夜の遊び事が浮かび上がってくるのです。
  この手紙にはここまでしか書けませんが、私はあなたの家系と共にあるものです。
  私とともに我が家系の３０余年の長い屈辱と不名誉の歴史から解き放ちましょう。
  かしこ』

  金吾は、手紙を読み終えて、はじめて報道されたバラバラ死体を彷彿とした。
  母親に、
  「葉子さん、娘さんの名前はなんといいなさるですかい。」
  「夕美、木戸夕美と言います。携帯もずっと不通なんです。」
  金吾は母親に黒磯の住所と連絡先、夕美の連絡先を聞いて言った。
  「なーに。心配するこっちゃねーよ。この金吾が何とかしてやらーよ。」

  帰る道すがら金吾は半次を電話で捕まえて山道具を一式もってアパートに
  くるように指示した。

* <2016-12-10 土> R10.0 W2.0
  今日は９時からベランダの塗装の工事が入った。
  それというのも1月前くらいにベランダの手すりに焼け焦げたタバコの
  吸い殻があったのだ。
  上の階のバカが火のついた吸い殻をすてて、手すりに落ちてそのまま
  燃え尽きて、塗装を焦がしたのだ。
  よくもこんなとところに止まっていたなあ。
  管理会社に文句をいったら張り紙だして注意喚起して、
  修繕工事会社に連絡するというので、貴重な土日の休みに見積もり
  してもらって、今日の工事になったんだ。
  バカはどこでもいるが上の階にいるバカが特定できない。
  現行犯を捕まえるしかないのだ。
  しかし、こんなバカのせいでランニングの予定を変更するのは、
  自分の誇りにかけてできない。
  だから、工事は午前いっぱいかかるらしいが、そのまま彼らを残して
  終わったらそのまま出て行ってくれと言って、
  ランニングを開始した。
  今日も順調だった。
  完璧ほどのbuildup ができた。
  東京の１２月のこの気温とこの湿度おそらく最後は３分にあげることが
  できた。
  思った、もう週10kmは自分の中でイージーになっている。
  週１２kmか週１５kmを導入しようかなと思う。
  コースは去年のように工事で封鎖されているところはないので、
  気持ちよく走れる。
  それからダイエットもしていて、朝のすっきり時点で64kgになっている。
  あと、マリンマラソンのエントリー期限が12/5になっていた。
  たまたま月曜日にwebでみたらそうだった。
  Qちゃんが走るか不明だったんでやめようと思ったが、ゲストにQちゃんと
  小出監督のいつもの姿、やっぱり出ようと締め切り最後にエントリーした。
  
* <2016-12-18 日> R13.0 W2.0
    いつものコース。
    ただ今日は調子をみて15kmか13kmにする予定。
    温度湿度はともいい。
    両国インターの折り返しから５分後半にあげて
    水神大橋はまで５分を維持し折り返し後スパート
    を２度かける。
    ほとんど１度目で息が上がるがすぐに信号待ちに
    ひっかかるので信号を渡って、白鬚橋を渡って、
    ２度目のラストスパート３分まであげたいが
    上がりきらずフィニッシュ。
* <2016-12-25 日> R13.0 W2.0
    いつものコース。
    ほとんど先週とかわらない。
    体調もいい。
    先週より５分台を長くかけれているから
    だいぶよい。
    これが今年ラストになった。
 
* <2017-01-01 日> R13.0 W2.0
  年がかわったらしい。
  ここ両国では問屋やら運送会社やら職人の工場などが
  シャッタを閉めて、謹賀新年などと張り紙がしてあって、
  なにやら私の大好きなものの匂いが漂っている。
  車の交通量は少なく、人の往来も少なく、うきうきしてくる。
  いつも見飽きた景色をどうして、こうも遠方へと視線を
  あげたくなるのだろう。
  遠山を羨望の慄きをもって見上げるように。
  すべての建物に人気が少ないこと。
  路地からみる遠山を遮る無数の電線の無秩序な絵模様さえ
  美しい享楽を与えてくれる。
  それは廃墟だ。
  昨年の仕事の最終日。
  茶水のスクランブル交差点をいつものように渡っていると、
  幼い少女の手を引いた母親が急いで横切った。
  私は思った。
  幼い子に母親や父親の手が必要なように、
  私には、孤独が必要だったのだ。
  さて、そんなことを思って新年のランニングだ。
  いつものコースでいつものスタート。
  少し攻め方を早くしたせいか、８kmと１１kmで緩めたが
  それでも２段階フィニッシュは成功したと思う。

* <2017-01-03 火> R10.0 W2.0
  去年の１月は末に12km走っただけでした。
  一昨年の年末から風邪を引いて実家でも走れず、
  それでも無理してただ仕事をしていた。
  今年はもう２回も走ってきた。
  体重の記録を書いておく。
  現在朝起きトイレすませた状態で63.5kgまで下げている。
  2015/9/26の網走マラソン時の朝が67.5kg。
  私はいつのまにかランニングをするためにダイエットを
  行ういわばアスリートになっていたわけだ。
  今日のランニングスタート時は64.5kg。
  なかなかいい感じの減り具合だと思う。
  にもかかわらずこの前のハーフは2:09とは。
  書いてなかったから書いとくが1/22はマリンマラソン
  12/5がエントリー締め切り日だったがなんとその日
  にエントリーできたのだ。
  Qちゃんが走るか、走ると記述がないけど、Qちゃんと
  ハイタッチするためその日あわててエントリーした。
  おそらく最終日までエントリーできたのは近来はじめて
  なんだろう。
  いよいよマラソン大会淘汰の時代かというかもすでに
  起こってるけど。
  どうぞもっと起こってください。

* <2017-01-06 金> テレマークスキー
  夏山だけじゃなく冬山もやりたくなった。
  そんなこと考えていたらクロスカントリースキーを
  思いついた。だけどクロカンは滑りがだめだ。
  山を登れて滑れて走れて三拍子揃ったスキー。
  それがテレマークスキーだった。
  調べていくと洗練されたスキーがあることがわかった。
  ウロコ板＋３pinビンディング＋革靴これこそ私好みの
  「Simply the best」
  この選択をサポートしてくれるショップは神保町にはない。
  正確にはスキーシューズに革靴を想定していたのだが、
  置いているショップがなかった。
  そんな中、目白のカラファテというショップがあった。
  革靴の試し履きもできたんで迷わずプラスティックブーツに
  決めた。実はscott というイタリアのメーカーのブーツが
  革靴より柔らかかったのだ。
  革靴は所詮水を吸うし濡れるから雪山は辛そう。
  もしテント伯するなら乾かすことはまず不可能。
  凍える足先のことを考えたらまずその選択はない。
  軽い板=G3 STINGER 78 XCD 172cm(片足1.17kg)
  3pin ビンディング=ボレー(450gペア)
  ブーツ=scott エスカーション(1300g片足)
  これにストック、メンテ用ワックスを買ったら¥150000
  だからウエアまで回らず。レインウエアで代用して、
  そのカラファテに置いてあった、テレーマク塾パンフ
  をもらってきました。
  裏磐梯。
  20:20の新幹線で東京から郡山へ80分郡山から猪苗代40分
  へと乗り継いで迎えにきていた塾長の車で40分。
  2.5泊スキー合宿の始まりとテレマーク人生の始まりだ。
  
* <2017-01-07 土> テレマークターン
  テレマークスキーは、かかとが上がる、つまりヒールフリーという、
  もはや私には精神主義のようなインフラ上にある、スキー技術により
  成り立っている、それがテレマークターンだ。

  （はい、左から）
  左に曲がるときは左の足に体重をかけ膝を曲げる、その時
  かかとが自然に上がり、左のブーツのインナーの前方を左足の
  前方の筋肉で圧をかける。
  この時右足はおり曲がらずふくらはぎで右ブーツのインナーの
  後方に圧をかける。
  （伸びる）
  そしてターンする前に上体をあげる。
  （はい、右いー）
  右足も同様に、右足に体重をかけ膝を曲げる、その時
  かかとが自然に上がり、右のブーツのインナーの前方を右足の
  前方の筋肉で圧をかける。
  この時左足はおり曲がらずふくらはぎで左ブーツのインナーの
  後方に圧をかける。

  (はい、退け反らなーい）
  (はい、遠おーくをみてー）
  (はい、大きなクッションボール両手で持っている感じ）

  これでターンができる理由がわからなかったができても
  わからないけど楽しい。

  1日目にはちょっとだけターンができた。
  
  急なゲレンデはアルペンで降りる。
  1日目午前はプルークから基本を学ぶ。
  午後にはテレマークターンをこのようにやった。
  二日目も初心者用ゲレンデで繰り返し練習。
  後半塾長が中級者グループを見に行ったので、私は、
  ストイックにリフト待ちでイメージトレーニング。
  できましたとも、塾長の手本のラインをターンできました。

  そして午後にはビーコンのトレーニング。
  塾長が埋めた、ビーコンを探す。
  塾長の「仲間が３人埋まった！たすけてください！」
  と演技から始まる。
  面白い結果があるがこれは書かない方がよいだろう。

* <2017-01-09 月>  クロカンハイキング
  雪が少ないのでペンションからはスタートできず、
  車で出発地点まで行って、小野川湖の横の林道を２時間ほどのハイキング
  実はゲレンデはウロコ板は滑りがわるいので
  初心者で使うのはよくないのということで
  レンタルのテレマーク板を使っていたのでした。
  STINGERは前日の夕方ペンションの横の畑?
  で試していたのだが本格使いは今日が初めて。
  他の人は全部クロカンだったが私だけテレマークのウロコ板だった。
  第１陣出発地点到着。空は薄い曇り空だが雪は降っていない。
  苅田と思われる広い土地の真ん中に林道への道が一直線に続いて
  そこから入って、先にスキーをつけた人が
  ５mに満たない丘を見つけて遊んでいた。
  それを倣う。そして滑って初ゴケ。
  葉を落とした白樺の林が両脇に広がるなかだれも後をつけっていない
  林道を進む。
  ラッセルしているのは塾長だけど。
  おそらくリゾートではごくありふれた景色なんだろうが
  この自然との一体感がたまらなく幸せだ。
  熊注意看板あり。カモシカの足跡もある。
  少し登って、ハイカーのために作った丸木を数本束ねたような
  長さ２m程の橋がある。
  いきなりアドベンチャーゲームが始まる。
  ９人のハイカーが一人ずつ渡る。それを心配そうに見守るがだれも
  落ちない。
  次の橋は丸木が１本少ない細い橋。だれも落ちない。
  そうして小野川湖を50m程見下ろすところをすぎて、
  折り返し、昼食タイム。
  スキー板で雪を踏みしめて椅子を作る。
  ポットに入れてきたお湯を注いでカップヌードルを作る。
  スキー板がテーブルになる。
  うまいぞ。
  あっというまのランチタイム終了。
  帰りも歩きで行くが、途中で塾長が帰りの第１陣部隊を招集する。
  やった、選ばれた。３番目だ。走る。
  あの細い橋の先が左に崩れてやばい、よちよち歩きで渡るが
  渡りきったところに段がある、ウロコ滑った。
  やばい落ちる、うっ我慢する、やった乗り切った。
  だれも落ちなかった。
  パスカング開始、随分と前にやっていたのでこれは得意。
  だがすぐにSTINGERは心拍数を上げさせてきた。
  クロカンと比べると先が太い分抵抗は大きい。
  自分のランニングに例えるとキロ４分後半程の心拍数だ。
  あと１kmあったらついって行けなかったかもしれない。
  また、あの丘で遊ぼうとする他の隊員。
  さすがにもう元気がなくなった私はただみているだけ。

  いやー。これほど遊んだのはこの１０年でも思いつかない。
  出された食事の本格的なビストロ風もうまかった。
  
  裏磐梯テレマークスキー塾のエイリアスとは。
  遊びの天才と遊びを心得た大人の集う塾だ。
  
* <2017-01-15 日> R10.0 W2.0
  ランナーは左側を走る。
  この常識は陸連がちゃんと言ってないからと
  周りをよく見ていないバカランナーが右側走行をしている。
  そんなバカが二人もいやがった。
  顎上げて必死の腐れ顔したやつ気持ち悪いんだよ。
* <2017-01-19 Thu> R5.0 W1.0
  AM
* <2017-01-22 Sun> R21.09 W2.0  2:00.49
  マリンマラソン
  2:00.49
  ベスト２
  キューちゃんにハイタッチするのも忘れて走った。
  ２時間切りに４９秒惜しかった。
* <2017-01-29 Sun> R5.0 W1.0    R-Total 64.0
* <2017-02-03 Fri> テレマーク
  東北新幹線19:16移動
* <2017-02-04 Sat> テレマーク  
  猫魔スキー場
* <2017-02-05 Sun> テレマーク  
  猫魔スキー場
  アルペンは上手くなった。
  でもテレマークは上手くならずむしろ下手になった。
* <2017-02-11 Sat> R21.09 W3.0　
  赤羽マラソン
  2:22.25
  ワースト２
  とにかく荒川周りは景色の変化ちいさくつまんなくて走りづらい。
  失敗の原因は、最初の２kmを10分以下で入ったこと、
  スタート位置がトップから１０mくらいに並んでいたこと。
* <2017-02-19 Sun> R7.0 W3.0
* <2017-02-24 Fri> テレマーク
  東北新幹線20:19移動
* <2017-02-25 Sat> テレマーク
  ネコマ
  男カレーと女カレーまずい。
* <2017-02-26 Sun> テレマーク R-Total 28.0
  グランデコ
  結局テレマークの免許＝星ひとつもらえず、
  今シーズンの山スキーデビューはならず。
* <2017-03-05 Sun> R10.0 W2.0
* <2017-03-07 Tue> ドクターストップ
  スキー転倒による肋間神経痛
  全治１４日間、ランニングは自殺行為と言われる。
* <2017-03-29 Wed> R10.0 W3.0  R-Total 20.0
* <2017-04-02 Sun> R7.0 W2.0
* <2017-04-09 Sun> R5.5 W0.5
* <2017-04-16 Sun> R7.0 W2.0
* <2017-04-23 Sun> R7.0 W2.0 R-Total 35.5
* <2017-05-01 Mon> R6.0
  帰宅ランニング
  信念：いついかなる時もランニングできるための最小の服装でいること。
  会社終わる、どっかのトイレ行く、パンツとワイシャツ脱ぐ、
  トレイルランザックに押し込む、メガネをサングラスに変える。
  帽子をかぶる、ストレッチする、走って帰る。
  ということで帰宅ランニング開始。
  ちぇっ4kmしかない。
  だから余分に走って6kmにした。
* <2017-05-05 Fri> R10.0 W2.0
* <2017-05-06 Sat> R15.0 W5.0
  浜離宮へ隅田川を下る。浜離宮、手作り弁当食べる。
  帰る。
* <2017-05-09 Tue> R4.0 W1.0
  帰宅ランニング
  信念：いついかなる時もランニングできるための最小の服装でいること。
  有事起こる。
  ワイシャツを脱ぎ破る、それをどっかのコンビニのゴミ箱に突っ込む。
  そして走る。
* <2017-05-09 Tue> R4.0 W1.0
* <2017-05-14 Tue> R5.0 W1.0
* <2017-05-16 Tue> R4.0 W1.0
  帰宅ランニング
  けっこうショーウインドウに映る自分の足のo脚が気になる。
* <2017-05-17 Wed> R6.0 W1.0
  錦糸町経由自宅まで。
  メガネの右の鼻当てが朝起きたらなくなっていた。
  だからここのメガネ市場まで走ってきた。
  ただだった。
* <2017-05-18 Thu> R4.0 W1.0
  帰宅ランニング
  けっこう排気ガスきになる。
* <2017-05-19 Fri> R4.0 W1.0
  帰宅ランニング
  けっこうショーウインドウに映る自分の背中の丸みが気になる。
* <2017-05-21 Sun> R3.0 W1.0
* <2017-05-23 Tue> R4.0 W1.0
  帰宅ランニング
  昨日の月曜日だけは帰宅ランをしていない。
  ランニングと同じで週始まりは徐々にいきたいからだが。
  シューズはウォーキングシューズだ。
  rockport だ、フツーにはローハーに見える。
* <2017-05-24 Wed> R4.0 W1.0
  帰宅ランニング
  シューズはも一年も使っていたので、ヘタリがわかる。
  で、インナー変えた。
  裸足のようにへたっていたのがわかるいい感じクッションになった。
* <2017-05-24 Wed> R4.0 W1.0
  帰宅ランニング
* <2017-05-28 Sun> R21.0 W3.0
  頑張った。
* <2017-05-29 Mon> 
  目の右にゴフルボール大の日食とまったく同じイメージの
  不審物が映る。
  三楽病院へいく、うちはレーザできないから、紹介状だす。
  紹介状もって看護婦くる、自分で連絡しなさいね。
  あっこに公衆電話あるからね。
  かけてくださいね。
  #瞳孔開く目薬打って見えないんだけど。
* <2017-05-30 Tue>  網膜剥離発覚
  翌朝、飯田橋の病院の眼科にかかると、あっこれ。
  レーザーじゃダメ手術だ。
  明日ここに９時前にきてください。と名刺渡される。
  明日は手術16個入っているけど途中にねじ込むから。
  帰ったら左を下にして安静にしてください。
  枕はつかわないでください。
  途中会社によって報告と月締め処理して帰って横になる。
* <2017-05-31 Wed> R-Total 94.0
  京成立石駅
  みずほ眼科緊急手術 15:00-16:05
* <2017-06-01 Thu> 
  眼帯はずし
* <2017-06-03 Sat> 
  検診、うつぶせ寝
* <2017-06-05 Mon> 
  検診、うつぶせ寝
* <2017-06-08 Thu> 
  抜糸、うつぶせ寝
* <2017-06-15 Thu> 
  空気が抜けるので再剥離危険どます
  右傾斜
* <2017-06-22 Thu> 
  90%完治めど
* <2017-06-26 Mon> W10.0
  大倉山
* <2017-06-29 Thu> 
  完治
* <2017-07-01 Sat> W10.0
  ビッグサイト
* <2017-07-03 Mon> 
  会社スタート
* <2017-07-09 Sun>　W2H
* <2017-07-13 Thu>
  検診 左目レザー8/2
* <2017-07-17 Mon> W10.0
* <2017-07-21 Fri> 
  飲み錦糸町
* <2017-07-23 Sun> W12.0
* <2017-07-30 Sun> R5.0 W1.0
  手術後２ヶ月経ったのでランニング再開
* <2017-08-01 Tue> 
  東京武道館（綾瀬）珠算電卓全国大会
  今日は姪っ子の長女が熊本県の珠算の代表に選ばれたので
  会社休んで見に来た。
  本人から見るものではないと聞いていたが、種目をこなしている
  うちこれは競技として発展してきていると思えてきた。
  東京武道館は日本武道館、国技館だとかに名前が沈んではいるが
  立派な三階席を有した体育館だ。
  万、億の数字がマイクで呼ばれるのを珠算、電卓、暗算と競技
  が繰り返される500人近いエントリーを最初の半分に減らす、
  ３問、姪っ子、最後に9000たすの忘れて２問間違いで予選敗退。
  会場退出、小さな体で大股で悔しさを表す姿が愛おしいぞ。
  大会終わって体育館を出たら雨だった。
  今日のディズー二は無理だよとラインしたら、行くよと返事。
  JKは、すごいぞ。
* <2017-08-02 Wed> R5.0 W1.0
  左目レーザ10分で終わる
* <2017-08-05 Sat> R10.0 W2.0
  last 1km wind sprint
* <2017-08-07 Mon> R4.0 W1.0
  帰宅ランニング
* <2017-08-07 Mon> R3.0 W1.0
  帰宅ランニング
  浅草橋の駅前を抜けスピードアップゾーンに入った途端重い湿度の沼に
  突っ込んだ。そして息ができなくなってストップ。
  なんとか隅田川に出れば息ができると必死で足を動かすが、
  テラスも湿度の沼と化していて風もない。
  経験から蔵前橋を過ぎればなんとかなると必死で歩く。
  風が少し出てきてなんとかなった。
  全身ずぶぬれで火照った体をクールするのはスーパーだと思いつく。
  野菜売り場を過ぎて鮮魚売り場に達した時、一挙に冷えたシャツは心臓を止めようとする。
  やばい、今日２度目の死の恐怖体験だ。
  シャツを心臓から手で離して背中をまるめてなんとか脱出。
  これで帰宅ランニングはやめた。
* <2017-08-11 Fri> R7.0 W2.0
  朝走って久しぶりに新幹線で帰省。
  福岡まで、昔７時間半だったのが５時間半になったがそれでもちょっときついな。
* <2017-08-14 Mon> R7.0 W2.0  
  昔の友人と小倉で泊まり込みで飲んでそのまま
  翌朝下関観光へ市場は休みだったがフグはたくさんいた。
  そのまま新幹線で戻って両国についた。
* <2017-08-14 Mon> R7.0 W2.0    
* <2017-08-18 Fri> R5.0 W1.0    
  帰宅ランニングやめたので早朝ランニングにした。
  ランニング終了後すき家の卵かけ御飯ミニ220円を食って帰って
  洗濯して２度寝してぐったりなって会社いく。
* <2017-08-19 Sat> R7.0 W2.0    
  早朝ランニング＋卵かけ御飯ミニ
* <2017-08-20 Sun> R3.0 W1.0      
  暑くて3kmで終わり
* <2017-08-22 Tue> R5.0 W1.0      
  早朝ランニング＋卵かけ御飯ミニ
* <2017-08-23 Wed> R5.0 W2.0      
  早朝ランニング＋卵かけ御飯ミニ
  クールしていると。
  隅田川のテラスの手すりのすぐ横に竹一本水面から1m程
  棒を突き出して漂っていた。
  よく見ると下に竹の根っこの株がついていたそれでも凝視していたら
  35cmくらいの体高のあるバスが汚れた黄色い水を通して銀色の
  体を翻して逃げていった。

* <2017-08-25 Fri> R5.0 W2.0      
  早朝ランニング＋鯖焼き卵かけ御飯ミニ360円
* <2017-08-26 Sat> R7.0 W2.0      
  今日は眼科の検診、問題なし。
* <2017-08-26 Sat> R7.0 W2.0      
* <2017-08-27 Sun> R21.0 W4.0      
  浅草から白髭橋へと登るテラスは工事で横の道路を走らされる。
* <2017-08-29 Tue> R3.0 W0.0      
* <2017-08-31 Thu> R10.0 W3.0 R-Total 100.0 
* <2017-09-03 Sun> R7.0 W2.0
  昼過ぎランニング
* <2017-09-05 Tue> R5.0 W1.0
  早朝ランニング＋鯖焼き卵かけ御飯ミニ360円
* <2017-09-08 Fri> R5.0 W1.0
  早朝ランニング＋鯖焼き卵かけ御飯ミニ360円
* <2017-09-09 Sat> R10.0 W3.0
  早朝ランニング＋鯖焼き卵かけ御飯ミニ360円
* <2017-09-10 Sun> R11.0 W1.0
  早朝ランニング＋鯖焼き卵かけ御飯ミニ360円
* <2017-09-14 Thu> R5.0 W1.0
  早朝ランニング＋鯖焼き卵かけ御飯ミニ360円
* <2017-09-16 Sat> R15.0 W4.0
  早朝ランニング＋サケ焼き卵かけ御飯ミニ360円
* <2017-09-18 Mon> R10.0 W2.0
  9:00ランニング開始
* <2017-09-20 Wed> R7.0 W2.0
  早朝ランニング＋鯖焼き卵かけ御飯ミニ360円
* <2017-09-22 Fri> R5.0 W2.0
  早朝ランニング＋鯖焼き卵かけ御飯ミニ360円
* <2017-09-23 Sat> R10.0 W3.0
  早朝ランニング＋鯖焼き卵かけ御飯ミニ360円
  今日は末の姪っ子の第３回ジャズコンクール全国大会。
  姪っ子はあの去年の地震の益城町の益城町立中学校。
  このコンクールは、初代のチャンピョンが珠算の長女で
  演劇部からピアノの応援に抜擢され吹奏楽で全国を勝ち進んで
  錦糸町のトリフォニーに来ていた。
  そこで私の目の前で第一回で優勝していた。
  それがディフェンデングチャンピョンとしてシードされ、第二回も優勝した。
  今年は三女が一年生でバリトンサックスで望んだ。
  デフィエンデングチャンピョンは当然、おおとりとなる。
  私は、それまでの１２校の演奏を聞いていたが、益城中学の演奏は
  はるかにそれら凌駕していた。
  絶対断絶次元の違う演奏で三連覇を達成した。
  益城の演奏者はすべてに音楽をしていた。
  音楽は上手い下手なんか関係ない。でも練習とそれがうむ全体効果がわかる。
  今日のこの会場の瞬間の意味で音楽が達成できるか決まる。
  そういうのはベルリンフィルとも同じだ。
  今日、益城中は、完全に音楽そのものを演奏していた。
* <2017-09-26 Tue> R5.0 W1.0
  早朝ランニング＋サケ焼き卵かけ御飯ミニ360円
* <2017-09-27 Wed> R5.0 W1.0
  早朝ランニング＋鯖焼き卵かけ御飯ミニ360円
* <2017-09-30 Sat> R15.0 W3.0 R-Total 114
  早朝ランニング＋鯖焼き卵かけ御飯ミニ360円
  今日は墨田区の健康検診。
  体重が1年前の検診70kgから63.5kgに記録された。
  今日は朝トイレ済みの体重61.5kgだった。
  早朝ランニングに切り替える前は朝と昼はおにぎり一個にしていた。
  夜も含めて1000kカロリくらいだったと思う。
  徹底的にカロリーを抑えた生活をしていて、月間走破距離が伸びて
  筋肉量をあげたため一挙に体重が減ってきた。
* <2017-10-05 Thu> R5.0 W1.0
  早朝ランニング＋鯖焼き卵かけ御飯ミニ360円
* <2017-10-08 Sun> R15.0 W3.0  
  今日は30km走らなくてはならなかったが、早朝ランニングできず
  15時スタート。
  21kmコースが浅草ー白髭工事なので断念し、
  白髭ー南千住5kmを周回して2回でtotal19km４回で29kmとして
  白髭ー桜橋がフィニッシュでフルマラソンの練習ができる。
  しかし、白髭ー南千住には自動販売機の設置が見当たらない。
  今日外してさがしていたら隅田川から少しだけ入ったところの
  公園に水飲み場を発見した。
  水は水道水のまずさがあったがこれを利用すれば30kmコースができる。
  もちろん40kmもできる。
  少しコースを逸脱するのが残念だがペットボトルは運ぶのもトレールザック
  を装着するのもいやだからこれを有用しよう。
  このランニング後体重は遂に60.9kgになっていた。
  水分補給後なので60kg前半までさがったことだろう。
  10/29の金沢マラソンに向けダイエットは成功した。
  あとは30kmを２本いれられるかどうかだ。
  28日までに100kmとし平日の早朝は減らすようにしよう。
* <2017-10-11 Wed> R7.0 W2.0 
  AM4:30からランニング暗いからヘッドランプしているが
  どうもバッテリィが弱い。
  いつも5kmだが今日は7kmでどうなるかみる。
  吾妻橋フィニッシュ。
  疲れた。すき家の生卵定食300円。
* <2017-10-12 Thu> R5.0 W1.0
 AM6:00開始、ごく普通にbuild up して終わる。
 松屋330円。
* <2017-10-13 Fri> R5.0 W1.0  
  AM4:10開始、ごく普通にbuild up して終わる。
  松屋330円
* <2017-10-15 Sun> R30.0 W3.0  3:22
* <2017-10-22 Sun> R20.0 W3.0  
* <2017-10-29 Fri> R42.19 W5.0 Net4:34:17 4616位/10709人中
  今日は5月頃に申し込んだ金沢マラソンツアーの２日目つまりマラソン当日だ。
  ツアーが用意したのは東横INN金沢兼六園香林坊だった。
  ここが良かったことは一つしかない。
  スタート地点まで５分という立地だけだった。
  今日も同じホテルに止まるので必要な荷物だけ持っていけるし、
  ストレッチを部屋でやるのでかなり余裕がもてることだ。
  朝食は過去のバイキング歴でも最悪でアパとはえらい違いだ。
  ひじきの煮物、切り干し大根、キャベツの千切り、つくね、スクランブルエッグ
  と味噌汁と申し訳のバナナ。これだけ。しかも泊まってるのはランナーだけ
  だから時間は同じになるので２０分以上またされた。
  なるべくゆっくり食べて部屋に戻って準備。
  今日はずいぶまえから気になっていた今日は通り雨になる。
  雨は30km走と20km走の練習でも経験したとおり、左足の中指から始まり
  徐々に全指に痛みがでる。
  これは20km走で確認した通りつま先が濡れて冷えてしまったというのが
  原因の半分をしめていると思う。
  今日も朝は降っていないが降ってくればこの痛みでどうやって３０kmから
  の未経験距離を走るかだ。
  だからベットで指のマッサージを入念にできるのはとてもいい。
  靴下も雨が抜ける５本指を用意しているこれは使用確認すみだ。
  ストレッチも入念にできたし準備万端だ。
  ゴミ袋もかってある。ジェルも二つ用意した。
  そしてシューズはゲルニンバス(19)おニュー。
  数日前に再計算してみると770km走っていたので慌てて銀座で買ってきたもの。
  なんと足測定したら数ミリ両方とも大きくなっていた。
  まえからつまさきのあたり感がきになることがあって店員も進めてきたので
  思い切って27cmにあげていた。
  履いた瞬間軽くなっているのがわかった。サイズもぴったし、今のシューズ(18)が
  どれだけへたっていたかもわかった。
  初つくしが心配だがもうやるしかない。
  7:30頃にホテルを出ようとするともうみんなの列が歩道を埋めていた。
  私も加わった。
  市役所まえがでスタートゲート。走者は、スペシャル(S)、A-Kまででだ。
  Gで直角におれてKが最後。昨日の下見ツアーではKまで800mあるそうだ。
  私はGだったちょっと迷ったがゴミ袋を被ってゼッケンと対応する車のトラックに
  に荷物をあずけて位置につく。
　アップはしなくても自然となると思ったんですこしだけのアップにしたけど、ここでは無用。
　今日の体重は計っていないが62kgだろう。
　これでマラソン中は61kgで走り続けることを目指してダイエットと練習をしてきた。
　2016/7月健康検査の時70kgだったが昨今で朝のトイレ済み状態で60.5まで
　いっているから10kg近いダイエットをしてきた。
　万全である。
　これがフルに対する一環した私のアプローチだ。
  号砲まで随分と間がある。どこでイベントやっているかわからなが、ゲストの野口みずきがやけに
　ハイになってうるさい。
  それに時間がかかりすぎる８：５０スタートらしいがまだ３０分あるけどもう締め切りだそうだ。
  雨はまだ降っていないがゴミ袋でないasicsのロゴが入った使い捨てのポンチョが羨ましい。
　どっかで配っていたんか。
　ずいぶんまったあと市長のピストルでスタート。
　しばらく動かなかったが徐々に歩き出した。
　スタートゲートをすぎたとたん走り出した。これはよくできている。
　後日確認で号砲から８分２５スタートゲート切りだった。それでもスピードはでないから思った通りウォームを兼ねてる。
　順調なスタート切れてよかった。心配は雨だけだ。
　５km経過後時計を見ると6分30秒より遅れている感じがする。実は後でラップ確認したら6:15だった。
　もうゴミ袋は外して集めているスタッフに渡した。
　少し飛ばすこと試みる次の５kmが6分、景色を見る余裕はない。
　すでに雨がポツリゴミ袋捨てたことへの後悔はない。
　１０ー１５kmが６分９秒。
　このころ4:45分のペースランナーを抜く長めの紐をつけた風船が高いからよく見える。
　この心から左中指の痛みが嫌な予感を持ってくる。
　雨は靴をとおり指に達している。３０km走と２０km走の経験からこれが冷たい水がいくらか
　起因していることがわかる。だがまだラン中のストレッチも入れる必要はない。
　とにかく想定した6:30で距離を稼ごう。
　１５−２０kmが６分２５秒、いつものハーフは半分行ってなお喜びはない。
　２０ー２５kmが６分４４秒、足の痛みは左の指全部にいっている。ラン中ストレッチを繰り返している。
　エイドの水やドリンクはそのたびにとっているが人だかりのするエイドは避けている。
　このころだったか裸足の被り物ランナーに抜かれた。
　足の指は右にも波及していた、左が利き足だが右にその役目をさせていたのが効いてきたようだ。
　珍しくエイドが空いているところを見つけた、何かお菓子だ、芋だ、一杯たべた、すると
　横のばーちゃんがこれも絶対うめーから食っていけ。
　そういわれて一杯とった、そしたらその横の親父が無言でお稲荷さんを一つ握って前に突き出していた。
　それもかわかったのでとった。
　でばーちゃんのを食った。その瞬間口の水分を全て失った。
　やられた。だが確かにうまかった。
　幸いにもすぐに水があったので水をとって芋を噛み流して、お稲荷さんを２口で食って、
　元気がでた。ばーちゃんがんばるね。
　折り返しで例の4:45分のペースランナー探すがいない。
　安心した。
　だが彼らは恐ろしい秘密兵器を持っていた。
　しばらくしてもエイドでなにかを物色しているとなんと４：４５分のペースランナーもエイド探してんじゃ
　ねーか。やられた。彼らのフーセンは縮んで頭の高さじゃねーか。
　それじゃステルスじゃんか。
  30-35kmは７分１秒まで落ちてる。
　一挙に絶望感に突き落とされるがこの集団につくしかね。
　この集団は大きい。それにうざい野郎のくささがひどい。
　なるべく新鮮な空気のクールな位置取りをして逃さないように私の最大の試練がはじまった。
　35kmをすぎると私の心境はもうどうでもよくなった。
　足がちぎれて後どうなろうともどうでもよくなった。
　だから一切ラン中のストレッチもなし、骨盤傾斜、肩甲骨の引き、足のスライドと着地と
　上下をなるべくさせない。いつも考えている最高のフォームに集中。
　35-40km 6分43秒このタイムは後でわかったことだけど、やればやれるんだね自分くん。
　いとおしいよ。
　ということで４０kmの給水もすっ飛ばしゴール4:45のペースと一緒にゴール。
　webの結果からわかったんですが、スタート６７１３位、ゴール４６１６位、２１００人近く抜いてました。
　そして金沢マラソンはストレッチもウォークもなしの完全完走でしめくくりました。
  
　グロス　41:16 1:12:29 1:42:33 2:13:19 2:20:08 2:45:26 3:19:05 3:54:11 4:28:01 4:42:42
　ラップ  (32:51)　(31:13) (30:04) (30:46) (32:07) (33:39) (35:06) (33:50) (14:41)
* <2018-01-09 Tue> R5.0 W1.0 
  AM 5:30スタート、そのまま松屋へ。ヘッドランプ点灯したままいつもの定食330円食って
  今年のランニングスタート。
  他の人から見て俺は異常者だろうな。
  ヘッドランプついてますよ。とはだれも教えてくれないよな。
* <2018-01-14 Sun> R10.0 W2.0
* <2018-02-12 Mon> R6.0 W1.0
  今年はランニングにうまく入れずまま２月中旬までになってしまった。
  １月総距離は15km。
  先週はテレマーク。
  2/7に喉痛発生、翌日治り、その翌日際発症、鼻水があまりにもすごかったので、
  早退したらインフルエンザB型と判明。
  熱も平日症状もなんともない。
  だから2/18は青梅マラソンなんで走ろうとした。
  昨日と一昨日は医者に止められたから止めたが、今日は走らなければの義務感で
  走ってきた。しかし、肺が苦しくて６キロで止めた。
  青梅３０km３時間を目標でサブ４.5を手中にしてサブ4への足がかりにしたかった。
  体重は増やしていない。それだけが武器だ。
* <2018-02-17 Sat> R6.0 W1.0
  不覚にも酒飲んで苦しい。
  明日青梅じゃありませんか。
  もう午後３時を回った早くしないと日差しが弱くなって寒くなるぞ。
  いやいやストレッチして古いストッキングと半袖モンベルの古い自転車用の
  ブレカー羽織って開始、マンションでると寒い。
  隅田川にぶつかって厩橋へ風が強い。
  隅田川の東京側テラスは日陰だ。
  やめてくるっと回って両国側テラスを南下、総武線の下までつかないうち
  に工事中3/22まで護岸強化するらしい。
  ここで回って、吾妻橋までいく。
  風は海風だから春を先取りしている分背中の暖かさが慰めてくれるが気温は下がっている。
  途中のクレーの道は乾いている、吾妻橋まできて三味線の練習のおねさん。
  の音色を聞いてうまくなったね。
  と心でそのりりしそうな後ろ姿をみて言った。
  9日金にインフルエンザBに判定され平熱で大した支障もないのに休まされ。
  今日に至ったがなぜか今日はたんや咳がからむ大丈夫か。
  それでもまた工事中の看板で折り返し、駒形橋でやめた。
* <2018-02-18 Sun> R24.0 W6.0 青梅マラソン
  7:30起床、トイレ、お風呂準備、
  7:20ジェル、バーム、水、バナナ２本、着替えを８klトレイルバッグに無理やりつ混んでしっぱーつ。
  7:30松屋やっこミニ定食。今日は変なミャンマー人がいないので滞りなく配膳完了。
  7:44総武線
  8:9 新宿１２番宣青梅特別快速
  9:3河辺駅到着
  　　河辺小学校に行って着替える。
  　　なんと８畳ほどの小さな更衣室。いやな予感。
  　　小学校の雲底横でストレッチ、更衣室でワセリンは濡れたのであとは大腿部中心に
     長いストレッチをしよう。ひととおり終わったがその前にトイレ。
     小学校横の公園がそれらしい、いくとズラーリ大は数えると１０個しかない。
     いやな予感。
     ３０分近く待って完了。
     さってはしるか。この寒さから半袖長袖の２枚か長袖１枚かに迷う。
     経験上、この迷いは少ない方を選ぶがよい。
     もういちど更衣室に行って下のTシャツ脱いで寒くなる。
     荷物を預けようとすると事前登録が必要だと、そこらの校庭におけと。
     あっそうだったか。
     ランネットでエントリーしたのに案内が実家に送られてきたのも変だったが
     嫌な予感。
     だいたい去年の赤羽もマリンも全部自宅に送られてきたのになんで青梅だけ
     実家に送ってやがるんだ。
     嫌な予感
  10:45
     荷物をそこら辺においてスタート場所へ移動、片道２車線の道路を封鎖している.
     右は女性だと係がいうが女性がすくない。
     だから右にも男性がならんでよくなる。
     って俺ここで大失敗していた。
     11時スタートって勘違いしていた。
     アナウサーくだらないことばかりスタート時間を言わない。
     １５分たって２０分が整列時間だという。
     トイレに行きたい。
     もういけないのでがまん。
  11:30 スタート
  　　歩き。重量挙げのの三宅ひろみの声がどこからかする。
  　　10分スタート看板が見える。
  　　おおっっと走れる。とおもったのもつかの間止まる。
  　　しばらくして走れる。
     距離表示５kmまでなしか。
     給水所５kmわから、民家の水でしのぐ、
     給水所が短すぎ３分２はとれとなんぞ。
     係の祖父いがやたら横柄だな。
     6k,8kmわかった
     給水所は団子状態。
     御嶽駅きた時応援は大きくなった。
     前来たもんねあと２、３駅かな。
     距離わからん14kmわかった。
     ここまできつかったk６．３０で行っている。
     １５の折り返しポールにパンチしてジェルタイム。
     梅だった。
     21kmの坂がきつかった。
     ここまでは周りを少しずつ抜いて行っているので大丈夫のはず。
     くだりは5分台を出すはずだった。
     24kmで登りを登りきって、右足大腿部が棍棒のようになった。
     足の指の痛みも全部に憑ってしまっている。
     諦めたウォークとストレッチを入れた。
     もうこの段階で完全完走も記録もない。
     あとは早く終わりたいだけ。
     ゴールはスタートから１ブロック奥の信号の右だった。
     メダルと、ジェルしかも走る前に飲むのがおすすめのね。
     バーム、おにぎり。
     即日完走証発行もなし。
     つまらない大会２度と出ねーよ。

* <2018-03-03 Sat> 研ぎマイスター学院訪問
  35歳定年をごまかして21年働いてもう限界になってきたのでプログラマを
  引退することにした。
  まあ長年アナーキーな人生歩んできたから年金で生活できるほど
  払ってきていないので年金で生活もできるわけない。
  そこで考えたのが研ぎ師になること。
  １５年ほど前に実家の包丁研いでみたら上手く研げた。
  折り込みちらしもスーっと切れるから切れる方だろう。
  表題の学院は浅草橋にある。
  浅草橋から自宅には通り道にあるので、この研ぎの学院は前から知っていた。
  この学院のあやしい記事をwebでみていたがよくよくみるとフランチャイズも
  展開しているし信頼できそうという認識を持ち出した。
  それで今日初めての訪問となる。
  神社の横にある３階ビルの最上階に細い階段を登っていくと、
  ダイアル施錠のドアが現れる後ろには下駄箱生徒が吐くぞうりなどがある。
  ノックをしてドアを開けると空いており、老事務員らしい女性が迎え入れてくれた。
  すると前方の椅子座ってTVを見ているさむいをきた老人が目に入る。
  挨拶をすませて椅子に座って話を聞く。
  部屋は一部屋、理科室の作業台が３つおいてあり周りの棚には研ぎ作業で使う
  砥石や布や樽などがみっしり並んでいる。
  新しくはないが研ぎの学院だ。
  生徒の名札も書いてある。
  老人はwebなどの記事から毒がある人と思っていたがそうではない。
  優しい顔した88歳の老人で歯はなくその笑顔には詐欺の要素を感じない。
  話を聞くと25人先月卒業したらしい。
  江戸弁の話は落語家のようでもある。
  遠山をみて語る
  1年就業で授業料30万教材費30万の合わせて60万かかる。
  決して安くはないが１００万稼ぐ人もいるのでそうなれば高くない。
  だが、決してプロとしてやっていける人はあまりいないようにも思える。
  webで見たが仙台、取手、千葉、かっぱ橋、谷中、青梅、静岡、名古屋。。
  その他にもweb公開していない人も多くいるらしい。
  ７００名の卒業生から想像すると１０％いるのだろうかわからない。（憶測）
  だが私には後がないのでこの学院に入ることを決めている。
  包丁の販売も行けるようだ。倍掛けの利ざやらしい。
  7000仕入れが15000で売れるらしい。
  かっぱ橋に成功者の兄弟の店があるので覗いてみる。
  気持ちの良い挨拶を受けて店内をみる、包丁のディスプレーが綺麗だ。
  デザインの良さが溢れる店内は明るい、フジアミシンコ流の時が泳ぐ額縁も新鮮だ。
  明かすつもりはないのでそのまま無言で立ち去る。
  来週にでも入学し５月まで土曜日のみ授業を受ける。
  なお、研ぐ包丁は自分で集める必要はない、問屋と提携しているのでそこに研ぐ包丁は集まる。
  もう一度夢を見てみよう。

  砥石は決して高いものではない。
  人工でいい。
  2000から5000円以下平均らしい。
  あら研ぎで月に３本使うと100万収入の目安とも聞き取れた。

* <2018-03-31 Sat> togi1
  本日学費をはらい入校した。
  先生が砥石と前掛けを机の上に用意していただいていたのは
  とっても嬉しかった。
  途中から講師のかたが見えて指導してもらった。
  なかなか厳しい。
  今まで家で研いでいたのとは全然違う。
  右手で研いでいたのが引き手は左右で行う。
  左はなにもやってこなかったので動かない。
  もっとうの焦らず、あわてず、諦めないでやるしかない。
* <2018-04-07 Sat> togi2
  本日は新しい生徒と２人になった。
  つい先月仙台の高校を卒業したばかりの野球青年だ。
  思い切りの良い勇気と秘めたものを持っているようだ。
  まさか姪っ子の一つ上と肩をならべて生徒になるとは思ってもみないことだ。
  先生は親方とよばれそして生徒が増えると取手からこられる先生と
  事務関連を任されている先生の３人だ。
  先生について習う。習うとは難しいものだ。
  左手がだめだ。かといって右手もいいとは思えない。
  シンメトリーな形状にする練習。
* <2018-04-14 Sat> togi3
  今日ははじめて持ち込みの包丁を研がせていただいた。
  年期の入った菜切包丁だ。
  ところどころ錆びが掘ったと思われる小さな穴が群生している。
  しかしちゃんと除去されている。
  鋼を鋼で合わせているものでちゃんと波紋が出ていて愛用されているものだと
  わかる。
  研ぎは軽く荒研ぎからいつもより寝せるように松本先生から注意された。
  この包丁は確かに柔らかい。薄い作りでしなりもあるが鋼もやわらかい。
  いつもより優しく左手感覚で右手で引く。
  実は前回終わりに家で練習するため桶と砥石と練習刃物を借りてきた。
  ところが台所だと高すぎるため台が必要だった。
  踏み台はないので研ぎ台をと思ったが在庫が２０日もあるというニトリ。
  だめだと諦め店をでるがはと板でよいのではと気づく。
  何枚か傘せればいいと引き返すと入り口に食器や雑貨があり、
  コルクの２５cm X 12cmの1cmが２枚380円であった。
  これだ。８セットかった。
  家に帰ってセッティングするとぴったし、この位置はとみると
  丹田だ、これは偶然にもランニングで体幹意識使う中心だ。
  なかなかいい感じで４、５回研いで終わる。
* <2018-04-21 Sat> togi4
  昨日NHKのBSぶらり鉄道旅という番組の取材が入った。
  ６月に放送予定らしい。
  先生は以前の他局の取材と同じ研ぎに関する取材と思っていたらしく、
  卒業生をあつめて準備万端だったが、レポータの質問が解せない内容で
  立腹していた。
  で今日は教師もおらず先にのべた若い研ぎ師と二人修行となった。
  菜切包丁を２本２回研ぎ先生に見てもらって。
  まあこんなもんでしょう。ということで終わった。
  修行は厳しいもんだ。
* <2018-04-28 Sat> togi5
  今日も菜切包丁で引き手の練習左を多くしてなんとかなったかな。
  刃が曇っている。ここに顔が写ってしかも唇がゆがんでないこと。
  そうか鏡面は顔を写してまがりをみるんだ。
  刃物を横にして唇をみると横に伸びていれば曲がりが大きい。
  縦にして唇がちゅうちゅうタコちゃんになっていると曲がりが大きい。
* <2018-05-01 Tue> togi6
  先生に青紙２号のマタギナイフの研ぎ方を教わろうとを見せたら
  こんなのこないから中華包丁を研げと言われた。
  わかりました、中華包丁は2500円だ。
* <2018-05-02 Wed> togi7
  なぜかいつも研いでいる菜切包丁の刃がつかなくなった。
  中砥で修正していたが埒あかず、荒砥でやり直すことにした。
  でガンガン研ぎ直していたら刃が付くようになってきた。
  そしたら今日1日菜切包丁と格闘している私をみて
  怒った先生が
  「バカの一つ覚えで菜切包丁ばっかりやりやがって、歳なんだからもうちょっと頭使うとおもってたんだがしょうがねーな。」
  「菜切包丁なんてやったってしょうがない。」
  「はさみとげ。」
  研ぎ方の方法が水研ぎだとわかってその日は終了。
  中華包丁を借りて持ち帰り練習することになった。
  左の研ぎでかたかた砥石に包丁の肩があたる。
  左の力のなさを実感する。そして歯がとんでもなくのっぺり状態になった。
  これはなんとかせねば。
  翌日は筋肉痛もっとひどいからこれ以上ひどくならないように休む。
  次の日は朝からなんとかのっぺりでなくなり刃に線が入ってくる
* <2018-05-12 Sat> togi8
  今日はなんとか左の刃がわかる状態でもっていって先生にみせたら。
  よく研げてます。ほんとかな。今日は先生が機嫌がよい。
  それもそのはず新しい生徒さんが入って今日から生徒は３人になった。
  やったね。
  なんとバカな勘違い。
  実家にあった牛刀を研いで行った。
  てっきり出刃と同じで片刃でよいと思っていた。
  おおきな勘違い薄い刃物は両刃なんだ。
  どれくらい長い間だろうか多分１５年以上勘違いしてた。
  刃の角度が大きく曲がっているのが蛤。
  それより少しシャープなのが浅利。
　まだまだ蛤だ。直刃を目指さなければならない。
* <2018-05-12 Sat> togi9
* <2018-05-19 Sat> togi10
* <2018-05-26 Sat> togi11
  
* <2018-06-01 Fri> togi11
  退社後の初めての学校。
* <2018-06-02 Sat> togi12
* <2018-06-05 Tue> togi13
  + 出刃右
  永井
  + 柄交換
    出刃右
    ひとつ目われてあとは先生がやった。
    450x2=900円
* <2018-06-06 Wed> togi14
  + タグ
    |----------+--------------|
    | No.      |              |
    |----------+--------------|
    | お名前   |              |
    | 住所     |              |
    | 電話番号 |              |
    | 受取日   |              |
    | 見積金額 |              |
    | 研上金額 |              |
    | 種類     |              |
    | 銘       |              |
    | 寸法     |              |
    | 製法     |  |
    | 材質     | 本焼・合わせ             |
    | 研ぎ師   |              |
    | 研ぎ日   |              |
    | 責任者   |              |
    | 備考     |              |
    |----------+--------------|
  + 仕上げ    
  + 本霞研ぎ
  + マチ磨き
  + 裏押し済を調べる
    わからん
    とがないとわからん。
* <2018-06-07 Thu> togi15
  仕上げがうまくいかん。
* <2018-06-08 Fri> togi16
  刃はつくが。
* <2018-06-09 Sat> togi17
  柳刃は勝手にやってはだめだったらしい。
* <2018-06-12 Tue> togi18
  左出刃をやるがしあげがうまくいかん
* <2018-06-13 Wed> togi19
 + 個人事業　
   + 領収書
     + 目的
       経費の証拠となる
   + 経費
     + 給与賃金
       人をやっとった場合。
     + 外注工賃
       外部に作業を委託した場合
     + 原価焼却費
       例えば店舗の改装をした場合,１年度に経費にできない。
       5年間かけて年毎に焼却費として形状する。
     + 貸倒金
       貸した金が戻ってこない。
     + 地代家賃
       仕事で何パーセント使うかで計上できる。
     + 水道光熱費
       仕事で何パーセント使うかで計上できる。
     + 接待交際費
       ２人以上の飲食の領収書などで計上できる。
     + 通信費
       inernet,携帯
     + 宣伝広告費
       チラシ、webチラシ代。
     + 消耗品
     + 福利厚生費
       事業主は認められない。
     + 新聞費
       新聞、NHK受信料金、BS,CSスカパーも可能
     + 書籍代
     + 修繕費
     + 損害保険料
     + その他、事業で使う費用

   + 控除
     + 社会保険控除
       + 国民年金
	 約19万固定、過去に遡っても計上可能。
       + 国民健康保険（これがやばい）
	 自治体により異なる。私の年で墨田区の場合最大は58+19=77万になる。
     + 生命保険料金
       50000（年間保険料金による）
     + 基礎控除
       38万固定

   + 領収書がなくても経費にできる
     + レシート
     + クレジットカード明細
     + インターネットショッピングメール
     + 結婚式招待状
     + 出金伝票
       領収書がない場合。
       電車代、バス代などの交通費
       結婚祝いや香典などの慶弔費
       自動販売機のジュース代
       領収書をなくしたとき
       接待交際費の割り勘費用
* <2018-06-14 Thu> togi20
* <2018-06-15 Fri> togi21
* <2018-06-16 Sat> togi22
  名川さん卒業、オケを買う。
* <2018-06-19 Tue> togi23
  名川さんオケを自転車で運ぶ。
  １０倍のLED付きルーペを買う。￥8800-
  研ぎ上げた９本を椿油をつけて持って帰る。
* <2018-06-20 Wed> togi24
  体重が遂に64.4kgになった今日からおにぎり一個にする。
* <2018-06-21 Thu> togi25
* <2018-06-22 Fri> togi26
* <2018-06-23 Sat> togi27
  もうやめるかここ。
  なんもわからん。
* <2018-06-26 Tue> togi28
  外人
* <2018-06-27 Wed> togi29
  はさみ
* <2018-06-28 Thu> togi30
  はさみ
* <2018-06-29 Fri> togi31
  はさみ
* <2018-06-30 Sat> togi32
  柳刃
* <2018-07-03 Tue> togi33
  エリゼの小出刃
* <2018-07-04 Wed> togi34
  柳葉
* <2018-07-05 Thu> togi35
  
* <2018-07-06 Fri> togi36
  出刃
* <2018-07-07 Sat> togi37
  中華
  鰻裂
* <2018-07-10 Tue> togi38
  鰻裂
* <2018-07-11 Wed> togi39
  蛸引き
* <2018-07-12 Thu> togi40
* <2018-07-13 Fri> togi41
* <2018-07-14 Sat> togi42
  裁ハサミ
* <2018-07-17 Tue> togi43
    裁ハサミ、えりぜ
* <2018-07-18 Wed> togi44
* <2018-07-19 Thu> togi45
* <2018-07-20 Fri> togi46
* <2018-07-21 Sat> togi47
* <2018-07-24 Tue> togi48
* <2018-07-25 Wed> togi49
* <2018-07-26 Thu> togi50
* <2018-07-27 Fri> togi51
  研ぎ師卒業
* <2018-07-28 Sat> togi52
  台風
* <2018-07-30 Mon>
  + 和包丁
    1. 裏磨き
       1) 荒砥（小割れ）
	  スキがないと包丁はきれないのでちゃんとつける
       2) 中砥（小割れ）
	  天然砥石は砥糞を使う
       3) 仕上げ砥（小割れ）
    2. 峰磨き
       1) 荒砥、中砥、仕上げ砥（小割れ）
	  先端を研ぐときは柄尻を持ち上げる
	  出刃の峰の角はウロコ取りに使うので丸くしない
    3. 表磨き
       1) 荒砥、中砥、仕上げ砥（小割れ）
	  しのぎ筋を確認する（刃作りへの確認）
	  切り刃の状態を確認する（刃作りへの確認）
    4. 刃を作る
       1) 荒砥
	  包丁のきっ先から砥石の面に当てておおよそ刃角を分割する
	  そりの部分からは切り刃が丸くなると魚のおろしがやりにくいので平に修正する（縦研ぎ）
	  表できっ先からアゴまで返しをちゃんと作る
	  そり部分は返しの作りは早いがそれ以降は時間がかかる
	  しのぎ筋が本来の和包丁の筋をなしているか確認する（良い包丁をみる）
	  表の返しが出てきたら包丁砥石角４５度で研ぐ(中砥への渡し、正本カタログには６０度と書いている）
	  裏を真っ平らに研ぐ（サビの確認、裏押しとスキの確認＝だめなら裏磨きに戻る）
	  裏の返しと確認ができたら中砥に移る
	  包丁の状態が悪いものは中砥＃800を使う場合もある
       2) 中砥
	  表から裏と幾度か繰り返し刃のつきを確認しながら包丁砥石角４５度で研ぐ
       3) 仕上げ砥
	  刃角を一定にして研ぐ
	  刃の付きをみる
	  砥糞で研ぎ中についたサビや汚れをとる
	  よく水気を拭き取って帯芯で磁気をとる
	  刃の付きをみる（刃のないところはまた仕上げで付け直す）
* <2018-08-07 Tue>
* <2018-08-23 Thu>
  + 好い加減
    + トレードオフ
      + とは
	プロジェクトの要求とプロダクトの要求の妥協点を探すこと
    + プロダクト
      製品のことをいう。プロダクトの要求とは製品の品質が高いこと
    + プロジェクト      
      製品を生み出すための複数のコストにより構成されたものをプロジェクトという。
      プロジェクトの要求とは、コストのひとつたとえば人員の場合はより少ない人数で
      製品を生み出すということが要求となる
      納期の場合より短い期間。
      費用の場合より少ない費用。
    + 好い加減
      + とは
	すなわち相反するプロダクトの要求とプロジェクトの要求の妥協点をとること
	研ぎにおいては研ぎあげた刃物の品質がプロダクト、研ぎ工程がプロジェクト。
     
* <2018-09-07 Fri>
  + 緊急
  + 交響曲
  + ななみへのクラシックについて
    + とりあえずあげると言っていたが、
      俺もまたスピーカーシステム組んだら
      使いたいので貸す(CDだけ)ということにしてほしい。
    + 全cdは拭いて綺麗にした。
    + cdを自分で拭くときは円の中心から外へ拭くこと。
    + 今手に入らないものもあるので大事にしてほしい。
    + 交響曲、管弦楽、室内楽(協奏曲含む)、歌劇(歌曲含む)に
      分類した。黄色い札をつけているのでわかると思う。
    + 作者について分類しているので箱の中の順番は崩さないほうがいい。
    + 交響曲の聞き方は番号の新しい順に聞くこと。ただし、
      受験勉強中のBGMには合わないとももう室内楽あたりにしといた方が
      勉強のじゃまにならないと思う。
    + ジャズは俺の手元に残した。
    + ヘッドホンは小ジャックの色が変色していた。
      もし異常があるならこの前のこずかいで買って頂戴。
    + あとPHA-1というアンプを2013くらいに使っていたやつを送る
      iphone<===>PHA-1<===>ヘッドホン
    + 2018/9/7　利一
    
* <2018-09-27 Thu>
  + 21Kmコースを正確に引いてみた
    + 自宅横網2町目(START)
    + 厩橋東
    + 厩橋西(slope)
    + 神田川河口(return)
    + 吾妻橋(tonnel)
    + 白鬚橋(return)
    + 神田川河口(return)
    + 駒形橋西(500m調整)
    + 厩橋西(500m調整)(slope)
    + 両国橋(slope/工事あり)
    + 両国インタ(return)
    + 吾妻橋東(slope/signal)
    + さくら橋東
    + 白髭橋東(return)
    + 白髭橋東テラス(slope/GOAL)o
  + 富山マラソンのゼッケンとパンフ
    が2018/7/27 15次時点で届いていない。
    新幹線の予約開始されているのになにもできない。
    ど素人がど素人仕事してやがる。
    折り返し電話が遅い。
  + 夕方に届いた。
    飯なしが飯ありの間違いだったとか。
    JTBのど素人が作っている。
* <2018-10-06 Sat>
  + アパホテル富山予約
    + 10/28 日曜日
    + 6900
  + 計画
    + 10/27 10:08 新幹線かがやき523号
    + 富山到着
    + ロッカーに荷物預け
    + 観光ジョギング
    + ロッカーに荷物取り出し
    + 15:30富山総合体育館
    + 16:00バス４番
    + ルートイン富山インターホテル
    + 10/28バス移動
    + 9:00マラソンスタート
    + 16:00アパホテル富山チェックイン
    + 10/29 新幹線富山-黒部宇奈月
    + 徒歩１分富山鉄道乗車
    + 宇奈月下車徒歩移動
    + トロッコ鉄道
* <2018-10-07 Sun> R10.0 W3.0 AM
  + GEL-cumulus
    GEL-ninbus が600kmを超えて、左太もも裏に違和感がでて故障
    の前兆となってきた。
    昨日アシックス東京で新しいニンバスに交換しようと行ってきた。
    ところがサブ4.5や4を目指すならキュムラス20にしたほうがいいと店員が言ってきた。
    違いは足の平部分のゲルの有無らしい。ニンバスは初心者向きだから故障
    が起こらないように全体にクッション性の高いゲルを入れている。
    ところが速さを求めるならの蹴り出しの足の平から先にゲルがあると、
    ゲルが力を吸収して効率が悪いらしい。
    なるほど意味はわかった。両方履いてあるいて試してみた。
    思い切って挑戦してみようという気になって購入した。
    ゲルが無い分ニンバスより1500円ほど安い。
    そして今日が初おろしランとなった。
    先日からの太ももの違和感は出てこないが、もうひとつ左足のばたつく音が
    気になっていたがキュムラスに変えてこの原因がはっきりした。
    まず5kmで左足指元に痛みがでてきた。7kmでは左足の平に円形の打たれ感
    がでてきた。何回かwalkを入れてフォームリセットを計って左足のばたつきを
    抑えたフォームに修正してこの痛みが解消していくのを確認したのが9km地点。
    ニンバスはフォームの乱れにも対応してくれていたんだなあ。
    フォームの乱れは左骨盤の回旋と傾斜がうまく行っていなかったのではと思う。
    右足は左足より器用なので対応しているようだが10km以上だと痛感がでてくるだろう。
    明日以降このフォームでかかと着地から足の平、足の指もと、指先へとスムーズ
    で柔らかい動きを意識しよう。
    ただ、キュムラスで42kmフォーム維持して走れるか不安がある。
* <2018-10-08 Mon> R15.0 W3.0 AM
  + GEL-cumulus 2
    昨日の教訓から左足の着地と蹴り出しをスムーズにするフォームを意識して入る。
    今日は15km走る予定で5kmを通過するが前日同様左足のばたつきが出ている。
    5kmまでは上げる気しないが6kmからストライドが伸びてきてフォームもよくなった。
    吾妻橋を渡って順調に行きばたつきがなくなり骨盤の回旋もよくなってきた。
    順調にビルドアップし南千住を折り返して、ラストだが、じゃっかんのパニックがでて
    ラストはジョグして終わり。
    キュムラスはまだ馴染んでいない。途中ニンバスに戻るかとも思ったが、判断は早計
    と思うので20km,30km走まではキュムラスで走ってみよう。
    なんとなくだがスピード感は上がっていると思う。
* <2018-10-09 Tue> R8.0 W3.0 AM
  + GEL-cumulus 3
    10km,15kmと連続して走っていたので5kmまじかで疲れが出て、なんとかごまかそう
    としたが8kmで終わり。
* <2018-10-13 Sat> R15.0 W3.0
|--------+-------+------+------+-------+-------------+----------+----------+-------------+-----+-----+-----+-----+-----|
| No.    | 1     | 2    | 3    | 4     | 5           | 6        | 7        | 8           |   9 |  10 |  11 |  12 |  13 |
|--------+-------+------+------+-------+-------------+----------+----------+-------------+-----+-----+-----+-----+-----|
| year   | 18    | 19   | 20   | 21    | 22          | 23       | 24       | 25          |  26 |  27 |  28 |  29 |  30 |
|--------+-------+------+------+-------+-------------+----------+----------+-------------+-----+-----+-----+-----+-----|
| OJIOJI | 57    | 58   | 59   | 60    | 61          | 62       | 63       | 64          |  65 |  66 |  66 |  67 |  68 |
| (O)    |       |      |      |       |             |          |          |             |     |     |     |     |     |
|--------+-------+------+------+-------+-------------+----------+----------+-------------+-----+-----+-----+-----+-----|
| MIWAKO | HI-3  | D-1  | D-2  | D-3   | D-4         | S-1      | S-2      | S-3         | S-4 | S-5 | S-6 | S-7 | S-8 |
| (MI)   | 100-O | 50-O | 50-O | 50-O  |             |          |          |             |     |     |     |     |     |
|--------+-------+------+------+-------+-------------+----------+----------+-------------+-----+-----+-----+-----+-----|
| NANAMI | JH-3  | HI-1 | HI-2 | HI-3  | D-1         | D-2      | D-3      | D-4         | S-1 | S-2 | S-3 | S-4 | S-5 |
| (NA)   |       |      |      | 100-O | 50-PA/MI/NA | 50-MI/NA | 50-MI/NA |             |     |     |     |     |     |
|--------+-------+------+------+-------+-------------+----------+----------+-------------+-----+-----+-----+-----+-----|
| MARIKO | JH-2  | JH-3 | HI-1 | HI-2  | HI-3        | D-1      | D-2      | D-3         | D-4 | S-1 | S-2 | S-3 | S-5 |
| (MA)   |       |      |      |       | 100-O       | 50-PA/MA | 50-PA/MA | 50-MI/NA/MA |     |     |     |     |     |
|--------+-------+------+------+-------+-------------+----------+----------+-------------+-----+-----+-----+-----+-----|

* <2018-10-14 Sun> R10.0 W3.0

* <2018-10-15 Mon> R14.0 W3.0
  21kmハーフコースを走る、飯は100kcalのおかゆこれが
  原因で12km めまい感パニックかと思ったが、ハンガーノックらしい。
  walkで回復試みるが吾妻橋でフィニッシュ。
* <2018-10-16 Tue> 高尾山
  急に高尾山登ってそのあと浅川国際マス管理釣り場で遊んでみようと思った。
  9:05-10:15JR中央快速高尾駅
  京王線高尾駅から高尾山口駅
  １号路-3号路-登頂-4号路-蛇滝-蛇滝バス停-日影
  一匹しか釣れんかった。
* <2018-10-17 Wed> R10.0 W3.0
  km６分を保ってラスト1kmだけスパートの練習に変更。
* <2018-10-18 Thu> R20.0 W3.0  
  ひさびさ南千住の折り返しを２週して20km走。
  6分の巡行でラストもスパートできた。
* <2018-10-19 Fri> 
  すぎ内科ここの先生ボケてきやがった。
  血液検査していらない薬がないかチェック。
  森平という自然砥石の店を発見、そこの人造荒砥をかった。2900円。
* <2018-10-20 Sat> R15.0 W3.0
  6分の巡行でラストもスパートできた。
* <2018-10-21 Sun> R7.0 W3.0
  15kmの後は疲れが残っているので軽めに7kmで終了。
* <2018-10-22 Mon> 
  30kmやるつもりが飲み過ぎでアウト。
* <2018-10-23 Tue> R10.0 W3.0
  途中で小雨。気温16,富山の雨のシミュレーションができた。
  雨で気温が低いなら長袖でスタートしよう。
  かなり寒かった。
* <2018-10-24 Wed> R10.0 W3.0
  昨日寒くて1kgも下げられず、気温も同じだったので、タイツ、長袖、半袖、ウインドブレーカを
  きて走った。ボクサー効果はすぐに現れ汗をかいていく。
  終わりで61.3kgほどだった。
  30kmを入れられなかったのがどうマラソンで出るか不安だ。
  それから大会で長袖ででるか半袖ででるか迷ってきたら。
  半袖がもう数年前のものしかない。
  というかほとんどの大会で着ていたものだがシミも傷もあってなんか恥ずかしい。
  で神保町、御徒町、アシックス東京を回るが、なんと大会にでるシャツがないのだ。
  大会に出るシャツとは胸元にジッパーがあるものということが重要なのだ。
  そういうものを各メーカは作らなくなったようなのだ、厳密にはnothfaceにあった
  があんまり好きじゃないから他を探した、結果ないのだ。
  じゃあ長袖はとみても冬場になったせいか厚手の生地のものしかない。
  各メーカさん。よう。おまえら馬鹿だろう。
  これだけ回って大会用のシャツがないなんて信じられないやらもどかしいやら。
  なんか間抜けな企業効率が背景にあるんじゃないだろうかと思う。
  結局３種の色があった最初に行った神保町に戻ってnothfaceを買ってきた。
  そこらへんのTシャツの倍の7000円もしたよ。

* <2018-10-25 Thu>
  先週の血液検査で中性脂肪が81となり、トライコアを１錠にすることになった。
  眼科の検診で新たな事実が発見された。
  一月前あたりから焦点を合わせた文字が滲んで見えないということに気づき始めた。
  紙面などではフォントが違うと思っていたが焦点を結ぶ網膜の下に水泡があるとことがわかった。
  といっても私の主張で改めて画像をみたらそうなっていた。
  おそらくもっと前からこの水泡はあっただろうが先生が気づかなかったのではと思う。
  これの影響度は如何ばかりか?
  近くを見るときでも遠くを見るときにもあるから毎回検診で目の測定にも影響がある。
  つまりはメガネを作るにしても影響がある。

  そもそも私はどういう経緯で苦しんできたか。否、苦しんでいたことも書いていないかもしれない。
  発端は2017/5/27日会社に行ったら右目の右下に黒い斑点があることに気づいた。
  この斑点のイメージは日食に酷似している。それがゴルフボール大の横にあったのだ。
  メガネの黒いつるの影で大きくなっていた。それを会社の明るい蛍光灯の中で浮き彫りにされた
  格好である。
  飛蚊症の一種と思ったが異常さの恐怖が勝って会社には伝えず近くの三楽病院の眼科に受診した。
  ずいぶんと待たされて診察に入ったら案の定女医がいてた。
  目に光を当てる装置に顎を乗せて診てもらった。
  なんでこんなに慌てた感じで診ているんだろうかと思うと不安になってきた。
  網膜剥離しているようだがレーザーで治るかわからない。ここでは手術できないので医者を
  紹介する、どこがいいというから飯田橋か新宿かというと迷っている私をみて飯田橋が近いので
  紹介するという。その後待合で待っていると看護婦が自分で電話して予約を取りなさいという。
  なるほど、この病院はこれで終わりでのちの事は自責に粉したいらしい。
  で看護婦に案内され院内のテレホンブースに行って看護婦がここに電話して先生の予約をとって
  と指示する。それでこの病院の役目は果たしたらしい。
  翌朝その飯田橋の病院に行くとこれから世話になる先生がいた。
  最初にこの先生は初診の医者のレーザー治療前提で話をしてきた。
  私はこの大きな黒いものの話をすると初めて例の装置で診てくれた。
  ああ剥がれている。明日緊急手術です。
  今日これから会社に帰って状況説明してそのまま右側を下にして安静にして
  明日ここの眼科で手術するから9:00前までにはきてください。
  15人手術予定ですがこの途中にねじ込みます。
  立石にある紹介された眼科にいくといろいろ検査して血も取られ、
  診察室の裏の抜歯用の治療台の上に右を下にして横になって、
  手術の順番を待つことになった。
  そして６時間後に手術できることになった。

* <2018-10-26 Fri>
  眼科。焦点を合わせた文字が滲んだ状態に見えるというのを医者にいったら、
  黄斑水疱といって焦点を合わせる網膜のポイントの下に水疱があることがわかった。
  これは白内障手術や網膜剥離手術の合併症らしい、幸いもっとも軽いもので点眼で
  治るらしいから点眼をもらって1日２回点眼することにした。
  そもそもこの症状は9月末から10月頭で気づき始めたのだ。
  術後なんども視力検査していたがこの症状では視力検査によるコンタクトやメガネ
  の合わせの土台が違っていたのではないか。
* <2018-10-27 Sat> R3.0 W1.0
  明日はマラソン大会なので新幹線で移動する。
  10:08はくたか
  
* <2018-10-28 Sun> net 2:33:57
  Start	00:05:51	
  5km	00:38:41	0:32:50
  10km	01:08:22	0:29:41
  15km	01:37:35	0:29:13
  20km	02:07:58	0:30:23
  中間	02:14:41	
  25km	02:39:00	0:31:02
  30km	03:12:59	0:33:59
  35km	03:49:13	0:36:14
  40km	04:25:38	0:36:25
  Finish	04:39:48	0:14:10
  28kmあたりでふくらはぎに疲労痛がでてストレッチとウォークをいれないと
  走れないと判断して完全完走を断念。
  以上のような結果になってしまった。
  ふくらはぎの痛みの原因がタイツにあると思っていたが、このタイツは
  去年の金沢マラソンでも走っていたので違う。
  中間は2:08:50だから前半の入りは予定どおり問題なかった。
  それも月間190km走って望んだのだからこのペースで良かったはず。
  ふくらはぎの痛みの原因はなんだろうか。
  シューズをGEL-Cumulus20に変えたこと。
  メンタル面が去年の金沢より下げていたこと。
  準備運動が十分とれなかったこと。
  タイツの締め付けが複合したのか。
  股関節の痛みをラン中のフォーム再調整で回復できなかったこと。
  などが考えられるが正直わからん。
  
* <2018-11-27 Tue>
  右目を網膜剥離して手術した部分が視野欠損して、こうして秋の深まる
  戸外にでて路地に侵入して、その路地の縫い方を単なる日の光の当たり具合からと風の
  方向と雑音と車の動きと人の影に遭う偶然とそれらからの自分の反応をただ何万分の一かの確率かで
  経路を作り上げながら昼飯を食うための店を決定しようとしている。
  視野欠損はその中で憂のもっとも辟易と貶めるものになってもうひと年を数えるか。
  私はこう飯を食うための店を探して必ず失敗する。それほどこの東京という間抜けな
  サービスの能動と受動サービスの形態の実態に呆れてどぶ川をそのエイリアスにしている
  隅田川に流れゆく竹の根を見下ろして、それになりたいと思った。
  流れゆく竹の根その先にはほぼ1mほどの竹とわかる竹が水面に現れていて呼吸という生命の基本の
  運動を表現している。
  時間は正午の手前である。風は山から吹いている。
  その模倣すべき竹の根が数日前の台風の影響で泥水と化したどぶ川のテラス付近を流れていくのを
  みて蔵前橋を渡ろうとした時に見つけてテラスに降り立った。
  その竹の根を手すりを乗り越して凝視した。
  この竹の根はバスケットボールほどの大きさだった。
  するとその傍から銀の魚影がひらめいて去った。
  私はそれを見てもう少し生きてみようと思った。

* <2018-11-29 Thu>
  ある真面目な男の話をしよう。
  その男は不真面目であった。
  だがその男には生涯愛する女がいた。
  だからその男は真面目であった。
  その男は芸術家であり造形するすべてのものはその女から得られていた。
  女が死ぬと男も数年で死んだ。

* <2018-11-29 Thu>
  このまま名もなく過去帳にだれかの長男という記述をされて死んでいくのもせっかくもらった生に申し訳なくなる。
  そういう気もするがそれでもいいと思う。
  日本の都市の航空写真をみると川に淀みができてそこに集まる無数のゴミが街のように見える。
  より大きくなるとより小さいものはゴミとなる。
  ゴミの一片は砂つぶと等価となり東京でひしめく大小のビルは砂つぶのきしめく音を、
  まわりの騒音の中に消え込んでそれらのビルはゴミと等価になる。
  航空写真のゴミは人々の吐き出したゴミと等価となる。
  これらのゴミは不要で一切必要となり、何かの刹那的な夢を求める。
  それらは決して美しくなく美しい。
  それらは価値なく価値がある。
  ただ時間がすべてを否定して砂つぶさえ無になる。
  いや時間さえ無になる。
* <2018-11-29 Thu>
  高千穂の峰々が〜。
  血に染まった。
* <2018-11-29 Thu>
* <2018-12-09 Sun>
  無からなにかが生まれた。
  エネルギーが無から生まれるなら金がなくても生きられる。
  日々の生活は金をもとめて苦慮して生きていっている。
* <2019-01-01 Tue>
  昨日つまりは大晦日から裏磐梯に来ている。
  テレマークスキーをやるために来ている。
  今年ほど前年のショックを引き継いだことはないように思う。
  それは大晦日フジテレビの番組のRIZINで那須川点心VSメイウェザーの試合
  が残念すぎる結果1R TKOで点心が負けたことだ。
  エキシビションだから点心の攻撃をメイウェザーが交わして9分の時間切れ
  という安易な予想をしていたからこの衝撃は計り知れない。
  ショックの内にあるものは宝物である点心がグローブで防御しているのにダメージを受け続け
  三つのダウンを取られたことだ。
  体重差があるにしても引退したボクサーには点心のスピードが勝るとおもっていた。
  ショックは大きいが、丸一日たって昨日の試合を思い出すがそれほどの差があるのか
  という疑問も持ってきた。ガードの上からの一発で点心の脳にダメージが残って
  足も使えずなす術なしになって負けたんだが。
  ガードじゃなくスルーでやればエキシビションの予想のような展開になったとも思われる。
  その想定の練習がなかっただけじゃないのか。
  結果のような差は本当はなかったんじゃないのか。
  ボクサーの試合でありがちなクリンチで逃げて体力を回復して策をねる。
  そして持ち前の学習能力の高さで一撃を入れる。
  そういうことができていた可能性もあるはずだ。
* <2019-01-01 Tue>
  私のテレマークブーツは、scotte excurtion 26.5 cm というもので
  この前身はgarmont の同名のものだ。
  私の選択理由としては、
  + まずサイズだが登山靴やランニングシューズはそれぞれ足の実質サイズより1cmほど大きくしたものを選ぶという定説にしたがってテレマークブーツもこれにしたがったわけだ。
  + もうひとつプラシックブーツで最メジャーなスカルプのT4というものがある、しかし履き比べるとscotte の方がはるかに柔らかい。革靴も試したがそれよりも柔らかい。
  というものだ。
  で今回３シーズン目になるがこのブーツを使っている。
  ところがここのテレマークの先生。私たちは塾長と呼んでいる。
  私がなんでもないところで転んでいるというのでブーツに問題があるのではないかということで、
  スカルプの一つ前のT3の同サイズを試してみることにした。
  9:40分ゲレンデでスタート。
  + 当然硬い感じがする。しかし感触はいいようだ。若干の優越をT3に感じる。T4を買うのが正解だったとも思う。
  + ただ足の甲とじゃっかん左内のくるぶしに当たり感がある。右内くるぶしも若干ある。
  + 14:00まで滑って自分の靴に履き替えてみる。どうだろうこの楽しさ、やはりこのブーツが私にはあっている。
  + T3はブーツの力で屈伸した足をサポートしてくれるのだがexcurtion はそうでなくて足全体で雪面からの衝撃を受けて滑るから楽しいのだ。
  それで結論でないが明日scotteの前身のgarmontの26cmがあるのでそれで練習してみようということになった。
* <2019-01-02 Wed>    
  今日もgarmont 26cmを履いて9:40頃スタート。
  締め付け感は私の26.5cmとは違いかなりフィットしていることがわかる。
  私のサイズはこれだとわかる。
  だが楽しさ感は少し遠のいた感がある。
  すこし足の疲労がきつくなったので、14:00にストップした。
  レストハウスでお茶飲んで時間を潰していると両脚の甲が冷たくてむしろ痛いくらいになっていた。
  結論としては私のサイズは26cmであるとわかった。
  しかし足の甲の問題がひきづることになった。
* <2019-01-03 Thu>    
  昨日から深雪の塾生たちがペンションに入っているので、一緒に猫魔に行く算段を塾長がしてくれていた。
  ４人で塾長のハイエースにのってしっぱーつ。
  彼らはウロコ板でリフトで丸山にいってそこから深雪を探して滑って登ってを楽しむ。
  私はこの一連の練習の3日目、同じようにストイックにテレマークするだけ。
  私は前日は26cmで全部滑っていたのでその感覚から26.5cmに変えたことでの感覚の違いから結果を模索しようとしている。
  リフト１回目、昨晩雪は降らず午後良い湿り気の多い雪が降ったためガリガリの部分がコース常にあった。そこでこける、コケまくる。
  確かに足の付け根の部分が26cmより緩い、完全に下手になっている。
  リフト２回目、バックスを１つ残しから０残しに変更する、若干改善されたもののこける。
  リフト３回目、昨日の26cmに履き替える。昨日の26.cmで気になった甲の問題解決へトライするためバックルを１段ゆるくする。
  いい感じだ、ガリガリでもコントロールして滑れる。
  これで決まりとなる。すなわち私の26.5cmはくそだった。
  さてこれから塾長に結果報告してどうなるのだろう。
* <2019-01-05 Sat>
  12/31-1/1 13500
  1/1 8500
  1/2 8500
  1/3 8500
  1/4 8500
  1/5 8500
  塾  6500
* <2019-02-10 Sun> R10.0 W3.0
  なんと本年20kmが今日になってしまった。
  もう去年10月の230kmの蓄えは消えて体は重く、buildupもできず、
  最終10kmの重たいラストで終わった。
* <2019-02-27 Wed> 筑波山登山計画
  + つくばエクスプレス
    + 浅草(0:48)
    + つくば
  + 関東鉄道バス
    + つくば(0:30)
    + 筑波山神社入り口
  + 登山
    + 筑波山神社入り口バス停
    + 宮脇駅(0:15)
    + 中の茶屋跡(0:40)
    + 御幸ケ原(0:40)
    + 男体山(0:05)
    + 女体山(0:15)
    + 弁慶茶屋跡(0:30)
    + つつじケ丘
  + 関東鉄道バス
    + つつじケ丘(0:30)
    + つくば
  + つくばエクスプレス
    + つくば(0:48)
    + 浅草
* <2019-02-28 Thu> 
  + 楽天にて桜の丸棒43mmx900mmを注文2880円、2019/3/5以降に代引き
    
* <2019-03-03 Sun>　東京マラソン
  + 今日行われた東京マラソンは期待の大迫傑がでるのでどこかに遊びに行くのもやめて
    観戦することにした。
    昨日からの天気予報は雨であった、当たらないことを祈っていたが朝から冷たい雨が
    アスファルトを黒く光らせていた。
    観戦ポイントは、東京マラソンの３箇所の折り返しの一つ蔵前橋から清澄通りを南下
    して門前仲町で20キロのUターンし、再び蔵前橋24キロに戻ってくる２度美味しい場所だ。
    蔵前通りから清澄通りに直角ターンする交差点がほぼ17キロだ。
    その交差点に傘をさして歩いて行くと歩道は隙間もなく観戦客が陣取っていた。
    仕方ないので背の低いばぁさんの後ろでみることにした。
    先行スタートの車椅子のランナーがきて、しばらくしてパトカーや報道車などが
    通り過ぎて先頭集団がきた、よし、大迫は先頭集団のいい位置につけている。
    第二集団も見届けて、蔵前橋の下のトンネルを通って復路の蔵前橋のたもとにつけた。
    往路と同じ様相を期待して待つ、先頭集団がきた、大迫いない。佐藤だけだ。
    大迫は遅れている、コースも後半に入って難所はこの蔵前橋の坂5mほどだ。
    登りにしても大迫の腰が落ちてあの弾けるようなフォームではない。
    大迫の顔を間近にみると苦しそう。まさかこんな私にも坂と忘れていたような
    この坂が苦しいわけがない。その写真をとって、マンションに帰って、
    テレビ観戦に切り替える、もうすでに大きく遅れて、29キロで大迫はリタイア
    してしまった。
    低体温になったのか足の故障かといろいろ考えた。
    で思った。一位エチオピアから四位ケニアまでのアフリカ勢などスナップをみる
    限りアームウォーマーをしていない。
    大会スタートの映像をみてなんで大迫までそんなのつけているのかと思ったが
    この雨だとチームもそれがベストと思ったんだろうと納得していたが、私の経験
    でももうアームウォーマーなんかする必要がないとおもって、もう何年もつけた
    ことがないことない。
    なぜかというと冬の晴れの日でも腕は相当汗をかくから水分を吸って相当重くなり、
    それがボディーブローのように疲労をためることになるからだ。
    雨の日は汗をかき始める前に濡れて熱を奪って行く。
    どの天気でも不要なのだと思っている。
    この日は気温は6度弱、そうとう寒い上に水分を含んで腕から熱を奪って体力を
    消耗していく。
    寒さ対策が逆効果となっているのだ。日本人選手はアームウォーマーをつけていない
    選手は見当たらない。思い込みが蔓延しているんだ。
    一位のエチオピア人が2:04:48。日本人のトップは2:10:21。10分も切れていない。
    おい指導者どもオマイラ!クソじゃねーのかよ。
    あの箱根駅伝もやめちまえ駅伝なんかで消耗するからマラソンのいい選手がもっと
    でてこないんだよ。
    マラソンで集団責任なんかのクソ美意識やめちまえ。
    個人競技で磨けよ。
    その他の思い込みの蔓延について
    + ５本指ソックス。
      私はこれが不要とわかるのに十年かかった。2016の金沢マラソンに参加した時雨だった。
      7キロで足の親指の付け根に痛みが起き始め全ての指に回って行く。
      雨で濡れてこれはしょうがない。練習でもなんども起こっていたからしょうがない。
      そう思っていたがある時付け根でなんで起き始めるんだって考えていたら気づいた
      ５本足の付け根にシワがよってそれがダメージになってるんじゃないかと。
      そして５本足ソックスやめたら７キロで痛くなくなった。それ以上の距離でも痛くない。
      おそらく指の長さや太さなどの個人差があると思うが十把一絡げの市販ソックスだから
      なおさら５本足なんかいらないんだと思う。
    + タイツの上のランニングパンツ
      ファッション。
    + テンションたっぷりのタイツ
      逆効果。

* <2019-03-04 Mon> 確定申告
  + 医療費控除
    + 国民健康保険の医療費のお知らせのリストと照らし合わせ領収書がない場合、以下からフォーマットを印刷して領収書がないもののみ書き出す
      http://www.nta.go.jp/taxes/shiraberu/shinkoku/yoshiki/02/pdf/ref1.pdf
  + dropbox
    + nagaister@gmail.com
      古い
    + nagaihart@gmail.com
      こちらが正しい
* <2019-04-11 木> KAYANO
  キュムラスが650kmにいったのと直面しているくるぶし痛の切り分けのために
  asics に行ってきた。
  銀座のapple storeに行った後に急に思い立っていってしまった。
  有楽町からの方が近かった。
  ニンバスに戻すことを決めていたが、ニンバスは足のひらに入っていたゲルが
  なくなってより反発指向になった、くるぶし痛の原因がキュムラスにあると
  思っていたのでそれではニンバスに戻して対応する魂胆がいきなり砕かれたように思う。
  迷っていたがとりあえず足の計測をすることにする。
  左足を後ろから見た時の傾斜が去年は2.6だったものが5.5度に上がっている、直立した
  状態で測るものだがこれはかなりおかしいことになっている。
  かやのはホールド重視なのでこっちの方が合うはず。
  しかもかやのは足のひらゲルがまだ入っている。
  ルームランナーで両方走ったが左足の着地は相変わらずパタパタしておかしい。
  この時点でキュムラスへの変更した直後に左足だけパタパタしていたのでキュムラスへの変更が
  原因じゃないっぽい。
  左足の傾斜の変化とくるぶし痛の対応への土台整備つまりブレないとことを作るには、かやの
  で行くのがベストと判断、購入。
  １７８００円、高い、直営店モデルなので高いらし。
* <2019-04-11 木> R8.0 W3.0
  故障発生が確実だ。
  7-8km で左足くるぶし内側上部付近に痛みが走る。
  フォームを調整してなんとか回復試みても回復しない。
  道路の状況や体調で発生しない場合もあるがほぼ確実になった。
  先日、キュラムスが650kmを超えるのでアシックスに行ったら左足首の
  角度が急変していた2.6->5.5度になっていた。
  これだとカヤノのホールドが合う、ニンバスのジェルは足のひら側には入らない
  仕様となってキュムラスと同じ方向になっている。
  そのカヤノで今日が二日目、それで再発確実になった。
  実は月曜日4/8 に整形外科で診察を受けていて左足のみたつとふらついて
  立てない現象があるのを発見してもらった。
  x線やエコーから足に損傷はないとのことふらついているので負担が重なって
  くるぶしの痛みに繋がったんだろう。
  でそれはここ数日雨でランニングをやめていたが、今日は晴れたのでそれを
  確認してきたのだ。
  思い起こせば電車の乗車整列時に体制が狂うとか歩いていてもふらつくのような
  現象がでていたことが思い当たってくる。
  明日、リハビリで歩きの状態などをみて次にインソールの制作という計画になるようだ。
  故障の症状をはっきり感じだしたのが2019/2/23だった。
  以前にもくるぶし付近の痛みがでたこともあったがすぐに回復していたのでスルー
  していたが、今回は月間走行を2中から3末まで350km近く伸ばしている過程で起きたので
  まず間違いなく大きなというよりランニング人生に関わる怪我となるだろう。
  先月220km月間走行で体幹も鍛えているからフォームの悪化してではない。
  なぜふらつくのか。
  自前のO脚強制を行なったが時期的に合わない。
  左足のパタパタが起こったことがくるぶし痛の所動になったのではないか。
* <2019-04-17 水> R7.0 W1.0
  左脛骨
* <2019-05-29 水> R7.0 W3.0
  4/26から福岡に帰って家族の状況などに携わっていてまったく走ることを
  をしなかった。
  １ヶ月ぶりの昨日新幹線で帰ってきた。
  さっそく、くるぶし痛のリハビリのために朝四時半から走り始めた。
  慎重に入って5キロ前に若干の違和感が出る。
  一月休んでもまだ出る。
  無理せず、現状を理解したいので7kmで終了する。
  ただ、左足の着地の際、慎重にではなく普通に衝撃を股関節で受けて、
  膝の屈伸で受け、外側の足の裏で浮かすように蹴り出すように心がける。
  そうすると6kmからで痛みが薄らぐ感じがする。
  さっそく、整骨院に行くが一月以上空いているから最初の問診が必要だ。
  電気を入れて、施術されるが初日に施術された時のような痛みがあまりでない。
  筋肉がほぐれているのだろう。
  ウォーターベットで背伸ばしを受けて終了。
  現在わかっていることは以下自分で解決するしかない。
  + 整形外科
    + レントゲンなどでくるぶしに炎症などの問題がないことがわかっている。
    + 座って両足を伸ばし、つま先を手前に引くと左と右で引き上げると左が上がらない。
    + 左足のみで立つとぐらついて立てないことがある。
    + リハビリで左股関節にちゃんと乗れず、外にずれることがあることがわかっている。
  + 整骨院
    + 左の外側の筋肉がかなり硬くなっている。
    + 筋肉をほぐさないとリハビリできない。
    + フォームローラーを使って足の外の筋肉を伸ばす。
    + 腰の高さの台に足をのせ、そこに胸を寄せ股関節の外の筋伸ばし。
* <2019-05-30 木> R10.0 W3.0
* <2019-05-31 金> R10.0 W3.0  
  左足の着地の時に骨盤で受け止めることを意識する。
  慎重に入るとむしろフォームを崩しているとわかってきた。
  build upすると不思議に痛みが起こらない。
  ただ、桜橋の8kmから白髭に向かう凸凹の道ではすぐに違和感がでて継続する。
  それでもラストスパートの新ゴールまではうまくbuild upできて痛みが取れる時がある。
* <2019-06-01 土> R10.0 W3.0
  この四日間のランニングで３月に月間220km走った時と同じレベルまで回復している。
  ４末から５末まで一月以上走っていなかったが筋力は想定外に落ちていなかった。
  おそらくこの「ひだり足くるぶし痛」の原因の80%を今日までのランニングで理解できた
  と思う。
  + 「ひだり足くるぶし痛」の経緯
    + 左足の着地後のばたつき音が気になりフォーム修正に望んだのが2018/10/5この日ゲルキュムラスにシューズ変更。
    + 左足のばたつきの音を少なくするために左足かかとが内側に入れていた、これにより蹴り出すための足が親指と内側土踏まずに移っていた。
    + 左足の親指の左横のタコが右側より相当硬く出来上がっていた。整形外科リハビリ時に指摘されていた。
    + 左足内側で蹴り出していたため着地時の股関節の受け止めが外側にずれていた。（原因）
    + 2018/10からのトピックスと走行距離
      + 2018/10(富山マラソン)(TR194km)
      + 2018/11(福岡帰省)(TR57km)
      + 2018/12(テレマークスキー)(TR40km)
      + 2019/1(テレマークスキー,福岡帰省)(TR10km)
      + 2019/2(福岡帰省,肝臓障害)(後半TR105km)(2/23くるぶし痛を意識)
      + 2019/3(肝臓障害)(TR220km)(くるぶし痛が体幹の筋肉減少?、シューズ?)
      + 2019/4(くるぶし痛のリハビリ)(TR63km)(4/6ゲルカヤ)
      + 2019/5(福岡帰省,くるぶし痛のリハビリ)(TR27km)
  + 「ひだり足くるぶし痛」の概要
    2018/10のシューズ変更が一因となりフォームの修正を意識していく、
    富山マラソンピークでは筋力の増加、一回の走行距離も今まで通り問題なし、もあってくるぶし痛が表面化していなかったが
    その後テレマークへの注力変遷があって走行距離は下がり筋力低下が進んでいた。
    テレマーク終了が2019/1中、その後福岡帰省で走行距離が著しく減少したため筋肉量が減り筋肉の硬化も進んだ。
    2019/2中に東京に帰って肝機能障害対応のため走破距離を伸ばすが左足のばたつきが先に述べた（原因）により顕在化した。
  + 「ひだり足くるぶし痛」に至った原因考察
    + 2019/10のシューズ変更がくるぶし痛に影響を与えたかは不明だがキュムラスに変えた直後からフォームへの意識するようになったのは事実。
    + 2019/3のアシックス銀座のショップでの計測で「かかとの傾斜角度」2018/10(2.6)->2019/4(5.5)に変化していた。
    + テレマークスキー上達のためゴムバンドによるO脚矯正が「かかとの傾斜角度」に影響があったかもしれない。
  + 「ひだり足くるぶし痛」対応
    + 左足着地時股関節でしっかり受け止め足のヒラ外側での蹴り出し意識の継続。
    + 今日まで9kmで起こるが悪路ではもっと蹴り出し意識を強める。
    + 昨年10月から10km以上の走破ができていないので、15,20km走破を目指す。
    + 歩いていても走っていてもある瞬間に起こるがどういう状況でなるのか不明なのでこれを解明する。
    + 逆に痛みが取れる瞬間もあるので同じく解明する。
* <2019-07-23 火> 
 + 福岡空港出発前
   ７月も終盤になってもランニング総距離は０のまま６月終わりに２度走ってくるぶし違和感
   は解消していない。
   今秋のシーズンのフルマラソンのエントリーもするきもなくどんどんエントリーの締め切り
   を見送っている。
   そして両国のマンションを引き払うため今板付にいる。
   家にいるのもなんだから４時間も早くきてしまった。
   sky018スカイマークにまたしてしまった。
   ここの待合もUSB/コンセントなどが整備された座席がいくつもあっていい感じになっている。
   ここで仕事するのもありかもしれない。
   待合の人々が搭乗してしまうと冷房は効きすぎるくらい冷えてくるそして自分のキーの打撃音
   がうるさいかもと聞こえてくる。
   さて、18時について一月ぶりのマンションで何をするのか壁の修正のみは気に掛かるが、もう
   フロアーの傷は諦めてとにかく無事に明け渡したい。明日の１２時から引っ越しでそのあと
   そこにいるのかいるように寝袋とマットは持ってきた。
   明後日11時に不動産屋のチェックを済まして、浅草のapaに宿を取っていて転出などの用事を
   済ませチェックインすれば夜錦糸町の千葉さんとの飲み会を待つだけになる。
   ５年慣れひたしんだマンションをでるのは本当に寂しい。
   なによりもあのランニングコースを走れなくなるのが悲しい。
<2019-08-09 金>
 + https://www.kisaka-direct.com/upload/save_image/images-large/kisaka/instructions/2st-2_ver.1.pdf
* <2019-12-22 Sun>
  + ほうじょうのうみをよむあ
* <2020-02-14 Fri>
  + W1.5 C3.5h
    これ以前にrunを3kmやったが、リハビリ中左膝の内側故障が起こり医者に行くとランナー膝のようだ。
    これで完全にrunが無理になりwark 10kmで10回めどに再起をこころみたがある朝左膝がおかしい。
    しゃがむと痛い、正座ができない、なにをやったのか覚えていない。
    そのうち治ると思っていたが治らない。
    もんもんとして年が明けた。
* <2020-02-16 Sun>
  + 流行り目
    2/14にトライアル東郷橋で軽トラのキーの閉じ込みをやってしまって家まであるくことになった。
    もどりは自転車にしたら久しぶりにサイクリングしたくなって3.5hゆっくり走ってきた。
    やはり坂が出現する楽しい。
    次の日は筋肉痛になったからまだアスリートらしさが少し残っているかもしれないとおもった。
    ただ、朝左目がごろごろしてコンタクト入れてもおかしいので眼科にいったら流行り目かもしれないと
    14d隔離だという。あす右目にも転移していれば決定的らしい。
    自転車で回復をこころみるか。
    北九州マラソンに受かっていればそれを目指してもっと早く回復をこころみようとしたかもしれないが
    落ちてた。そのマラソンが今日あった。
    なんとあたりまえだが中性脂肪が上昇した。
    4月に採血するんでそれまでに戻したい。
    自転車山登りを復活させれば戻せるかもしれないが、随分前の自転車が原因と思われる股関節痛がまたおこるかもしれない。
* <2020-02-18 Tue>
  + せどり
    + app
      + 有料
        + セドリストプレミア
	  バーコード読み取り、月額5400-
	+ プライスター
	  価格追従、ポイントまで追従、一月無料、4800
        + トレジャーパーフェクト
	  お宝商品、一月目9800,２ヶ月目以降3800
      + 無料
        + アマコード
        + chrome 機能
        + ロケスマ
          地図上のピン表示
        + モノレート
          https://mnrate.com/
        + モノサーチPRO
	+ 開店閉店.com
      + 店舗
	+ ドンキホーテ
	  + まじかカード（どんき）ポイントカード利用
	  + app 有用
	  + line@でクーポンもらえる
	  + 展示品、驚安(きょうやす)、特売、セット売りで利益が出る時あり
      + バーコードリーダー
	+ KDC200
	  30000
* <2020-02-18 Tue> C4.0H
  + いつもの釣川ランニングコースをきちんと走るのではなく自転車の機動力を
    楽しみに取り入れながら坂を登ったり未開の道を探して突き当たって、
    振り返った時に想像しない景色に会う、そんなサイクリングをランニングの代わりの
    運動として、ランニングよるの故障のリハビリのその最中の故障からリハビリのための
    ウォーキンング中の故障の最後の手段としてサイクリングをやって今日で２日目だ。

    そんなサイクリングの途中で遭遇する神社や仏閣にその成り立ちが気になった。

    昨年神保町の本屋で買ったアースダイバーは自宅に近い浅草や上野が題材となっている
    から実際の土地勘があるし日本人と生活の環境の歴史的成り立ちへの新しい観点の発見が
    随所にあったためとても面白く読んで終わっていた。

    それをこの生まれ育った宗像にも適用してみたいと思った。

    そのきっかけとなったのが牟田川近隣の集落だ。
    サイクイングコースの横には釣川があり、牟田川の合流から数キロ残して海に流れて込んでいる。

    牟田川は浅くゆるく弧を成して東へとさかのぼるのだが、内側の浅い部分では緩慢の影響と思われる
    海の水と太陽に洗われた薄い砂の色をしていてイナが飛ぶ光景が遠くの上流まで海の水が押し寄せて
    きていたことを容易に想像できるのだ。
    今では護岸に守られ大水でもその形状を崩しようがなく周りの水田群や散財する低山からの水を逃がしたりしている。
    近隣は有名な宗像大社や鎮国寺があり道の駅もあって繁盛している。
    民家は古くからそれらの川の流れとともに一緒に生きてきた佇まいをしており家家は何世代も育てた古い様式
    を伺えるものが多い。
    その民家ずたいに細い道が見える、どこまで続くか興味がある少し迷って鳥居が目に入る。
    大きな道から見える鳥居にはよめないが神社だ。
    小高い山の麓にも小さな鳥居があって石階段が木々の隙間に登って行っている。
    登ってみるとかなり急で中央に取り付けられている白く塗装されたた新し目の一本の鉄柵は登る者と降る者
    ２人分の幅しかないようだ。
    息を切って登ると孟宗竹や杉が丸く切り空を取って見せ、30畳ほどの大きさの社が山を切り開いて鳴らした
    土地に立っている、入り口は二つあるが奥がしめ縄が飾ってあるから参るところで手前が何らかの祭式を行い
    部落の民を迎える門であろう。
    50坪ほどの敷地は社の裏に回り込むことができる裏には石の社と奥に木の社と本殿を2mほどの空中廊下で
    つないであり、窓には大きなガラスが２枚はめ殺しになっている。
    少し異様を感じたが近づくことをせず、参って、降りることにした。
    急な階段と木々の間に見える牟田川はかつてはすぐそこまで海の波が押し寄せていたのだと思った。
    この小山はきっと岬だったのだろう。
    階段を下り終わって鳥居をみると織幡宮と書いてある、おかしい、神社だったはずなのに宮となっている。
    アースダイバーの記憶では神社の横には寺があるはず。
    寺はみ渡らないが宮と神社は２つあったのか。めんどくさくなって宮と神社を一緒にしてしまったのか。
    この合理性の知恵に納得はしていないが４時間も走っていたので疲れて帰途につく。

    その道すがらアースダイバー となってこの宗像の土地にアプローチしてみたくなったのだ。

* <2020-02-19 Wed>
  + アースダイバー 
    アースダイバー とは中沢新一の書著の題名です。
    「アースダイバー」という名称の由来は、世界が一面の水に覆われていたという原初の時代、水底に潜って「新しい世界」の大地の元になるわずかな泥土を持ってきたという、アメリカ先住民の潜水鳥神話に基づいている。第1作『アースダイバー』冒頭のエピグラフには、アルゴンキン語族の神話が掲載されている。
    とwikiにあます。
    私はアースダイバー に感銘を受けて、スカイダイビングやスキューバダイビングのように非日常的な行動すると同じように、
    地球の中へダイビングして非日常感を味合うことアースダイバー することと思っています。
    物理的に穴を掘っていくのではなく現実の空間の中の山、川、民家、神社、仏閣などから過去へ情景を思い巡らすこと
    と思っています。
  + アースダイバー するには手がかりが必要
    + 山と川と海
      山はその昔、岬であったかもしれません。岬は海の波を受けて白いしぶきをあげていて、
      そこに古代の人々は神聖なものをみたかもしれません。
      また海は多くの海産物を与えてくれますが時に漁にいった息子の命を奪っていきます。
      岬の形状の多くは丸い楕円を引き伸ばしたようなもので男性のシンボルを想起させ、白いしぶきは男性の発露をも想起させ海は女の陰部をも想起させ、
      そういう場所には古代よりなにかを祀るものが建立されて守られてきたようです。
    + 祀るもの
      + 日本の古来から続く固有の民族宗教である神道の信仰(神社)
        + 社格
	  神社の格式
        + 格式
          神社の格式は信仰の対象が皇室の祖先神を祀っているのか、地域の神様を祀っているのかというようなその神社が祀っている祭神によって決る。
        + 神社
          神社とは日本の古来から続く固有の民族宗教である神道の信仰で、神々を祀るための建物や施設であり、祭祀を行う組織のこと
        + 社号
	  神社の名前のことで社号には格式の違いによって神宮・宮・大神宮・大社・神社・社の6つに分けられる
          俗社号として天王，権現，明神，山王などがある。
        + 社殿の作り
	  社号によって神社の作りの違いはないが以下２つに分けられる
	  + 神明造（しんめいづくり）
            伊勢神宮に代表される様式です。切妻造の屋根と、入り口は屋根の長辺側にある平入の造りになっています。この神明造から派生した流造や、切妻造の屋根、平入の入り口の建物が二棟連結された八幡造などがあります。
	  + 大社造（たいしゃづくり）
            出雲大社に代表される様式です。切妻造の屋根と、入り口は屋根の短辺側にある妻入の造りになっています。この大社造りから派生したもの住吉造や春日造などがあります。
      + 仏教(寺)
	+ 仏閣
	  寺の建物
    + 寺と神社の違い
      宗教の違いとして神社は神道、お寺は仏教である。
      信仰の対象の違いとして神社は八百万の神（やおよろずのかみ）、お寺は仏様である。
      神社の入り口には鳥居があり、お寺の入り口には山門がある。
      参拝の作法の違いとして神社は二拝二拍手一拝であり、お寺は合掌が基本で手はたたかない。
* <2020-02-21 Fri>
  + せどり
    + 用語
      + プライム会員
　　　　　月額500円でプライム会員になれば、会員特典対象の映画やドラマ、アニメ、Amazon Original 作品が見放題。
      + 「フルフィルメント by Amazon」
	フルフィルメントの業務を細分化すると、「入荷、検品」・「棚要れ、商品保管」・「コール業務、受注処理」・「ピッキング」・「検品」・「梱包」・「発送」となる。
	①リソースの削減。
	②集客の安定性。
	③送料の無料化。
	④代金回収の委託。
	
* <2020-02-29 Sat> C5.5
  釣川を右にみて東郷橋から上流に進んで鹿児島本線の複線の踏切を渡って、流れは穏やかで綺麗ではないがこの釣川の源流を探ってやろうという気持ちが
  湧いてくるが、今日はとりあえず赤間宿を真面目にいったことがなかったから横道にそれる。
  感で大体の位置はわかっているのでだれもいない農道を宿場の面影がありそうな中心へと走らせる。
  住宅街にはいるとすぐ目につくなんと猿田神社（あの猿田彦)だどこにでもあるんだと思う一見公園にみえるがこの辺は武士の屋敷が
  あったのかもしれないと思いながら進んでいくと。
  いきなり寺が現れた。建立して年月は立っていないだろう親鸞聖人の像をそびえる浄万寺の門がみおろしっている。
  横に枯山水の庭があってはデザイン家も加わっただろう的なモダンな作りをしている。
  日差しはやさしく明るく門を照らしている自転車でくるりと輪を書いて宿場道と思われる街道にもどる。
  浄万寺を後にして赤間塾の通り(唐津街道：佐賀の唐津までいく道か)を一旦横切って散策すると鳥居があり今井神社と読める。
  なんとこの神社も個性がある鳥居のすぐ後ろに胴回り3mほどの大きな楠が生えている。
  木の細い作りの鳥居だが楠の方が古いだろう、後から鳥居を洒落ておいたのかそのようなユーモアを感じる。
  赤間塾を城山の方へというか鹿児島本線教育大方面へ遡って県道29号の法然寺を角に赤間上町の交差点をすぎるとすぐ右手に
  山側に須賀神社と谷側に駐車場がある。
  この神社も個性をもつ両脇を赤い門柱に囲まれた鳥居とその向こうに２つ鳥居があって社が見える。
  その参道よこに大砲の玉が奉納されている東郷平八郎の活躍のころ北の津屋崎に砲塔台があって打っていた。
  それがなにかの縁でここにたどり着いたのだろう。
  須賀神社の社の前に立つと小さな看板が左右に貼ってある右が恵比寿神社は左が菅原神社、恵比寿の方に回ると、
  赤い木の鳥居に豊受大神とあり後ろに石の社がたち、横に恵比寿神社が数社あつまっている。
  引き返して左にいくと菅原神社の石の社が控えている。
  兎角にこの近辺の人は短気が多い、１箇所にこれだけ集めるのも短気と合理性の表れだろう。
  もう飽きてきたのでそのまま赤間宿のメイン通りを一挙に下ってハンドルの赴くまま走らせていると、遠くの低い竹林や針葉樹の林横切る
  白いガードレールが走っているこれはおそらく宗像市界へといく道だと想像できる。私はまだiphoneを自転車に装着していないので
  リアルに地図はみることができない。
  しばらく界への方向に自転車を走らせると少し小高い丘のありその横を片側一車線の道路がこちらの
  農道と遠く真っ直ぐな下り坂からゆるい弧気持ちよく混ざっている分岐点には工事看板がある。
  左の丘は急な細い階段を頂上へと向かわせて何箇所か道をそれて休憩としてる。
  丘は１mの高さで溝の侵食をおさえるためコンクリートが先の道路の分岐からもっと上まで続いている。
  そこには自販機が２つあって買うものは落ちて敷き詰められた杉の枯れた葉と小枝をふむ不快感を誘う。
  交わった道路は峠の様相して竹や杉の先々が地形を表して重なり坂だから向かってこいと無言で威圧している。
  まずは、この神社鳥居は中国風のソリをしていて25cmの柱の小さいものだ、少しの平坦な面には数体の地蔵とお供えとして
  ジュースやお茶やカップ酒がある。
  登り旗もあるから祭りの始まりか終わりかを意味して、小さな幕に豊日神社とあったのでここが鳥居の名はよめないが豊日神社とわかる。
  階段は急で足の悪いもの自分もそうだが登りづらいが。イレクパイプを素人つなぎで立てた手すりが両サイドにあって
  助けてくれる。
  登り切ると昔の社跡の土台が苔むして積年をあらわにしてるこの山に車は入らないので道路を切り開いてから
  社の材料を運び入れないと復元は無理だろう。
  その尻込みはいく齢も重ねイラクパイプと簡素な旗を立てただけの良心を少し見せただけに終わっているのだろう。
  さて凍結注意の看板の上部にくぬぎ峠とある。坂好きというノルマを課している身分だからとりあえず峠の頂上を
  目指そう、フロントもリアもギアを全部使って登りきった。
  振り返ると宗像市の看板がある山の中腹を削り出して作った峠には興味するものはないのそのまま引き返して
  白く見えたガードレールの道を降る、あまりにも寒いし下りは苦手なのでブレーキを鳴らして下るとグローバルアリーナ
  の看板が見えた。
  テニスコート、サッカーやラグビーまでのグラウンドがあり、２階建の宿泊施設も完備している。
  地方交付税のまだありがたかった頃の意欲のあった頃の施設で現在はsanixのラグビーチームのホームグラウンドでもある。
  これらの施設へはクヌギ峠を下りきった所の交差点から登らなくてはならない楽かと思えば施設のある頂上までは長い坂が
  待っている、前のギアを一段残して登り切るラグビー場は自然芝で客席は自転車で入ることができるシーズンオフ
  だからできることかもしれないがくまなく施設をみわたすとBBQやら釜飯や自家製パンのレストランなどもある。
  人影は多くないがそれなりに車は止まっている。
  働く人の車が多いのではないかと思うがここにあるレストランに入る胃袋も自転車はロードのランドナーっていう部類だから
  それなりの前傾でここまで登ってきたから飯はいらない。
  なにを求めてここに来たのか、ただ、坂があったからきたんだけど。 
  この施設にすこしほどよい、坂をのぼってきた、あるいは車で子供の楽しみの約束を果たした、という心地よさを感じる。
  そして施設をくまなく自転車で見回って、ここをウォーキングの意味を感受しっきている少しおしゃれかそうでないかの
  人たちにあうがそれは会話を求めるでもないただその空間の意味にだけだと感じる人たちに合うがそれはほとんど俺は意味
  と足の疲れやそれの代償としての会話なんか必要がないのでそれらの人は俺には無意味な風景の一部というか、単なる風景
  になって、人はそれ以上ではないとおもいたかったが、ペダルの重さは人を感じるかもしれないが、それは、激情的な
  意味をこの目の前の低山のつざなりと低山の竹山のコンストラクトが意味のなさを冗長させて、フクロハギの筋肉の疲労を
  増して、疲労が心を通り越して疲労が筋肉のうまい脂身も消し去ってそれが踏みしめるペダルの軋みと合間って、死を
  なんども受け入れたい死こそ生とペダルを踏み込んで坂を登って死にたいを目指したが死にきれず、これを書いている。
  この施設の無意味となんともない脱力感が今も残っている。

* <2020-03-07 Sat>
  としを、しね。
* <2020-03-15 Sun>
 + おしゃべりみーちゃん注文
   + ¥13250-
   + ばあさん用
* <2021-08-23 Mon> PM BF1.0 W1.0
  + 64.1kg
* <2021-08-27 Fri> PM BF1.6 W1.0
  + 数週間前から突然ベアフットランニングならあの生きがいだったランニングを取り戻せるかもと思い始めていた。
  + <2021-08-30 Mon> サンダルでベアフットウォークとランをくみあわせてなんとか１キロは痛みも気にせずはしれることができた。
  + その筋肉痛の回復にmon,thr,wenの三日かけて今日家の周りを距離即して1.6kmのコースを作って走ってみた終始BFランだけだ。
  + 走れた。最後300にBuild upの頂点だ。これもかけれた。
  + やはりなにをやっても左足は優等生
  + 右足は考えないとできないやつだね、
  + これでいきがいをとりもどして、いや死に場所をとりもどせるかもしれない。

* <2021-08-28 Sat> AM BF1.6 W1.0
 + 体が重いが1.6はいけるのでストレッチを十分いれてはしる。
 + ラストスパートもかけていい感じで終わる。
 + ただし穴あきサンダル使用、十分な足のヒラに広さがあるので
   裸足と変わりはないので当分これでやってみる。
   あえてランニングシューズをはかず、やってみる。
   はだしは２００mくらい足の裏を鍛える程度ウォークとランをしている。
* <2021-08-29 Sun> PM BF1.6 W0.5
* <2021-08-30 Mon> PM BF2.0 W1.0
* <2021-08-31 Tue> PM BF2.0 W1.0
* <2021-09-02 Thu> PM BF2.0 W1.0
  + ランニングシューズを吐いてやるがしっくりいかない、サンダルの法がいい。
  + 靴下が原因か
* <2021-09-05 Sun> PM BF2.0 W1.0
* <2021-09-06 Mon> PM BF2.0 W3.0
* <2021-09-07 Tue> PM BF2.0 W1.0
* <2021-09-09 Thu> PM BF3.6 W2.0
 + 1.6kmを二周しラスト400mするので3.6km=3.2km+400mとなる
 + サンダルを山登り用の前が帯タイプで足首だけのものにした、
   弾力はなし、サンダルの面が硬いから小石の痛みは上がってこない。
   これで3.6kmできたのは喜ばしい。
   5.2kmはすぐにできるが明日は3.6kmをもう一度試そう。
 + 親指と中指で挟むタイプかとソールで選ぶのがいい。
 + 長距離になるといつワセリンを使うか考えないと。
 + ベアハンドは極力踵は使わないがつま先だけでなく腹全体着地する。
   着地はスムーズにするがいいようだ。
 + 呼吸はなるように任せているがいずれ、はくはくすうすうになっていくのか。
 + 左ひざの痛みはあるが走っている最中に改善するのが不思議だ。
* <2021-09-11 Sat> BF3.6 W1.0
* <2021-09-12 Sun> BF3.6 W2.0
* <2021-09-14 Tue> BF3.6 W1.0
* <2021-09-15 Wed> BF3.6 W1.0
* <2021-09-16 Thu> BF3.6 W1.0
* <2021-09-17 Fri> BF3.6 W1.0
* <2021-09-19 Sun> BF3.6 W1.0
* <2021-09-20 Mon> BF3.6 W1.0
* <2021-09-21 Tue> BF3.6 W1.0
* <2021-09-24 Fri> BF5.2 W1.0
* <2021-09-25 Sat> BF5.2 W1.0
  + 道路を渡ろうとした時後ろに車の気配を感じて急にストップをかけた瞬間胸に痛みが走った。
    たったこれだけのことで胸痛に悩まされることになる。
    車はアクセルをあげて目の前を通過していった、この運転手殺してやりてえー。
* <2021-09-27 Mon> BF5.2 W1.0
  + 胸痛により10月のベアフットランニングは中止。介護に専念することになる。
* <2021-11-08 Mon> 親父逝去

* <2021-11-14 Sun> BF2.0 W1.0
  + 以前同様、BFで山小屋サンダル履いて再開。
* <2021-11-15 Mon> BF2.0 W0.8
* <2021-11-18 Thu> BF2.0 W1.0
* <2021-11-20 Sat> BF2.0 W1.0
  + ワクチン２回目
* <2021-11-21 Sun> BF2.0 W1.0
* <2021-11-24 Wed> BF2.0 W1.0
* <2021-11-25 Thu> BF3.6 W1.0
  + 2.0km だと体が当たらまず寒いだけで終わるので3.6kmに上げる。
* <2021-11-26 Fri> BF3.6 W1.0
* <2021-11-28 Sun> BF3.6 W1.0
* <2021-11-29 Mon> BF3.6 W1.0
* <2021-12-03 Fri> BF3.6 W.0
* <2021-12-05 Sun> BF3.6 W.0
  + 初めて部落の集団作業である薬師様掃除にでる。
* <2021-12-06 Mon> BF3.6 W1.0
* <2021-12-08 Wed> BF3.6 W1.0
* <2021-12-10 Fri> BF3.6 W1.0
* <2021-12-11 Sat> BF3.6 W1.0
  + 秀円寺(曹洞宗)の檀家として会合に参加する。
* <2021-12-12 Sun> BF5.2 W1.0
* <2021-12-14 Tue> BF5.2 W1.0
* <2021-12-17 Fri> BF5.2 W1.0
* <2021-12-19 Sun> BF5.2 W1.0
* <2021-12-20 Mon> BF5.2 W1.0
* <2021-12-21 Tue> BF5.2 W1.0
* <2021-12-22 Wed> BF5.2 W1.0
* <2021-12-23 Thu> BF5.2 W1.0
* <2021-12-24 Fri> BF5.2 W1.0
* <2021-12-28 Tue> BF5.2 W1.0
* <2021-12-29 Wed> BF6.8 W1.0
  + 6.8kmまで順調にアップしたがここでいくつかの大きな壁にぶち当たる。
    まず一つ目BFではふくらはぎのひらめ筋を酷使するのだがどうも次の日に
    まで回復しないようなのだ。
    これは後にクールの時に強めにひらめ筋を刺激すれば1日でも回復するとわかる。
    シューズは以前と同じ山小屋サンダルだ。
* <2022-01-03 Mon> BF6.8 W1.0    
  + 1.6kmの周回コースを4周+400mの直線が家を中心にしたコースだ。
    これは介護のためにいつでも３分で家に帰ることができるコースである。
* <2022-01-05 Wed> BF6.8 W1.0
* <2022-01-06 Thu> BF6.8 W1.0
* <2022-01-09 Sun> BF6.8 W1.0
* <2022-01-10 Mon> BF6.8 W1.0
* <2022-01-11 Tue> BF6.8 W1.0
* <2022-01-12 Wed> BF6.8 W1.0
* <2022-01-14 Fri> BF6.8 W1.0
* <2022-01-16 Sun> BF6.8 W1.0
* <2022-01-17 Mon> BF6.8 W1.0
* <2022-01-19 Wed> BF6.8 W1.0
* <2022-01-21 Fri> BF6.8 W1.0
* <2022-01-22 Sat> LUNAサンダルべルーナ購入
* <2022-01-24 Mon> BF6.8 W1.0
  + LUNAサンダル着用でベアフットランニング開始。
* <2022-01-25 Tue> BF6.8 W1.0
* <2022-01-28 Fri> BF6.8 W1.0
* <2022-01-30 Sun> BF6.8 W1.0
* <2022-02-04 Fri> 
  + 左足の人差し指あたりに豆を潰した時のような痛みがでたので内科にいって
    痛風がでたといったら痛風じゃないというので整形外科にいった。
    レントゲンでは主な原因は見つからないが関節に薄い筋のようなものが見えるので
    これが原因ではないかとじくろの10%のゲルをもらって塗ることになった。
* <2022-02-06 Sun> BF6.8 W1.0
* <2022-02-08 Tue> BF6.8 W1.0
* <2022-02-09 Wed> BF2.0 W0.0
  + 痛みが出続けていて、その痛みの箇所を探っていると左足の中指が痛むことがわかった。
* <2022-02-14 Mon> 
  + 整形外科に再度見てもらうと中指の裏に２本の神経があるのでそれが圧迫されて起こるのでは
    ないかと飲み薬とゲルをもらう。
    この時インソールを工夫してみたらと言われる。
    足踏まずを上げるインソールがドラッグストアなどにうっているそうである。
    さっそく言ってみたがどれを選んでいいかわからない。
* <2022-02-16 Wed> W3.2
* <2022-02-17 Thu> W3.2
* <2022-02-20 Sun> MF6.8 W1.0
  + インソールを自分でDIYしてやろうと大分まえにかったKAYANO25にたまたまあった別の
    ソールで中指の神経に当たらないように切って二重にしたものを作って走ったら、これが
    ドンピシャまた6.8km走ることができるようになった。
    またLUNAの推奨着地はミッドソールなので足裏全体着地んい変更することにした。
* <2022-02-22 Tue> MF6.8 W1.0
* <2022-02-24 Thu> MF6.8 W1.0
* <2022-02-25 Fri> MF6.8 W1.0
* <2022-02-27 Sun> MF6.8 W1.0
* <2022-02-28 Mon> MF6.8 W1.0
* <2022-03-01 Tue> MF6.8 W1.0
* <2022-03-02 Wed> MF6.8 W1.0
* <2022-03-03 Thu> MF6.8 W1.0
* <2022-03-06 Sun> MF6.8 W1.0
  + またも部落の共同作業納骨堂の整備。
    それが終わって走るが今度は親指に痛みがでてくる、自作インソールでは段差があるので
    それが負荷になっていると思われるのでオーダーメイドインソールでwebを検索すると
    隣の駅にその靴屋がある。
    フィルフィートという靴屋で評判もよさそうだ。
* <2022-03-08 Tue> フィルフィート初見
  + 直接フィルフィートに行ってみるがそれらしい靴屋はない、電話がなんどか話中だったがやっと繋がって
    ると予約のみらしいが時間をとってくれるということなので車で待っていると向こうから車が現れて
    案内されるとそれは普通の民家の庭に作業小屋を立てて運営している若い彼は理学療法士だった。
    もっていった靴と自作インソールをみて二重ソールの段差と靴底の減り具合であきらかな異常な減り方を指摘された。
    確かにBFでたった68km走った靴にして小指付近からの減りが異常多い。
    初期検査代2000円で計測して靴があっているからはじめることになる。
    するとどうも足が右25.1左24.7でKAYANO25は27cmだから大きすぎると指摘をウケる。
    銀座のアシックスでKAYANO25を買った時には足が大きくなっていてそれまで26.5だったのを27.0
    にあげていたのだが3年のブランクで足が縮んだのと変な癖が混じってこの現象になったのではないか
    といわれ、まずは靴を26cmに買い替えてからということになる。
* <2022-03-09 Wed> MF6.8 W1.0 KAYANO28
  + さっそく天神のアシックスのランニングショップに行こうとするがなぜか三越の普通の靴屋
    にきてしまう、アシックスのウォークショップに電話で尋ねるとランニングショップはなくなって
    今はこの辺りではキャナルシティーのゼビオにしかないらしいのでいってみるとKANAYNOとGT
    しか置いてない。両方履き比べるとKAYANOが断然ホールド感がいい。
  + 帰ってKAYANO28で早速走る、するとどうだノーマルインソールで6.8km走れない痛みはでないこと
    がわかった、つまりKAYNO25はお釈迦いなっていたのだ。トータル200km+68kmくらい。
    三年の経年で劣化していたと納得する。
* <2022-03-10 Thu> MF6.8 W1.0 KAYANO28
* <2022-03-11 Fri> MF6.8 W1.0 KAYANO28
* <2022-03-14 Mon> MF6.8 W1.0 KAYANO28+オーダメイドインソール
  + 出来立てのインソールで走る。
    + 明らかに着地と蹴り出しが改善されている。
      しかし、足の裏の小指からかかとにかけて強い疲労感がでる、たぶんこれは今までつかって
      いなかった筋肉に乳酸がたまるので改善されると予想できた。
    + 親指に疲労感か関節痛かわからない圧迫痛がではじめる。
      蹴り出しが小指側にそれていたのが正常に親指に変わっているからだと思う。
    + もう一つ長年の故障の起こり方がわかった、原因と言いたいが原因というのではないと思う。
      踵着地を強くするとくるぶし内側の少し上い痛みがでる。４年前に出だした最初の異常だ。
      ミッドソールで着地したとき踵が着いたときに膝に膿んでいるような痛みを感じる。
      これはくるぶし痛の後にじわ時は起き出した異常だ。
    + ミッドソールでは走れないと思う。
* <2022-03-15 Tue> BF6.8 W1.0 KAYANO28+オーダメイドインソール
  + ここでまたベアフット(フォアフット)にもどすことにした。
    といってもまだ下手なので時々踵がついているので膝には違和感がでている。
  + 親指の圧迫痛は3周でで出す。また中指にも違和感がでだすのが早い。
    つまりオーダインソールを疑いだし、絶望感がではじめたということ。
  + build upして４分後半にはいると不思議に膝の違和感がなくなりスッキリ走れる。
* <2022-03-17 Thu> BF16.4 W1.0 KAYANO28+オーダメイドインソール
  + 前回と同じで３周で親指圧迫痛(右も同様)と中指違和感(右は薄い)がでる。
  + 親指の圧迫痛の向こうにあるものを確かめたいと思い出した。
  + そしていつも3週からビルドアップしていくのだがこの日はビルドをやめて6分前半で走ってみたくなった。
    すると6周走って、親指の圧迫痛がとれだした。7周あたりで左中指痛(鈍痛に近い)がではじめる.
    だがこいつの向こうもみたくなってきた。どうせだから倍の8周走ってやろう。
    8週走ると10周ケリの10マイルにしてやろうとフォレスト・ガンプの気持ちになった。
    さすがに8周半でやばい状態になったのでストレッチをいれたがその後はかるく走れて最後の一周
    はビルドアップして３分代までだせてフィニッシュ、疲れもなく、２周ールしておしまい。
    なお中指痛のむこうはまだみえなかったが、悪化もしなかった。
  + 16.4km走れたということは目標のフルマラソンサブ４が見えてきたということだ。
  + もうひとつ今日で酒やめて連続4日目。
* <2022-03-20 Sun> BF10.0 W1.0 
  + 2日置いて周回コースを走る
    何周にするか考えながら走って６周10kmとした
    両足の親指の鈍痛はでるが軽くなっているのでソールによる矯正の結果だろう
    左中指痛は3kmでで始めたがそれほど悪化せずに8kmあたりいくがその後
    重い鈍痛に変わりストレッチをいれてラスト一周buildupに持って行った
    周回コースはこれが最後になるだろうか。
* <2022-03-21 Mon> BF9.2 W2.0
  + 釣川コースにほぼ三年ぶりに出てみる、釣川河口まで6分前半で有酸素。
    折り返しから上げていこうとするが左足の中指鈍痛は4kmあたりで出始め
    徐々に痛みが増してくる。
    BF(フォアフット)に戻して5日目だがまだ力がないので踵が接地するのが頻発する。
    それに呼応するように膝に内側3/4周くらいに違和感というか痛みがでる。
    意識しないと踵がつく。
    7kmほどで左中指の完全に痛みだすがそれでもなんとかbuildupしてフィニッシュ。

* <2022-03-23 Wed> BF9.2 W2.0
  + 釣川コースに戻って2日目、昨日は雨もあって休んだ。 
    左右の足の親指の圧迫痛は解消したようだ。インソールで改ざんされて本来の
    親指蹴り出しに戻ったための疲労痛だったと思われる。
    ただ左の中指の鈍痛は、5kmででてくる。
    右足の中指も遅れて6kmあたりで違和感がでてくる。
    釣川河口の駐車スペースで筑前大島を遠方にみながらストレッチする。
    なぜかこのストレッチその後のランニングに効果が現れない。
    7kmあたりで、左の鈍痛に右の違和感がおってきて、止めようとするが
    痛みの向こうをみたいし後3km弱だから我慢していく。
    だが、左の痛みに屈した足がかってに踵着地をするから膝の痛みが
    湧いてくる。
    そうして走っていると8kmあたりで右足の中指の違和感が解消された。
    左の痛みは増しているがbuildupしてフィニッシュ。
    右足の回復はつま先の靴内の余裕が貢献しているのかもしれない、
    左足のつま先部分はグーにするにも余裕がなく中指近辺に神経が回っていない
    ように動かない。紐で調整するか、ランニング中のストレッチ方法をあみだす
    かだと思う。
  + 今日で酒やめて10日目。a
f    

    
* <2022-03-25 Fri> BF9.2 W2.0
  + ３回目の釣川標準コース、軽めに釣川河口を折り返して、5分台にあげようとすぐに
    左中指に鈍痛が始まり、本格的に嫌悪感がでるのは6.5kmくらいだ、同じく右は違和感が始まる
    がその後フィニッシュまで痛みは発生しなかった。
    左中指の鈍痛にたまらないので思い切って靴を脱いで5分ほどマッサージをしてみる。
    再スタート後順調に5分前半まであげたが、1.5kmほどで再度鈍痛が始まるが残りわずかなので
    最後3分台まで上げてフィニッシュ。
    オーダメイドインソールの小指側に流れるのを矯正したのだが確かにこれは改善されて
    親指で蹴り出しているのを感じるしたまたま個人で設置しているミラーで確認すると
    前まで情けないフォームだったのがそうでもなくなっているので確実に効果があがっている。
    だが、中指痛はKAYANO28のノーマルインソールの時とさほど変わっていないのだ。
    これは3/28に再度オーダメイドインソールのメンテにいくので相談してみようと思う。
    左つま先の靴内に余裕がないと思うので紐を緩めたこの効果はまで不明だが中指と人差し指
    のひっつき感は依然そのままある。
    靴底を確認すると小指側の削が少しめだつ右の方が若干大きい。
  + 釣川標準コースを距離測で再度測ってみた
    9.2kmは測りみすで9.8km(五月橋折り返し),10.83km(釣川河口折り返し)
    + 宗像大社(4.0km)
    + 玄海中学(5.0km)
    + 五月橋信号(6.0km)
    + 釣川河口(6.5km)折り返し
    + 五月橋信号(7.0km)
    + 玄海中学(8.0km)
    + 川端橋(9.0km)
    + 多礼(10.82km)フィニッシュ
* <2022-03-27 Sun> BF9.8 W2.0
  + 今日はいつもより念入りに足の指のマッサージとストレッチをやってワセリンを初めて
    塗った、しかしストレッチもワセリンもモートンには効果がなかった
  + 今日も釣川河口までいくかまよったが結局五月橋の歩行者ボタン信号がいや
    なのと距離測の再計測で五月橋折り返しでも9.8kmだったのでこれを標準コース
    としようとおもった。
    今日は調子が悪く両足の外の疲労痛がまたでたんで2km手前でストレッチ
    2kmから6分に上げて4kmの宗像大社に交差を渡った時、両足の中指に違和感が
    でた、いろいろ考えたが3kmで出る時4km,5km,6kmとこの痛みのでるタイミング
    が日によって違う、これをモートン病の誤差と言おう
    五月橋の折り返しで靴を脱いでマッサージする
    今日は2kmまで保った
    明日はオーダメイドインソールのメンテ日だから報告の材料は揃ったと思う
    - 小指側に流れるくせは矯正され親指蹴り出しに修正されている
    - モートン病にオーダーソールの効果はないと思われる
      ノーマルソールでも5kmまではいっている
    - ヒールストライクすると左くるぶしの上に痛みがでる
    - ミッドフットだと踵が自分の獣神まで地面についているので踵のぶれ
      がひざへのダメージになって膝痛を慢性的に起こしている
    - 踵が地面につくのは日常でも同じで慢性的膝痛(正座もできない)
      を起こしている
      
* <2022-03-30 Wed> BF10.0 W1.0
  + 3/28 にオーダインソールのメンテをしてもらった。
    伝えた結論はオーダインソールのモートン病に対する効果はない。
    しかし親指蹴り出しと小指に流れる癖は矯正され
    走破距離の伸びにつながった。
    といったものだ。
    心よく修正に応じてくれて。患部あたりに微妙なパーツを貼って
  　削るという作業をおこなった１時間半後完成。
    そのテストが今日になった。なんとなくだが2日も休んでしまった。
    1.6kmの周回コースでテストした。
    + 3kmで左中指に違和感、違和感は面が大きくなった。
    + 左親指、右親指も圧迫痛が現れる、右は2周ほどで消えたが左は続く
    + ジョグでそのまま6周10.0kmに向かうが7.4kgで左モートンの痛み
      がひどくなる、前回、前々回どうようマッサージをいれるシーンだが
      マッサージをいれるとランニングの総仕上げに水をさして達成感が
      中途半端になるのであえてやめる。
    + 左の親指痛は失せて行ったようでモートンだけが残っているが
      そのままラスト１周で5分に上げ最後は3分でフィニッシュ。
    + オーダインソールの修正は痛みが面の拡大に広がった。
      広がった分だけ痛みの増し方が疎ったか、それを狙ったのか。
      親指矯正は少し強くなった。だから親指の痛みは300mから両足につきまとった。
      だがこれは数キロで解消する時がくると思い実際そうなった。
      という結果だった。
      明日以降どのように変化するかだ。
* <2022-03-31 Thu> TR125 KAYANO-TR101
  + 雨で走れず、iphone の天気予報は１時間先もあたらない
  + ASICS ユーザ登録
    + *nagaihart@gmail.com
    + *1
    + https://www.asics.com/jp/ja-jp/メンズランニング/c/ja10600000/?prefn1=goal&prefv1=長く走る
  + インソールのシートみつけたかも
    + https://www.poron.jp/poron/
      + https://www.poron.jp/poron/consumer/
	この色が硬さを表わしているようだ。
	SA-30	1.0～5.0	普通	さくら
	TM-20	2.0～5.0	ソフト	オレンジ
	TM-15	2.0～5.0	ソフト	サーモンレッド
	TG-24	3.0～5.0	普通	オレンジ
	BB-32	3.0～5.0	ソフト	黒
	FW-27	2.0～3.0	普通	ブルーオレンジダークグレー
	FW-27EG	2.0～3.0	普通	ブルーオレンジダークグレー
    + https://nandaka.net/archives/537
    + https://nandaka.net/archives/787
      たぶんアシックスはこのoutholiteの供給受けている
      + OrthoLite（オーソライト）は、グレン・バレット氏が1997年に創業した米国のインソールサプライヤーです。
        アディダス、ニューバランス、アシックス等のリーディングメーカーを含む350以上のブランドに年間5億組以上のOrthoLiteを提供しています。
        特徴と技術は、素材が「オープンセルPUフォーム」であること。
        オープンセルPUフォームは簡単に言うとスポンジです。ウレタンの一種です。そこらじゅうで使われています。
        セルというのはウレタンの中の気泡のことで、その気泡がそれぞれ独立して存在すると空気や水を通さないウレタンになり、防水パッキンやタイヤチューブなどに使用されます。
    + https://walking.asics.com/jp/ja-jp/オーソティック-インナーソール-クッションタイプ/p/TIZ402-11.html?
      outhotech(オーソテック)新物か
  + モートンが起こる瞬間
    + フォアの着地で起こるのではない
      + 根拠
	+ モートン痛の中心に豆ができているのは着地では起こり得ない
	+ 着地ではもっと高い位置(親指や小指)での接触があるのにここには豆ができていない
	+ オーダメイドソールは土踏まずの補強だがまったくモートンの効果が見られない
    + 着地して体の重心が通り過ぎた時、蹴り出しの前に付け根に体重がかかった時に起こる
      + この時豆の部分が最大の圧迫を受けている
      + 痛みはこの蓄積が溢れた瞬間に起きて、次の着地の時に痛みとなると錯覚する
    + じゃあなぜヒールやミッドで起こらなかったんだ。
      + ヒールもミッドも蹴り出す前の瞬間、土踏まずアーチが助けていたからだ
      + フォアの場合付け根部分だけに負担がかかってしまう
  + 解の模索
    1) 足し算でなく引き算する
    2) 靴下の豆の部分を切り取る
       あと２,3回走って確かめたあとやってみる
    3) ノーマルソールの豆の部分を裏から削る
       1) の後確証が得たら古いkayano25でやってみる
* <2022-04-02 Sat> BF10.0 W1.0
  + 左の靴紐先端を2cmほど緩める、以前1cmほどゆるめたがもう一度ためしてみた。
    確かにつま先に余裕ができた。しかし結果モートン対策にはならなかった。
  + 200mで両親指に圧迫痛を感じる
  + 3kmで左中指に違和感がでる、そのまま4kmでモートンの痛みが広がる
  + 7.4kmで痛みは完全にでってあとは我慢するしかなくなる
  + 残り1周でbuild up、速度を上げるとオーダーインソールの土踏まずのサポートが
    着地から蹴り出しまで長く続くのかモートンの痛みは薄れているのか
    心拍が上がるから誤魔化されるのかわからず3分台でフィニッシュ。
* <2022-04-04 Mon> BF10.0 W1.0
  + また1日やすんだ。
  + 300mで両足親指付け根に圧迫痛がでる、これは４周くらいにおさまる。
  + モートンの違和感は4kmあたりからでる、モートンらしい痛みは7km過ぎたあたりで始まり
    8kmあたりでマックスになる。なんとか8.5kmまでいくがストレッチをいれて
    最終周にbuild upしてフィニッシュ
  + オーダーインソールの改修後のテストはこんな感じでモートンに関しては
    依然まったく効果ないのだろう。
  + 改修したことによる親指付け根のダメージは今後におさまるとおもうが様子見。
  + 靴紐に関しては良い感じであるがモートンに関しては効果がない。
  + ここ三日をまとめると、親指は走りはじめから違和感がでて5周(8km)まで続く。
  + モートンは3km-5kmで違和感がでてモートンらしい痛みは7km過ぎから始まり8.5kmでマックス
    になる。
    おそらく今後は同じパターンになると思われる。
* <2022-04-05 Tue> BF9.8 W2.0
  + 500mで両足の親指痛がではじめる。
  + 今日はあたらしい試みで靴下のモートン部分を丸くくり抜いてはしっている。
  + 今日は調子がわるい500mで息が上がるいやな感じがする。
  + 3kmで若干の違和感がでるが5km,6kmと違和感の上昇は起きない。
  + 今日から蹴り出し直後に足の指のグーパーストレッチを入れてみた。
    すこしいい感じである。
  + 穴あき靴下の効果か6kmの五月橋信号折り返しでも差し迫った痛みはでない。
  + 五月橋で念の為ストレッチを入れたがその後5分台をキープして
    さすがに9.5kmあたりでモートンの痛みマックスがでたがそのままフィニッシュ。
* <2022-04-07 Tue> BF9.8 W2.0
  + 500mで両足の親指痛がではじめる。
  + 5kmでモートンの痛みがくるが軽くその後は五月橋折り返しでストレチせず
    折り返してbuilupしようとする。
  + buildupは好調で時々モートンの痛みが悪化するか不安になることもあったが
    なぜかモートン患部一体が熱くなる。これは依然ヒールでやっていた時も同じように
    なったことが何度もあるので良い傾向かと思いながら3分台に上げてフィニッシュ
* <2022-04-09 Sat> BF9.8 W2.0    
  + 今日もおなじように親指痛はでている。
  + それは時が解決すると思うのでモートンだけに注力するがなかなかでてこない。
    8kmで出出すが前回と同じ足のひらが熱くなる現象がでてそのままフィニッシュ。
    モートンは早く走るとストライドが伸びた分インナーの縦アーチのサポートが長くなる。
    そうなることでモートンのマックス痛みの出るタイミングが微妙にずれていくのかもしれない。
* <2022-04-11 Mon> BF9.8 W2.0    
  + 10:00 オーダインソールの２回目の改修だ。
  + 伝えた結論は修正版のインソールは前回と前々回のランからbuildupで早く走ると
    縦アーチのサポートが効き始めてモートンに効果がある。
  + 親指は走り出しすぐにでて最後まででるのでもう一度削ってもらった。
    午後雨が降り出したが晴れが上がっていくのを確信してラン、
    親指の痛みは解消されている。
  + だが今日は気温と湿度が上昇で体調がよくなく6分巡航も芳しくなかった。
    6kmでモートンがではじめなんどかストレッチで逃げようとしたが、
    だめで100mほどwalk して再びアップしてフィニッシュ。
    まあ、こういうもんだ。
  + インラインソールは仕上げフェーズ(黒いシートをずれないように底に貼り付けて）
    で終了、あとは自分でこのソールをベースに構築していくしかない。
  + 10km標準コースが走れるのでいつものルーティンをこなしながら次の15kmや21kmを
    照準にいれて日々ランニング人生を送っていこうと思う。
  + これがランニングだ、依然は自分と気象の戦いだったがこれにモートンが加わった。
* <2022-04-15 Fri> 復活まで
  + ランニングの復活それは非常に長い戦いだった。
    21/9に親父の看取り介護が始まってすぐに看取りの後に私にはなにがあるのだろうと
    あれほど、ランニングといういきがいを怪我により2019/9月より断念してほぼ2年
    もういちど生きがいを取り戻そうと介護での合間を作っていつでも３分で家に戻れる
    1マイルの周回コースを作って望んだ。
    最終手段に選んだのはBF(ベアフット)ランニングだ。
    ベアフットとは裸足で走ることだ。
    1) ベアフットになれるため裸足での試し、サンダルでのランニング開始。
    2) 一周1.6km+400mからだ。基本のランニングトレーニングはbuildupだ。
       心拍最大、速度最大で最後の400mゴールへ向かうトレーニングだ。
    3) 1.6km->3.6km->5.2kmそして6.8kmまでそれぞれ10日間を設定して距離数を伸ばしていきランニングの復活を実現する目論みだ。
    4) 6.8kmで大きな壁にぶつかる。
       1) ベアフット(つまりフォアフット)によるふくらはぎのひらめ筋の痛みと1日ではダメージの回復しないこと。
       2) ダメージの次の日への持ち込みはクール時の強めのふくらはぎへの負担(つま先ラン)をかけることで回復してくる。
       3) 山小屋サンダルからLUNAサンダルのベルーナというモデルに変更したら４日で左足中指周辺でいたみがでた。
          結局この痛みが6.8kmの壁として3ヶ月間も立ちはだかることになる。
       4) ２度ほど医者にいきジクロファナック痛み止め与えられるが改善しない。
       5) LUNAサンダルが痛みの原因だとわかるので中止下駄箱に投げ入れる。
       6) 約200km走行のシューズ(kayano25)にもどすが同様に中指痛がでる、医者のインソールでの
          対応という言葉で市販の土積まず補強インソールをはくが走り始めでだめだとわかる。
          自作インソールを作るこれがヒット6.8kmまで走れる。
          しかし親指の圧迫痛に悩まされる。
    5) オーダメイドインソールとkayano28
       1) オーダーメイドインソールを探すと隣の街に作ってくれるところがあったので早速ためす
          3/13最後の望みで作成、3/14かわらないむしろ親指足の外側に疲労痛がでる,3/15同じ,3/16
          もうあきらめてjogを続ける、親指痛の向こうを見たいと思い,5周目まで走れる６周目で親指痛
          が回復、8周半で中指痛がピークしかたなくストレッチしていたら電話がかかってくる。
          その電話がよい休憩となったのか残り2周をbuildupして16.0km走破。
          オーダインソールはまずはシューズを変えることから始めることになった。
          kayano25は外に流れる癖が異常にでていて27mmだと大きいから26mmがぴったしだということ
          でkayano28で26mmを購入そのインソールにオーダメードインソールを作成することになった。
       2) その後8日間走破して結論、オーダーインソールでは中指痛には効果がない。
          親指痛には効果があるが結果を出すには時間がかかるだろう。
       3) 3/28オーダーインソール改修、トータル６回試すがすべて10km走破、始め２回親指痛がひどい
          中指痛も効果ない、３回目中指痛には少し変化がある痛みに痒みと熱いという感覚が入ってくる
          4,5回ラストまでノンストレッチでbuildupして完了。
       4) 4/11 オーダーインソール改修、一度改修なんなく６kmで中指痛、ストレッチいれて痛みこらへて
          フィニッシュ。親指痛は改善されている。
          正直オーダメイドが決定打にはなっていない。しかしなんらかの改善があって10kmへの距離の復活
          ができているという事実がある。
    6) 10km標準ランニングは可能になった。
       ここからランニングといういきがいを構築する。
  + ツイッターつくろうかな
    - ひとは２面性いな多面性をもつ
    - 多面性の呟き
    - 多面性であるが発信は一人
    - 多面性の呟きがブランチとマージと破棄を繰り返す
    - 履歴と最新
* <2022-04-16 Sat> BF9.8 W2.0
  + 四日ぶりだからか今日は特に調子が悪い
  + 最近は2kmまで胸苦しさが続くが6kmでも胸苦しさが治らない
  + なんどかストレッチいれるがモートンは6km前半ででてbuilupも
    かけれず、最後の多礼までのみ上げてフィニッシュ
* <2022-04-18 Mon> BF9.0 W3.0
  + 今日も調子悪い、胸の苦しさプラス親指の疲労感と圧迫痛
  + 2kmのウォームでも6km/1mに上げられず、5.5kmでモートン痛が本格化
  + 6kmで長めのストレッチを入れて立て直そうとするがbuilupできない
  + モートン痛も悪化ラストの1.5km途中で上げるも失速9.0kmでやめる
  + クールのオークでも親指痛がかいま出る
  + 土踏まずの疲労感、このインソールいるのかと疑いがでてくる
  + 今日は気温湿度も悪くない単純に体調とモートン
* <2022-04-22 Fri> BF9.8 W2.0
  + 今日も苦しいがここ２、３日で一番いい、2kmで6分にあげて、6km折り返しだが
    6.5kmで突然モートン痛。
  + 数度ストレッチいれて最後は1.5km build upして終了。
  + 親指痛と足全体の疲労感があるのでこのインソールは必要か疑問が押し上げて50-50くらいになった。
  + kayano28は約200km超えなんであと600kmとすると４ヶ月、夏を挟むから半年くらい持つか。

* <2022-04-23 Sat> BF9.8 W2.0
* <2022-04-27 Wed> BF9.8 W2.0
* <2022-04-30 Sat> BF9.8 W2.0 TR118.2 KAYANO28 196.5
* <2022-05-01 Sun> BF9.8 W2.0
* <2022-05-02 Mon> BF9.8 W2.0
* <2022-05-08 Sun> BF9.8 W2.0
* <2022-05-10 Tue> BF9.8 W2.0
  + この日もいつもどおりかなり攻めた、しかし若干水分量がすくなかったので
    500mmのペットボトルを買っておぎなった。
    これからまたハードルに当たることになった。
    左親指付け根に痛みがでだした。
* <2022-05-12 Thu> 
  + 蜂須賀
    左親指付け根に痛みは、
    最初はいつもの筋肉痛だと軽く思っていたのだが後日、明後日と痛みが増したので
    蜂須賀整形外科を受信した。
    レントゲンから骨には異常がなさそうということがわかった。
    ただ、レントゲンでは疲労骨折はわからないそうだ。
* <2022-05-13 Fri> 
  + いずみ
    次に内科を受信して痛風を訴えた。
    2022/4/28の血液検査の結果をみると尿酸値が9.7となっている、50日も酒をやめたのに
    尿酸値だけに異常に高い、他に原因がある。医者はあいかわず原因をさぐろうとすることよりも
    薬の処方に注力している。
    診療中もその後考えて、なるほど原因と考えられることがわかった。
    アイスクリームとお菓子だ。酒を0にしたことによる口寂しさもあってこの二つの消費が
    酒の代わりに台頭していたのだ。診療を終わったあとに気づいたので医者には言ってないが、
    次回２W後に尿酸を下げる薬の結果で診察を受けてとのことなのでそこで言えばよいだろう。
  + <2022-05-15 Sun>
    痛みは薬のロキソプロフィン、レパミピドをのんで3日目に治ってきた。
    もしかすると両足の右足付け根の違和感は痛風が原因だったのかもしれない。
* <2022-05-18 Wed> BF9.8 W2.0
  + 久しぶりに朝8:00に吉野家で朝食とって帰ってさっそく畑の道路の草刈りに向かう。
  + 草刈りが終わってドブ掃除ドブに長さ1.2mほど太さ8cmの鉄パイプが寝ていたのを
    引き起こして今日のドブ掃除は終了した。
  + それで7日ぶりにランニング開始。
    ロキソプロフィンは痛みや炎症を抑える薬だから尿酸を下げる効果は無いようだがランニング
    は調子がいい。
    4km過ぎで右足のモートンがで始めるが、左足はでない。
    ロキソプロフィンがモートンの痛みまで抑えているのか。
    最後まで出ずにbuildupもできて終了。
* <2022-05-19 Thu> BF9.8 W2.0
* <2022-05-23 Mon> BF9.8 W2.0
* <2022-05-25 Wed> BF9.8 W2.0
* <2022-05-26 Thu> BF9.8 W2.0 TR88.
* <2022-06-01 Wed> BF9.8 W2.0
 + 5/27 尿酸値を抑えるファブック朝一錠を処方される
 + 次回の血液検査で酒をやめる時に常食していたアイスクリームが原因による尿酸値があがったかどうかの検証を行う
* <2022-06-03 Fri> BF9.8 W2.0
  + 6.5kmでモートン痛がで始めるがそれほど痛みは上がらずbuildupして終了
  + 今日から本格的に断酒を開始する、医者が塩昆布(ふじっこ減塩149円)といっていたので買ってきてお茶のあてにしている
    結構いいかもしれない。飴はカロリーが高いのでやめた。
    塩こん部長(299円)という海苔があったのでそれも一緒にかった。
* <2022-06-04 Sat> BF10.0 W2.0
  + 今日は来るべき夏の気象を教えてくれるような気温風速だった。
  + しかたがないので有酸素で走行距離だけは死守しようという戦法でいくことにした。
  + モートンは6.5kmではじめるが痛みは結局最後までマックスには達していない。
  + 後半は5分40秒を守って有酸素運動になったのを確認して5分前半でかるくフィニッシュする方法にした。
  + これはこれでありだとわかった。buildupよりはかなり疲労感は抑えられている。
  + 気象が悪化して距離を稼ぎたい時はいいようだ。それに本番の実践の速度になる、つまり、
    サブ4なら5:45が巡航速度で35kmまでいきそこからどうあげてサブ４を確実にするかだ。
  + モートンはいままでのような痛みは少ない。いつか21km,12km,15kmを入れていこうと思う。
  + それからKAYANO28のノーマルソールをヒマラヤで1350円で手に入れてある。
  + オーダーに対して貢献度は現在50%まで落ちていると思う。
* <2022-06-06 Mon> BF9.8 W2.0
  + 昨日は大雨今日も残っていたが雨雲レーダで回復しそうなので11時ころ出発
  + 一昨日と昨日の酒のせいか調子がよく無いがノンストップで6km折り返し
  + 風は海風が結構吹いていた帰りは背中にそれを受けて5分ジョグでフィニッシュするのも
    サブ4には面白いトレーニングになると迷ったが結局体がbuildupにした。
  + ここ何日かモートンはでるのだが悪化せず苦にならない程度まで回復か麻痺かしている
  + そろそろ12kmか15kmトレニングを入れてもいいかと思うがまだ本気でそれに移行しようとは決心がつかない
  + 断酒はここ４、5日で2日できている、アイスクリームではなくて、塩コンブをお茶請けにつかっている
  + だが昨日買った塩こん部長の145g塩昆布が塩辛すぎる、フジッコの25%減塩がうまくて塩加減がいい
  + サブ４
    + XS=(1kmの秒数)*総距離,H=(XS/60/60の整数),M=(XS/60/60の余り),S=60*(XS/60/60の少数)
    |------+--------+---------+---------+---------+---------+---------+---------|
    | S-km | 10.000 |  20.000 |  21.098 |  30.000 |  35.000 |  40.000 |  42.195 |
    |------+--------+---------+---------+---------+---------+---------+---------|
    | 6:00 |  60:00 | 2:00:00 | 2:06:35 | 3:00:00 | 3:30:00 | 4:00:00 | 4:13:10 |
    | 5:50 |  58:20 | 1:56:40 | 2:01:40 | 2:55:00 | 3:24.10 | 3:53:20 | 4:06:08 |
    | 5:45 |  57:30 | 1:55:00 | 2:00:45 | 2:53:30 | 3:21:15 | 3:50:00 | 4:02:38 |
    | 5:40 |  56:40 | 1:53:20 | 1:59:00 | 2:51:00 | 3:18:20 | 3:46:40 | 3:59:07 |
    | 5:30 |  55:00 | 1:50:00 | 1:55:30 | 2:46:00 | 3:13:30 | 3:40:00 | 3:52.04 |
    | 5:20 |  53:20 | 1:48:20 | 1:53:40 | 2:41:00 | 3:07:40 | 3:33:20 | 3:45:02 |
    | 5:10 |  51:40 | 1:46:40 | 1:51:50 | 2:36:00 | 3:01:50 | 3:26:40 | 3:38:01 |
    | 5:00 |  50:00 | 1:45:00 | 1:50:00 | 2:31:00 | 2:56:00 | 3:20:00 | 3:30:58 |
    | 4:50 |  48:20 | 1:43:20 | 1:48:10 | 2:26:00 | 2:49:10 | 3:14:20 | 3:23:57 |
    |------+--------+---------+---------+---------+---------+---------+---------|
* <2022-06-07 Tue> BF9.8 W2.0
  + 今日は寒いと思ったが2kmから暑いと感じだし湿度も高いので苦しかったが、モートンの強烈な痛みもでず
    buildupでフィニッシュした
  + 自分用のマラソン大会攻略アプリできるかな
  + 剣道やり直してみるかとおもったら銃剣道の方が面白いと思えてきた
  + そうすると剣道との異種格闘技がおもしろいと思えてきた
  + ランニングコースに犬の糞の固め打ちが何箇所もある、これって2022/6/1施工されたペットチップ埋め込み
    義務化に関係してないか
  + 市役所に電話したら看板を設置するか回覧板を回すかしかできないらしい、イエローチョークは道路法など
    にひっかかりできないらしい
  + さっき農事班長が穴熊の親子が家の裏にでて、ぎゃーぎゃー騒いで子育てで子供が側溝に落ちたりして咥えて
    助けたとかの写真をとっていた
  + ランニングコースの犬の糞の固め打ちってこれ穴熊じゃ無いか?
  + 調べるとそうかもしれない、固め打ちの４箇所すべて同サイズ同形状、インターネットの画像にそっくり
  + そう考えると80%以上の確率で穴熊と思われる
  + 犬の飼い主に抱いていた嫌悪と侮蔑の思いが消えて自分の愚かさを悔いる、から明日市役所に謝るかも

* <2022-06-09 Thu> BF9.8 W2.0 (NIS)
  + Normal In Sole にしたさほどかわらないとおもった
* <2022-06-10 Fri> BF9.8 W2.0 (NIS)
  + Normal In Sole にしたさほどかわらないとおもったが
    やはりモートンは5.5kmあたりからでてきて大きくなった
* <2022-06-12 Sun> BF9.8 W2.0 (OIS)
* <2022-06-20 Mon> BF9.8 W2.0 (OIS)
  + Order In Sole にもどした最近は痛みがでにくくなった
* <2022-06-23 Thu> BF6.0 W2.0 (OIS)
  + 暑くて川端井堰でおりかえした、jogで終わり。
* <2022-06-24 Fri> BF9.8 W2.0 (OIS)
  + AM8:00から開始なんとかbuildupして終了
* <2022-06-26 Sun> BF9.8 W2.0 (OIS)
  + AM6:00から開始なんとかbuildupして終了
* <2022-06-30 Thu> BF4.0 W0.4 TR120
  + Total Run(120km)
* <2022-07-07 Thu> BF9.8 W2.0
  + 痛風が数日前に再発、余っていた痛み止めをのんだら走れるようになった
  + AM6:00開始、川端ヰセキ過ぎからは玄海小学校までサイクリングコースの横をはしると日陰になる
  + 湿度が高くラストスパートのみで終わり
  + 汗を３lかいていたので測ってみたら59.7だった
* <2022-07-14 Thu> BF9.8 W2.0 TR20
* <2022-08-28 Sun> BF3.6 W2.0
  + 秋の気配と禁酒を決心してまた周回コース２周より開始。
  + 足の筋肉がひとまわり落ちている。
* <2022-08-29 Mon> BF3.6 W3.0
* <2022-08-30 Tue> BF3.6 W1.0
* <2022-08-31 Wed> BF5.2 W2.0
* <2022-09-03 Sat> BF5.2 W2.0 TR20
* <2022-09-03 Sat> BF5.2 W2.0
* <2022-09-05 Mon> BF5.2 W2.0
* <2022-09-07 Wed> BF5.2 W2.0
* <2022-09-08 Thu> BF6.8 W2.0
* <2022-09-09 Fri> BF6.8 W2.0
* <2022-09-11 Sun> BF6.8 W2.0
* <2022-09-12 Mon> BF6.8 W2.0
* <2022-09-16 Fri> BF6.8 W2.0
* <2022-09-17 Sat> BF9.8 W2.0
* <2022-09-21 Wed> BF9.8 W2.0
* <2022-09-22 Thu> BF9.8 W2.0
* <2022-09-23 Fri> BF9.8 W2.0
* <2022-09-24 Sat> BF9.8 W2.0
* <2022-09-26 Mon> BF9.8 W2.0
* <2022-09-28 Wed> BF9.8 W2.0
* <2022-09-29 Thu> BF9.8 W2.0
* <2022-09-30 Fri> BF9.8 W2.0 TR143
* <2022-10-04 Tue> BF9.0 W2.0
* <2022-10-05 Wed> BF10.0 W2.0
* <2022-10-06 Thu> BF10.0 W2.0
* <2022-10-09 Sun> BF9.8 W2.0
* <2022-10-10 Mon> BF9.8 W2.0
* <2022-10-12 Wed> BF9.8 W2.0
* <2022-10-14 Fri> BF9.8 W2.0
* <2022-10-18 Tue> BF9.8 W2.0
* <2022-10-19 Wed> BF9.8 W2.0
* <2022-10-23 Sun> BF9.8 W2.0
* <2022-10-27 Thu> BF9.8 W2.0
* <2022-10-28 Fri> BF9.8 W2.0
* <2022-10-30 Sun> BF9.8 W2.0
* <2022-10-31 Mon> BF10.0 W2.0 TR140 KAYANO28-TR727
* <2022-11-02 Wed> BF9.8 W2.0
* <2022-11-06 Sun> BF11.0 W2.0
* <2022-11-07 Mon> BF11.0 W2.0
* <2022-11-09 Wed> BF9.8 W2.0
  + GEL-katano29(26.5cm 2EE)購入
    イオンに在庫なく赤間ヒマラヤにいくも在庫なく新宮ヒマラヤで購入
* <2022-11-10 Thu> BF9.8 W2.0
  + 0kmでもモートン違和感発生、紐の縛りが苦しいから途中で緩めるも一度でた
    モートンは回復せず、Buildupかけられず、蜂須賀整形予約
* <2022-11-12 Sat> BF9.8 W2.0
  + kayano28をでオーダーインソール変更する、いままでどおりで近い仕上げにもっていけそうだが
    気温が暑くてはっきりとは旧シューズによるモートンがでるとは言えない。
    たが確かにkayano28は寿命がちかいだろう。
* <2022-11-13 Sun> BF8.0 W2.0
  + kayano29をノーマルソールに変更する、2kmで違和感、そのままストレッチやマッサージするも
    完走できず。
* <2022-11-14 Mon> BF9.8 W2.0
  + kayano29でオーダーインソールではしる4kmで違和感でるが7kmまでもつ以降は痛みに変わるが
    buildup完走、たまたま2km過ぎで8:30だった、ゴールで9:00だった、8kmを30分で走破していた
    けっこうわれながらすごいと思われる
  + 8:30 に時計みたのは10:20の蜂須賀整形予約に間に合わせるためには折り返しを短くする配慮
    が必要と思えたが調子をみたいのでいつものコースでこの結果。
  + 蜂須賀ではまず、手術しても再発するだろうからただ痛いだけ、ソールや走り方などで調整したほうがいよい。
    と医者。
    痛風の痛み止めが効くというとそれを服用するのもありだと言われたので2w分ロきそプロフェンとアルじオキサ
    を処方、塗り薬ももらう。
  + SUB4戦略
    + オーダーインソールででこまでいけるかトライアンドエラー
    + テーピング(整足テーピング:折尾駅にフランチャイズ)を試す
    + ランニングフォームを再度みなおす。
    + 痛み止め(３日前服用開始)トライアンドエラー(北九州マラソン定員割れにエントリーするか?)
  + 北九州マラソンエントリー(2023/2/19))して15825円払い込んできた
  + 2022/3にGEL-kayano28でオーダーしました宗像大井の永井です。
    ご無沙汰しています。
    最近kayano28が寿命と感じkayano29に変更してオーダーインソール試したところ、kayano28より
    もモートン病の出方が、だいたい,
     a. 7km/違和感,9km/最大痛みという感じのものが、
     b. 4km/違和感,7km/最大痛みのようになってしまいました。
    おそらくベイパーの流れでkayanoの形状が変わったためと思いますが、新しいインソールをオーダー
    することで前の(a.)のパフォーマンスいけますでしょうか?
  + ソール自分で作れば?
    確かに自分で作ればいいかも、でんなー!
    
   

